### ISSUE TITLE
[BUG] The mongodb jobrunr collections cannot be created

### ISSUE THREAD

**Issue by phoenixsbk** [jobrunr/jobrunr#101]
**Describe the bug**
When running with spring-boot and jobrunr with mongodb configured, the server cannot get started and the mongodb collections are not well configured.

**Environment**
I'm using version jobrunr 1.3.0
I'm running on JRE / JDK OPENJDK 11
I'm using the following StorageProvider MongoDBStorageProvider

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
I've configured a simple spring boot REST service with spring-boot-starter-data-mongodb and configured my mongodb instance like below:
```yaml
spring.data.mongodb.uri: mongodb://mongocluster1.com:27017,mongocluster2.com:27017,mongocluster3.com:27017/mydatabase
```
When start the server, I can see the collection of "jobs" being created but the next M002_CreateRecurringJobsIndex didn't create any collections.

**Expected behavior**
jobrunr should be able to run with mongodb configuration and create the collections at very first time running.

**Additional context**
I think the problem is due to this method:
`https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/storage/nosql/mongo/migrations/MongoMigration.java#L13`
Every migration should create a collection of its own name, but the key point here is that the "name" is not used inside the creation process but ignored and use the same "metadata" as name, which cause a create failure, but this failure/exception is swallowed in the M00X tasks and ignored.

**Comment by rdehuyss** [comment]
Great catch - I don't understand how the tests then succeeded.
