### ISSUE TITLE
[Improvement] Better BackgroundJobServer initialization in Spring

### ISSUE THREAD

**Issue by SardarNL** [jobrunr/jobrunr#1010]
We are facing two minor problems with default JobRunr Spring Boot starter:

- `BackgroundJobServer` is always started before bean is created. A custom `BeanPostProcessor` is unable to configure server before it starts. Fix: use `initMethod = "start"` which was explicitly designed to allow post processors customize bean before/after it is initialized.
- `RetryFilter` is added using hard-coded list. We are using custom `RetryFilter` that is aware of domain specifics. Fix: obtain `JobFilter` list from container, by default there is just default `RetryFilter`.

I've made a pull request which implements this small yet very needed improvement https://github.com/jobrunr/jobrunr/pull/1009

**Comment by rdehuyss** [comment]
Let's continue the discussion in https://github.com/jobrunr/jobrunr/pull/1009.
