### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by timinho111** [jobrunr/jobrunr#1014]
SevereJobRunrException occurred in BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3: Could not resolve ConcurrentJobModificationException

### Runtime information
- __Timestamp__: 2023-08-16T10:18:10.778198253Z
- __Location__: BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3
- __JobRunr Version__: 6.1.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.7
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: dbf69ea5-a27f-4f59-83ee-d95c90cd1999
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2023-08-16T10:13:36.274432Z, lastHeartbeat: 2023-08-16T10:18:06.556999Z)
- BackgroundJobServer id: 18d1821e-ae48-4dab-a252-561fd491d8d3
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2023-08-16T10:18:09.765695Z, lastHeartbeat: 2023-08-16T10:18:09.777147Z)

#### Concurrent modified jobs:
Job id: 54b3fb95-44c9-4e19-80fa-0ab374972078
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 241; Storage version: 242
	Local state: DELETED (at 2023-08-16T10:12:52.870090038Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857746933Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T09:00:47.163892892Z) ← ENQUEUED (at 2023-08-16T09:00:46.953703475Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053347609Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829082899Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T09:00:47.163892892Z) ← ENQUEUED (at 2023-08-16T09:00:46.953703475Z)
Job id: d076bb74-db06-4dd4-bb6a-772d0bf01f95
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 301; Storage version: 302
	Local state: DELETED (at 2023-08-16T10:12:52.871882560Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857747480Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:45:35.439235248Z) ← ENQUEUED (at 2023-08-16T08:45:30.565966283Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053384122Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829083360Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:45:35.439235248Z) ← ENQUEUED (at 2023-08-16T08:45:30.565966283Z)
Job id: 63fa2b89-5f26-40d5-a77f-d36bb4307fd9
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 322; Storage version: 323
	Local state: DELETED (at 2023-08-16T10:12:52.875571831Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857747912Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:40:15.954662367Z) ← ENQUEUED (at 2023-08-16T08:40:15.709744132Z)
	Storage state: DELETED (at 2023-08-16T10:12:52.427228759Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829083718Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:40:15.954662367Z) ← ENQUEUED (at 2023-08-16T08:40:15.709744132Z)
Job id: 539728de-3435-495f-9244-e90bde364a24
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 281; Storage version: 282
	Local state: DELETED (at 2023-08-16T10:12:52.877353862Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857748282Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:50:35.448061627Z) ← ENQUEUED (at 2023-08-16T08:50:30.608800311Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053388919Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829084044Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:50:35.448061627Z) ← ENQUEUED (at 2023-08-16T08:50:30.608800311Z)
Job id: 4d99890a-046c-4e9d-8ff6-2b0627c9a1b7
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 321; Storage version: 322
	Local state: DELETED (at 2023-08-16T10:12:52.886315143Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857748645Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:40:35.234237761Z) ← ENQUEUED (at 2023-08-16T08:40:30.637715744Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053393280Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829084451Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:40:35.234237761Z) ← ENQUEUED (at 2023-08-16T08:40:30.637715744Z)
Job id: 207162d5-f0a3-41ed-8162-2d56280f9718
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 261; Storage version: 262
	Local state: DELETED (at 2023-08-16T10:12:52.887775135Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857748923Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:55:35.938857784Z) ← ENQUEUED (at 2023-08-16T08:55:30.895231935Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053397247Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829084688Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T08:55:35.938857784Z) ← ENQUEUED (at 2023-08-16T08:55:30.895231935Z)
Job id: 01ec161d-bd6b-41b4-a638-7ff33ef6641b
Occurred at: 2023-08-16T10:18:10.778158806Z
	Local version: 227; Storage version: 228
	Local state: DELETED (at 2023-08-16T10:12:52.888906508Z) ← PROCESSING (updated at 2023-08-16T10:12:52.857749325Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T09:05:34.988036838Z) ← ENQUEUED (at 2023-08-16T09:05:30.557323945Z)
	Storage state: DELETED (at 2023-08-16T10:12:46.053401251Z) ← PROCESSING (updated at 2023-08-16T10:12:37.829084970Z on BackgroundJobServer 18d1821e-ae48-4dab-a252-561fd491d8d3 and started at 2023-08-16T09:05:34.988036838Z) ← ENQUEUED (at 2023-08-16T09:05:30.557323945Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:78)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:48)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
For OSS, we only provide support for the latest version of JobRunr which is 7.
