### ISSUE TITLE
RetryFilter does not work

### ISSUE THREAD

**Issue by jemieeffendy** [jobrunr/jobrunr#104]
Hi,

I am trying to setup RetryFilter, but it does not work properly. My suspicion is the default retry filter overrides what i placed in. Can someone help?

**Comment by rdehuyss** [comment]
Hi @jemieeffendy ,

I just tried to reproduce this and all appears to be working well:

```java
            JobRunr
                .configure()
                .withJobFilter(new RetryFilter(2,10))
                .useStorageProvider(storageProvider)
                .useDashboard(3000)
                .useBackgroundJobServer(backgroundJobServer)
                .initialize();
```

![image](https://user-images.githubusercontent.com/567842/110645158-069e4a00-81b6-11eb-81ea-baa77b6d74ff.png)


If I read your debugging explanation, there is something odd though: it is indeed correct that there are 2 retryfilters, the default one and the one you configured. **_But_**, your filter (with only 2 retries) should be last (so not above the default retry filter). 

See also https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/filters/JobDefaultFilters.java#L23-L26

Here you see the method `getAllJobFilters` where the two default filters are added first and then your specific `JobFilters` (which should come last). 

Can you setup a small Github repo that reproduces the issue? That way, I can see what is going on.
