### ISSUE TITLE
[BUG] SevereJobRunrException occurred in BackgroundJobServer fb1e8c43-e9ef-4729-8227-419315020649: Could not resolve ConcurrentJobModificationException

### ISSUE THREAD

**Issue by suchy30** [jobrunr/jobrunr#1056]
It occurs randomly, sometimes after a minute, sometimes after 2 hours. I had the same issue with Jobrunr 7.0.0 and older. Is something on my side or something that should be fixed in Jobrunr? It's java 17 with spring boot 3, postgres database (PostgreSQL 14.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), 64-bit), running in k8s (with only one replica).

### Runtime information
- __Timestamp__: 2024-06-11T15:25:45.893520844Z
- __Location__: BackgroundJobServer fb1e8c43-e9ef-4729-8227-419315020649
- __JobRunr Version__: 7.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.11
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: fb1e8c43-e9ef-4729-8227-419315020649
(workerPoolSize: 80, pollIntervalInSeconds: 15, firstHeartbeat: 2024-06-11T11:38:12.472040Z, lastHeartbeat: 2024-06-11T15:25:44.698428Z)

#### Concurrent modified jobs:
Job id: 019007e7-bc14-7623-a2ef-988b756ab334
	Job Name: Enqueue new check kValidator state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.KValidationJob.enqueuekValidatorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882581108Z) ← SCHEDULED (at 2024-06-11T15:25:45.876022598Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880801250Z) ← SCHEDULED (at 2024-06-11T15:25:45.876022598Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab335
	Job Name: Enqueue new check status message state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.AssembleStatusMessageJob.enqueueAssembleStatusMessageCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882582089Z) ← SCHEDULED (at 2024-06-11T15:25:45.876234467Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803207Z) ← SCHEDULED (at 2024-06-11T15:25:45.876234467Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab336
	Job Name: Enqueue new check status message state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DisassembleStatusMessageJob.enqueueDisassembleStatusMessageCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882582313Z) ← SCHEDULED (at 2024-06-11T15:25:45.876393308Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803447Z) ← SCHEDULED (at 2024-06-11T15:25:45.876393308Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab337
	Job Name: Enqueue new check Document assemble state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.AssembleDocumentJob.enqueueDocumentAssembleCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588274Z) ← SCHEDULED (at 2024-06-11T15:25:45.876524060Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803629Z) ← SCHEDULED (at 2024-06-11T15:25:45.876524060Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab338
	Job Name: Enqueue new check databaseValidation state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DatabaseValidationJob.enqueueDatabaseValidationCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588508Z) ← SCHEDULED (at 2024-06-11T15:25:45.876685716Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803810Z) ← SCHEDULED (at 2024-06-11T15:25:45.876685716Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab339
	Job Name: pl.am.demo.processor.test.scheduling.receive.job.DecompressFileJob.enqueueFileCompressCheck()
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DecompressFileJob.enqueueFileCompressCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588689Z) ← SCHEDULED (at 2024-06-11T15:25:45.876819399Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803993Z) ← SCHEDULED (at 2024-06-11T15:25:45.876819399Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab33a
	Job Name: Enqueue new check fileCompressor state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.FileCompressorJob.enqueueFileCompressCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588864Z) ← SCHEDULED (at 2024-06-11T15:25:45.876954137Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804177Z) ← SCHEDULED (at 2024-06-11T15:25:45.876954137Z)
Job id: 019007e7-bc15-733e-b96f-fa027e87c0c2
	Job Name: Enqueue new check fileCompressor state
	Job Signature: pl.am.demo.processor.test.scheduling.job.pspis.testFileCompressorJob.enqueueFileCompressorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882589040Z) ← SCHEDULED (at 2024-06-11T15:25:45.877091722Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804353Z) ← SCHEDULED (at 2024-06-11T15:25:45.877091722Z)
Job id: 019007e7-bc15-733e-b96f-fa027e87c0c3
	Job Name: Enqueue new check kValidator state
	Job Signature: pl.am.demo.processor.test.scheduling.job.pspis.testKValidationJob.enqueuekValidatorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882589219Z) ← SCHEDULED (at 2024-06-11T15:25:45.877219474Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804540Z) ← SCHEDULED (at 2024-06-11T15:25:45.877219474Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 019007e7-bc14-7623-a2ef-988b756ab334, 019007e7-bc14-7623-a2ef-988b756ab335, 019007e7-bc14-7623-a2ef-988b756ab336, 019007e7-bc14-7623-a2ef-988b756ab337, 019007e7-bc14-7623-a2ef-988b756ab338, 019007e7-bc14-7623-a2ef-988b756ab339, 019007e7-bc14-7623-a2ef-988b756ab33a, 019007e7-bc15-733e-b96f-fa027e87c0c2, 019007e7-bc15-733e-b96f-fa027e87c0c3

## Concurrent modified jobs:
Job id: 019007e7-bc14-7623-a2ef-988b756ab334
	Job Name: Enqueue new check kValidator state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.KValidationJob.enqueuekValidatorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882581108Z) ← SCHEDULED (at 2024-06-11T15:25:45.876022598Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880801250Z) ← SCHEDULED (at 2024-06-11T15:25:45.876022598Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab335
	Job Name: Enqueue new check status message state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.AssembleStatusMessageJob.enqueueAssembleStatusMessageCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882582089Z) ← SCHEDULED (at 2024-06-11T15:25:45.876234467Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803207Z) ← SCHEDULED (at 2024-06-11T15:25:45.876234467Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab336
	Job Name: Enqueue new check status message state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DisassembleStatusMessageJob.enqueueDisassembleStatusMessageCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882582313Z) ← SCHEDULED (at 2024-06-11T15:25:45.876393308Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803447Z) ← SCHEDULED (at 2024-06-11T15:25:45.876393308Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab337
	Job Name: Enqueue new check Document assemble state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.AssembleDocumentJob.enqueueDocumentAssembleCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588274Z) ← SCHEDULED (at 2024-06-11T15:25:45.876524060Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803629Z) ← SCHEDULED (at 2024-06-11T15:25:45.876524060Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab338
	Job Name: Enqueue new check databaseValidation state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DatabaseValidationJob.enqueueDatabaseValidationCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588508Z) ← SCHEDULED (at 2024-06-11T15:25:45.876685716Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803810Z) ← SCHEDULED (at 2024-06-11T15:25:45.876685716Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab339
	Job Name: pl.am.demo.processor.test.scheduling.receive.job.DecompressFileJob.enqueueFileCompressCheck()
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.DecompressFileJob.enqueueFileCompressCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588689Z) ← SCHEDULED (at 2024-06-11T15:25:45.876819399Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880803993Z) ← SCHEDULED (at 2024-06-11T15:25:45.876819399Z)
Job id: 019007e7-bc14-7623-a2ef-988b756ab33a
	Job Name: Enqueue new check fileCompressor state
	Job Signature: pl.am.demo.processor.test.scheduling.receive.job.FileCompressorJob.enqueueFileCompressCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882588864Z) ← SCHEDULED (at 2024-06-11T15:25:45.876954137Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804177Z) ← SCHEDULED (at 2024-06-11T15:25:45.876954137Z)
Job id: 019007e7-bc15-733e-b96f-fa027e87c0c2
	Job Name: Enqueue new check fileCompressor state
	Job Signature: pl.am.demo.processor.test.scheduling.job.pspis.testFileCompressorJob.enqueueFileCompressorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882589040Z) ← SCHEDULED (at 2024-06-11T15:25:45.877091722Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804353Z) ← SCHEDULED (at 2024-06-11T15:25:45.877091722Z)
Job id: 019007e7-bc15-733e-b96f-fa027e87c0c3
	Job Name: Enqueue new check kValidator state
	Job Signature: pl.am.demo.processor.test.scheduling.job.pspis.testKValidationJob.enqueuekValidatorCheck()
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-06-11T15:25:45.882589219Z) ← SCHEDULED (at 2024-06-11T15:25:45.877219474Z)
	Storage state: ENQUEUED (at 2024-06-11T15:25:45.880804540Z) ← SCHEDULED (at 2024-06-11T15:25:45.877219474Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 019007e7-bc14-7623-a2ef-988b756ab334, 019007e7-bc14-7623-a2ef-988b756ab335, 019007e7-bc14-7623-a2ef-988b756ab336, 019007e7-bc14-7623-a2ef-988b756ab337, 019007e7-bc14-7623-a2ef-988b756ab338, 019007e7-bc14-7623-a2ef-988b756ab339, 019007e7-bc14-7623-a2ef-988b756ab33a, 019007e7-bc15-733e-b96f-fa027e87c0c2, 019007e7-bc15-733e-b96f-fa027e87c0c3
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 17 more

```

Jobrunr config.
```
@Configuration
@RequiredArgsConstructor
public class JobRunrConfig {

  private final List<JobFilter> filters;

  @Bean
  @ConditionalOnProperty(name = "org.jobrunr.background-job-server.enabled")
  public JobRunrConfigurationResult jobRunrConfigurationResult(StorageProvider storageProvider, JsonMapper jobRunrJsonMapper, JobActivator jobActivator,
      BackgroundJobServerConfiguration backgroundJobServerConfiguration) {
    return JobRunr.configure()
        .useJobActivator(jobActivator)
        .useJsonMapper(jobRunrJsonMapper)
        .useStorageProvider(storageProvider)
        .withJobFilter(filters.toArray(new JobFilter[0]))
        .useBackgroundJobServer(backgroundJobServerConfiguration, true)
        .initialize();
  }
}
```

```
  @Job(name = "KValidator async handler", labels = {SOP, BUSINESS_VALIDATION_PROCESS, K_VALIDATOR_HANDLER})
  public void scheduleKValidationAsyncHandler() {
    BackgroundJob.scheduleRecurrently("*/1 * * * *", this::enqueueKValidatorCheck);
  }

  @Job(name = "Enqueue new check kValidator state", labels = {SOP, BUSINESS_VALIDATION_PROCESS, K_VALIDATOR_HANDLER})
  public void enqueueKValidatorCheck() {
    List<DelegatedState> delegatedTaskInState = processesService.getDelegatedTaskInState(SOP_BUSINESS_VALIDATION, 100);
    delegatedTaskInState.stream()
        .map(delegatedTask -> processesService.getStartedProcessById(delegatedTask.getStartedProcessId()))
        .forEach(startedProcess -> {
          UUID jobId = UUID.nameUUIDFromBytes((startedProcess.getFileId() + SOP_BUSINESS_VALIDATION).getBytes());
          BackgroundJob.enqueue(jobId, () -> checkKValidationStatus(startedProcess, JobContext.Null));
        });
  }
```

**Comment by auloin** [comment]
Hi @suchy30, could you please update your GitHub profile (like requested when you create an issue)

**Comment by rdehuyss** [comment]
Are you using a replica for postgres?

**Comment by suchy30** [comment]
Sorry, I wrote it wrong, the spring boot application is running in k8s with one replica. Postgres is running standalone outside of k8s.

**Comment by rdehuyss** [comment]
The only time I've seen this is, if you are using a database that is replicated (e.g. master/slave) like mongodb. Postgres also supports replication. The problem is that JobRunr is faster than the replication and you receive the same job again (still in `SCHEDULED` state whereas it was just `ENQUEUED` before) when reading from the slave as the writes did not propagate yet from the master to the slave..

**Comment by rdehuyss** [comment]
Can you setup a repo that reproduces this?

**Comment by rdehuyss** [comment]
Pinging @suchy30 - can you setup a repo that reproduces the issue?

**Comment by rdehuyss** [comment]
Closing due to no response. Feel free to reopen is you can setup a repo that reproduces this.
