### ISSUE TITLE
[BUG] 7.2.1 is not published on maven

### ISSUE THREAD

**Issue by jose96043** [jobrunr/jobrunr#1060]
### JobRunr Version

7.2.1

### JDK Version

-

### Your SQL / NoSQL database

-

### What happened?

Version 7.2.1 was released yesterday but its not published on maven

### How to reproduce?

Check maven repository

**Comment by rdehuyss** [comment]
Thanks for reporting. 

Maven central did some changes preventing us to to publish. Luckily, they were really helpful and things are solved. 

It is publishing as we speak so I expect it to be available in the next couple of hours.
