### ISSUE TITLE
[Feature] Quarkus extension - support the existing scheduler API

### ISSUE THREAD

**Issue by mkouba** [jobrunr/jobrunr#1069]
It seems that the `jobrunr-quarkus-extension` only supports the jobrunr annotations/API. It might make sense to support the [Quarkus scheduler API](https://github.com/quarkusio/quarkus/tree/main/extensions/scheduler/api/src/main/java/io/quarkus/scheduler) as well so that users can easily switch the underlying implementations but keep the existing code.

**Describe the solution you'd like**
We do something similar in the `quarkus-quartz` extension, i.e. we map the metadata found (e.g. `@Scheduled(every = "5s")`) to the Quartz API [like this](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java#L699-L818).

**Comment by melloware** [comment]
Adding a Quarkus DevUI card as well would be great that could have the JonRunnr UI in it similar to how I do Mailpit Extension.

https://github.com/quarkiverse/quarkus-mailpit/raw/main/docs/modules/ROOT/assets/images/mailpit-ui.png

**Comment by rdehuyss** [comment]
I'm afraid we don't do this as it will complicated or docs as it then doesn't align with other frameworks. 

If you open a PR for this (including the website), we're of course happy to review it.

**Comment by mkouba** [comment]
> I'm afraid we don't do this as it will complicated our docs 

Well, my proposal was to support the "shared" API which is [documented here](https://quarkus.io/guides/scheduler-reference) and supported by the `quarkus-scheduler` and `quarkus-quartz` extensions. I.e. no need to add anything in the jobrunr docs.

> as it then doesn't align with other frameworks.

No need to align with other frameworks. This would be implemented in the jobrunr Quarkus extension.

> If you open a PR for this (including the website), we're of course happy to review it.

Unfortunately, I don't have spare cycles to explore the jobrunr API but I can help with the Quarkus extension, i.e. describe how it's implemented in `quarkus-quartz`.
