### ISSUE TITLE
[BUG] Can't override RetryFilter or create my own one

### ISSUE THREAD

**Issue by ilopmar** [jobrunr/jobrunr#1081]
### JobRunr Version

7.2.2 (I can't pull 7.2.3)

### JDK Version

openjdk version "21.0.3" 2024-04-16 LTS

### Your SQL / NoSQL database

Postgresql

### What happened?

In a regular Spring Boot application with the JobRunr Starter I want to have a custom `JobServerFilter` so I can run some logic when a job fails. I've created my own filter but it's never executed because it's always added at the end of the list of handlers.

I can't even change the `RetryFilter` as explained in its own Javadoc:

```java
JobRunr.configure()
    ...
    .withJobFilter(new RetryFilter(20, 4)) // this will result in 20 retries and the retries will happen after 4 seconds, 16 seconds, 64 seconds, ...
    ...
    .initialize();
```

Because this new Filter, as mentioned is added at the end:

![image](https://github.com/user-attachments/assets/c6094095-c8bd-4c81-862d-a05f21d8c1e8)

And as you can see, my job is executed with the default 10 retries instead with the 20 I wanted:

![image](https://github.com/user-attachments/assets/b68b13b0-2a48-4b67-813a-026538549016)

This also happens when creating my own filter:

```java
@Bean
  public JobScheduler jobScheduler(StorageProvider storageProvider, HandleJobErrorFilter handleJobErrorFilter) {
    return JobRunr.configure()
        .useStorageProvider(storageProvider)
        .withJobFilter(handleJobErrorFilter) // <-- My filter
        .initialize()
        .getJobScheduler();
  }
```

```java
package com.example.jobrunr_filter;

import org.jobrunr.jobs.Job;
import org.jobrunr.jobs.filters.JobServerFilter;
import org.springframework.stereotype.Component;

@Component
public class HandleJobErrorFilter implements JobServerFilter {

  public HandleJobErrorFilter() {
    System.out.println("==================== HandleJobErrorFilter.HandleJobErrorFilter ====================");
  }

  @Override
  public void onProcessing(Job job) {
    System.out.println("==================== HandleJobErrorFilter.onProcessing ====================");
  }

  @Override
  public void onProcessingSucceeded(Job job) {
    System.out.println("==================== HandleJobErrorFilter.onProcessingSucceeded ====================");
  }

  @Override
  public void onFailedAfterRetries(Job job) {
    System.out.println("==================== HandleJobErrorFilter.onFailedAfterRetries ====================");
  }

  @Override
  public void onProcessingFailed(Job job, Exception e) {
    System.out.println("==================== HandleJobErrorFilter.onProcessingFailed ====================");
  }

}
```

It is added at the end but never call (I don't see the `println`s):

![image](https://github.com/user-attachments/assets/3ff41187-c766-466f-ad8b-8c5ca2fb32e5)

It seems that once a filter matches none of the following filters are executed. This kind of makes sense but it also makes impossible to define additional behaviour like implementing only one of the four methods in the previous class (which is what I wanted to to).  
Also it seems that the example in the RetryFilter javadoc is not 100% accurate because we can't override the default filters.

### How to reproduce?

You can find a reproducer in https://github.com/ilopmar/jobrunr-filter-issue

**Comment by rdehuyss** [comment]
Hi @ilopmar , I've just reviewed your reproducer but I'm afraid your setup is wrong.

This is extensively tested (using automated tests) and we're 100% sure this works.

**Comment by ilopmar** [comment]
Could you please let me know what's wrong with my reproducer or how to configure my own filter properly? :pray:
