### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by spokenbird** [jobrunr/jobrunr#1086]
### JobRunr Version

7.2.3

### JDK Version

Corretto 17.0/2

### Your SQL / NoSQL database

14.12

### What happened?

JobContext is null / does not seem to get injected when passing JobContext.Null for a job.

With the following code:

```java
public void enqueueUploadedDocumentTransmissionJob(String objectKey, Submission submission, UserFile userFile, String fileName) {
        String presignedUrl = s3PresignService.generatePresignedUrl(objectKey);
        JobId jobId = jobScheduler.enqueue(() -> sendUploadedDocumentTransferRequest(submission, userFile, fileName, JobContext.Null));
    }
    
    @Job(name = "Send Document Transfer Request for Uploaded Document", retries = 3)
    public void sendUploadedDocumentTransferRequest(Submission submission, UserFile userFile, String fileName, JobContext jobContext) {
        log.info("Job State is: " + jobContext.getJobState());
        log.info("Job Metadata is: " + jobContext.getMetadata());
        log.info("Enqueued uploaded document transfer job with ID: {} for file with ID: {} in submission with ID: {}", jobContext.getJobId(), userFile.getFileId(), submission.getId());
    }
    ```
    
I get the following error:
    
16:52:49.464 [https-jsse-nio-8080-exec-10] ERROR f.library.config.ActionManager - Unable to run Action 'SendUploadedFileToDocumentTransferService', java.lang.NullPointerException: Cannot invoke "org.jobrunr.jobs.Job.getState()" because "this.job" is null

### How to reproduce?

Call a job annotated with @Job  that has JobContext using JobScheduler like so:

```java
public void enqueueUploadedDocumentTransmissionJob(String objectKey, Submission submission, UserFile userFile, String fileName) {
        String presignedUrl = s3PresignService.generatePresignedUrl(objectKey);
        JobId jobId = jobScheduler.enqueue(() -> sendUploadedDocumentTransferRequest(submission, userFile, fileName, JobContext.Null));
    }
    
    @Job(name = "Send Document Transfer Request for Uploaded Document", retries = 3)
    public void sendUploadedDocumentTransferRequest(Submission submission, UserFile userFile, String fileName, JobContext jobContext) {
        log.info("Job State is: " + jobContext.getJobState());
        log.info("Job Metadata is: " + jobContext.getMetadata());
        log.info("Enqueued uploaded document transfer job with ID: {} for file with ID: {} in submission with ID: {}", jobContext.getJobId(), userFile.getFileId(), submission.getId());
    }

### Relevant log output

```shell
16:52:49.464 [https-jsse-nio-8080-exec-10] ERROR f.library.config.ActionManager - Unable to run Action 'SendUploadedFileToDocumentTransferService', java.lang.NullPointerException: Cannot invoke "org.jobrunr.jobs.Job.getState()" because "this.job" is null
```

**Comment by rdehuyss** [comment]
Can you create a reproducing example in a public GitHub repo? This will save us quite some time.

There are quite some integration tests for this feature so I really don't understand why you're getting this.

**Comment by rdehuyss** [comment]
Your error message is coming from somewhere else: `f.library.config.ActionManager`.

In the code you posted, there is no mention of a variable `job` , only `jobContext` and the error message explicitly mentions `job` inside the `f.library.config.ActionManager`.

The code above will work without problems but there is some other problem inside your code ( where you reference the `job` field or variable)

Closing for now but feel free to reopen if you have a GitHub repo reproducing the issue.
