### ISSUE TITLE
Dashboard not appearing[BUG]

### ISSUE THREAD

**Issue by excitement-engineer** [jobrunr/jobrunr#109]
I am currently running the snapshot build to test out the kotlin support. However, I can't get the dashboard to appear:

I have made a super simple main that reproduces this:

```kotlin
fun main() {

    val source = PGPoolingDataSource();
    source.setDataSourceName("A Data Source");
    source.setServerName("localhost");
    source.setDatabaseName("test");
    source.setUser("postgres");
    source.setPassword("tester");
    source.setMaxConnections(10);

    val scheduler = JobRunr.configure()
            .useStorageProvider(PostgresStorageProvider(source))
            .useDashboard()
            .initialize()

    scheduler.useKotlin()
}
```

As soon as I run this main the log states that the JobRunr dashboard has started at http://localhost:8000. However, when I go there it gives a 404.

**Comment by rdehuyss** [comment]
Hhhmmm, I don't publish snapshot builds so I don't know where you get it from.

If you want to try out Kotlin support, please use the 2.0 branch. Can you please test with that branch and report back?

**Comment by excitement-engineer** [comment]
Hey! Thanks for your response. Sorry, I should have been more clear, I got the snapshot build from the 2.0 branch. I built it using the instructions you mentioned [here](https://github.com/jobrunr/jobrunr/issues/77#issuecomment-776748201). 

I tried to find out the cause that the dashboard is not showing but I could not find it. Strange given that the logs mentioned that the server has started. I also tried changing the port but this did not work either. 

Do you have any idea what the reason could be that it does not work? Did I perhaps make a mistake in the configuration?

**Comment by rdehuyss** [comment]
Well, a 404 means the webserver is listening.

Can you try http://localhost:8000/dashboard?  This looks like the following issue: https://github.com/jobrunr/jobrunr/issues/69.

Which browser are you using?

**Comment by rdehuyss** [comment]
I just tried to reproduce the issue but am unable to do so:

build.gradle.kts
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.32"
}

group = "me.ronald"
version = "1.0-SNAPSHOT"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.jobrunr:jobrunr-kotlin-support:1.0.0-SNAPSHOT")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("org.slf4j:slf4j-simple:1.7.30")
    implementation("com.h2database:h2:1.4.200")
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}
```

app.kt
```
import org.h2.jdbcx.JdbcDataSource
import org.jobrunr.configuration.JobRunr
import org.jobrunr.scheduling.JobSchedulerExtensions.useKotlin
import org.jobrunr.storage.sql.h2.H2StorageProvider

fun main(args: Array<String>) {

    val source = JdbcDataSource();
    source.setURL("jdbc:h2:/tmp/test");
    source.setUser("sa");
    source.setPassword("sa");

    val scheduler = JobRunr.configure()
        .useStorageProvider(H2StorageProvider(source))
        .useDashboard()
        .initialize()
        .useKotlin()
}
```

Console output:
```
[main] INFO org.jobrunr.dashboard.JobRunrDashboardWebServer - JobRunr Dashboard started at http://localhost:8000
```

When I click the link from the console, the dashboard opens.

![image](https://user-images.githubusercontent.com/567842/114440043-f5d46000-9bc9-11eb-8808-872a14f52ac2.png)
