### ISSUE TITLE
[BUG] `JobActivator` is called multiple times for same job

### ISSUE THREAD

**Issue by chrisjenx** [jobrunr/jobrunr#1095]
### JobRunr Version

7.2.3

### JDK Version

Zulu 20

### Your SQL / NoSQL database

Postgres 14

### What happened?

Using a basic service locator (JobActivator) it will be called multiple times for the same job despite only one class need to be created:

i.e.:

```
2024-08-25 23:33:55.151 [backgroundjob-worker-pool-8-thread-21] TRACE JobRunrServiceLocator - Getting service: class co.haynet.jobs.JobSchedulerJobs
2024-08-25 23:33:55.152 [backgroundjob-worker-pool-8-thread-21] TRACE JobRunrServiceLocator - Getting service: class co.haynet.jobs.JobSchedulerJobs
2024-08-25 23:33:55.152 [DefaultDispatcher-worker-1] TRACE co.haynet.jobs.JobSchedulerJobs - TestRecurringJob: called
2024-08-25 23:34:10.154 [DefaultDispatcher-worker-1] TRACE co.haynet.jobs.JobSchedulerJobs - TestRecurringJob: finished
```

Not sure if this is intentional or not, but this could get very expensive if those services need to be created each time. 

```kotlin
val serviceLocator = JobRunrServiceLocator()

return JobRunr.configure()
  .useJobActivator(object : JobActivator {
    override fun <T : Any> activateJob(type: Class<T>): T = serviceLocator.get(type.kotlin)
  })
```

```kotlin
open class JobRunrServiceLocator {

    private val logging = LoggerFactory.getLogger("JobRunrServiceLocator")

    open fun <T : Any> get(klass: KClass<T>): T {
        logging.trace("Getting service: {}", klass)
        // by default use default constructor
        return klass.constructors.first().call()
    }

}
```

### How to reproduce?

```kotlin
val serviceLocator = JobRunrServiceLocator()

JobRunr.configure()
   // in memory db or postgres
  .useJobActivator(object : JobActivator {
    override fun <T : Any> activateJob(type: Class<T>): T = serviceLocator.get(type.kotlin)
  })
  .initialize()

fun startRecurringJob() {
   BackgroundJob.enqueueRecurring<TestJob>("test-queue", Duration.ofMinutes(1)) { it.callMe() };
}


// Test class
class TestJob {
 fun callMe() {
  // println("something")
 }
}


// Generic ServiceLocator
open class JobRunrServiceLocator {

    private val logging = LoggerFactory.getLogger("JobRunrServiceLocator")

    open fun <T : Any> get(klass: KClass<T>): T {
        logging.trace("Getting service: {}", klass) // will get called twice per job
        // by default use default constructor
        return klass.constructors.first().call()
    }

}
```

### Relevant log output

```shell
2024-08-25 23:39:55.329 [backgroundjob-worker-pool-8-thread-27] TRACE JobRunrServiceLocator - Getting service: class co.haynet.jobs.JobSchedulerJobs
2024-08-25 23:39:55.330 [backgroundjob-worker-pool-8-thread-27] TRACE JobRunrServiceLocator - Getting service: class co.haynet.jobs.JobSchedulerJobs
2024-08-25 23:39:55.331 [DefaultDispatcher-worker-7] TRACE co.haynet.jobs.JobSchedulerJobs - TestRecurringJob: called
2024-08-25 23:40:10.337 [DefaultDispatcher-worker-7] TRACE co.haynet.jobs.JobSchedulerJobs - TestRecurringJob: finished
```

**Comment by rdehuyss** [comment]
Hi @chrisjenx: I don't think this is a bug 😊. Things work and it would be an improvement if this would be changed. I would prefer if you would open a discussion for these kind of things.

This is by design: most IoC containers we support (Spring Boot, Quarkus, ... ) create singletons and this is merely a lookup (in a Map for Spring). We first check in the `BackgroundJobWithIocRunner` if it has a bean with the given class that is available (first time it is fetched) and then the actual bean is retrieved to perform it's job.

I hope this clarifies things.

**Comment by chrisjenx** [comment]
Fetching each time the job runs makes sense, but fetching multiple times for the same Job run does not. Might not be a bug but based on my concern, for sure unexpected behavior. 

_Why does it call it multiple times for the same job?_


IMO I wouldn't assume these are fetching singletons. (general rule of thumb is only need single instances if your class contains state), which TBH most backends shouldn't as your DB is the holder of state not Repo/API/Service layers. (Maybe most backend engineers are wasteful?)

Guice etc supports `Resusable` components but thats not common practice, I would be surprised how many people have that setup correctly.
