### ISSUE TITLE
[BUG] quarkus.jobrunr.background-job-server.delete-succeeded-jobs-after being treated as seconds instead of hours

### ISSUE THREAD

**Issue by prabhjotlalli** [jobrunr/jobrunr#1113]
### JobRunr Version

7.2.3

### JDK Version

openjdk version "21" 2023-09-19

### Your SQL / NoSQL database

Unsure

### What happened?

Jobs are being deleted from succeeded too quickly.

### How to reproduce?

Pull and run https://github.com/jobrunr/example-quarkus

Add `quarkus.jobrunr.background-job-server.delete-succeeded-jobs-after=10` to `application.properties`

According to https://www.jobrunr.io/en/documentation/configuration/quarkus/ the jobs should be deleted from succeeded in 10 hours. (docs say quarkus.jobrunr.background-job-server.delete-succeeded-jobs-after=36 #succeeded jobs will go to the deleted state after 36 hours). However, the job will move to deleted a few seconds after 10 seconds have passed.

**Comment by auloin** [comment]
This is a documentation issue. The conversion of the property is up to Quarkus and it defaults to seconds.
