### ISSUE TITLE
[BUG] Job Queue blocked after several days, requiring service restart

### ISSUE THREAD

**Issue by kebademe** [jobrunr/jobrunr#1115]
### JobRunr Version

6.3.5

### JDK Version

open jdk 1.8.0_232

### Your SQL / NoSQL database

Postgres 11

### What happened?

I am using a Job Queue system in my application to process background tasks. After a few days of normal operation, the jobs remain enqueued but are not being executed. When I check the dashboard, I can see several jobs in the queue, but in the **Server** section, no servers are processing them.

**Observed Behavior:**
1. After several days: All jobs stay stuck in the queue. None of the jobs are executed despite being present in the queue.
2. Dashboard: The "Enqueued" section shows jobs, but the "Server" section is empty (zero servers processing jobs).
3. Service restart: If I manually restart the service, the jobs are processed correctly for a while, but the issue reoccurs after a few days.

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.handle("ext1234","ref90128"));
  throw new PendingException("Processing transaction");
```

**Comment by rdehuyss** [comment]
I'm afraid you're not following our community guidelines (the text when you open an issue).

Please update your GitHub profile if you want any support.
