### ISSUE TITLE
[Feature] How to set the validity period for a task?

### ISSUE THREAD

**Issue by Caelebs** [jobrunr/jobrunr#1128]
**Is your feature request related to a problem? Please describe.**

I want to set the validity period for a recurring task when creating it. For example, for a certain task, I want it to be executed within the time range from 1727712000000 to 1729785600000, but I haven't found an API that allows setting such a property.

**Describe the solution you'd like**

**Describe alternatives you've considered**

I can create a recurring task and then, when the task is executed, check if the current time is within the validity period. If it's outside the validity period, I can then delete the corresponding task. However, I don't think this approach is very good. So I want to know if JobRunr has such parameter configuration to support setting the validity period range of tasks?

**Additional context**

```
		String s1 = jobScheduler.scheduleRecurrently(Cron.weekly(), () -> System.out.println("Easy!"));
		System.out.println(s1);

		String s2 = jobScheduler.createRecurrently(aRecurringJob()
			.withId("test-s2")
			.withCron("0 */12 * * *")
			.withDetails(() -> System.out.println("I'm created by the builder!")));
		System.out.println(s2);

		String s3 = jobScheduler.scheduleRecurrently("11111", cron, service -> System.out.println("s3"));
		System.out.println(s3);

		String s4 = jobScheduler.createRecurrently(aRecurringJob()
			.withId("test-s4")
			.withCron(cron)
			.withDetails(() -> System.out.println("s4")));
		System.out.println(s4);

		String s5 = jobScheduler.createRecurrently(aRecurringJob()
			.withId("test-s5")
			.withName("s5")
			.withCron(cron)
			.withDetails(() -> System.out.println("s5")));
```

There is the code I used to create the task.

**Comment by rdehuyss** [comment]
Hi @Caelebs - can you update your github profile? Please also see our [community guidelines](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D).

**Comment by Caelebs** [comment]
I apologize for any inconvenience caused by my carelessness. The question I asked didn't adhere to the community guidelines, so I'll close it now.

**Comment by rdehuyss** [comment]
No problem at all - I just realized that this isn't shown when creating a feature request. 

Regarding your question:
- in JobRunr Pro you have the possibility to implement a custom schedule (so you can combine a CRON schedule and a validity period).
- you can also try JobFilters and delete the job before it is created?
- ...

As always in IT - there are many different ways to solve this...
