### ISSUE TITLE
[BUG] Daily Recurring Jobs Keep Getting Re-enqueued During DST Shift

### ISSUE THREAD

**Issue by alexgutjahr** [jobrunr/jobrunr#1145]
### JobRunr Version

7.3.1

### JDK Version

OpenJDK 21.0.5+11

### Your SQL / NoSQL database

PostgreSQL 16.3

### What happened?

Hey Ronald, it is really hard to pin down the actual problem, but I will try my best:

I have four recurring jobs successfully executed for the past few weeks.
They are scheduled for 02:05a, 02:10a, 02:15a, and 02:20a with timezone Europe/Berlin:

![CleanShot 2024-10-27 at 06 57 37@2x](https://github.com/user-attachments/assets/a1e20260-c052-4a98-b255-d0142dca124d)

On 26.10.2024, all jobs were executed correctly, starting at 02:05a Europe/Berlin (00:05a UTC).
On 27.10.2024, the jobs started again at the correct time and finished successfully (no exceptions, etc.)

But they kept getting re-enqueued between 01:00a and 01:15a (UTC), leading to log messages likes this
`Recurring job 'Foo' is already scheduled, enqueued or processing. Run will be skipped as job is taking longer than given CronExpression or Interval.`

The most logical explanation I can come up with is the DST change, since nothing else has changed. Sorry that I cannot provide more details,but happy to provide anything that may prove helpful. Cheers!; nothing else has changed. I'm sorry that I cannot provide more details,but I'm happy to share anything helpful.

Edit: I would also have expected all jobs to run twice on 27.10.2024, what puzzles me is that they executed way more often than that.

### How to reproduce?

n/a

### Relevant log output

```shell
n/a
```

**Comment by rdehuyss** [comment]
Can you reproduce this with a simple sample and changing your clock back to right before the DST change?

**Comment by alexgutjahr** [comment]
Sure!

**Comment by alexgutjahr** [comment]
@rdehuyss provided a minimal sample here https://github.com/alexgutjahr/jobrunr-dst.
I've deployed it on a VM with the [launch script](https://github.com/alexgutjahr/jobrunr-dst/blob/main/launch.sh). 

The job gets executed 3 times (with the cron expression `0 5 2 * * *` for `Europe/Berlin`:
![CleanShot 2024-10-27 at 09 44 43@2x](https://github.com/user-attachments/assets/54eef9fc-3c6f-4dac-a280-f3ef108043cf)

Let me know if I should provide further details, thanks!

**Comment by rdehuyss** [comment]
Thanks for the reproducer. I'm taking 2 weeks off but will look into it end of November, beginning December.

**Comment by alexgutjahr** [comment]
No rush, enjoy your time off!

**Comment by proshin-roman** [comment]
@rdehuyss it seems the issue was fixed a long time ago, but to be sure - could you please provide the version where the fix was released? It seems I saw it happening again a few days ago (on the night between Oct.25 and Oct.26) on version 7.5.3.

UPD: it seems the bug was fixed in the 7.3.2 release - according to this diff: https://github.com/jobrunr/jobrunr/compare/v7.3.1...v7.3.2

**Comment by auloin** [comment]
Hi @proshin-roman, do you have a reproducer?

**Comment by proshin-roman** [comment]
@auloin not yet, and I'm still not sure the issue was caused by this bug. Once (and if) I have any more info, I'll post an update here.
