### ISSUE TITLE
[Feature] Allow non-integer seeds for retries

### ISSUE THREAD

**Issue by prabhjotlalli** [jobrunr/jobrunr#1147]
**Is your feature request related to a problem? Please describe.**
I'd like to use 1.5 as a seed.

**Describe the solution you'd like**
Allow double to be passed in here: https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/filters/RetryFilter.java#L58 (`Math.pow` already supports it)

**Describe alternatives you've considered**
I'll suggest to the developer to use 2 and have a longer retry than they'd like.

**Additional context**

**Comment by rdehuyss** [comment]
Hi @prabhjotlalli - quick question, does your company have a JobRunr Pro subscription?

**Comment by rdehuyss** [comment]
Then you can use the `CustomRetryPolicy` which offers a lot more flexibility. It can also be configured in Spring and Quarkus.

**Comment by rdehuyss** [comment]
See https://www.jobrunr.io/en/documentation/background-methods/dealing-with-exceptions/#a-custom-retrypolicy-for-all-your-jobs.
