### ISSUE TITLE
[BUG] JobRunr does not support SAP HANA Database

### ISSUE THREAD

**Issue by alanfok** [jobrunr/jobrunr#117]
**Describe the bug**
I'm working on the project and it works well in my local machine. And when I deploy to SAP cloud foundry, It fails to instantiate.

Here is the log.

 :"ERROR","categories":[],"msg":"Application run failed","stacktrace":["org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'coreApplication': Unsatisfied dependency expressed through field 'jobScheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in class path resource [org/jobrunr/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/autoconfigure/storage/JobRunrSqlStorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'sqlStorageProvider' threw exception; nested exception is org.jobrunr.JobRunrException: Are you running an unsupported DataSource or Database? Please check the documentation. If you think this is wrong, please open an issue using the following url: https://github.com/jobrunr/jobrunr/issues/new?template=bug_repo

**Environment**
I'm using version 
		<dependency> 
		    <groupId>org.jobrunr</groupId> 
		    <artifactId>jobrunr-spring-boot-starter</artifactId> 
		    <version>1.1.0</version> 
		</dependency> 

I'm running on JRE / JDK <11> 

I'm using SAP HANA.

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```
 jobScheduler.scheduleRecurrently(()->{ syncService.syncMonthly();} , Cron.monthly());
```

**Expected behavior**
it should work as the same as my local Database

**Comment by rdehuyss** [comment]
SAP Hana is not mentioned as a supported database on Github nor the website. So, this is definitely not a bug.

Although JobRunr probably supports SAP Hana out of the box, you won't be able to use Spring Boot auto configuration.

Try to setup an `OracleStorageProvider` yourself and it may work (no guarantees).

**Comment by alanfok** [comment]
Thanks for let me know  :)
