### ISSUE TITLE
[Feature] Able to schedule multiple jobs that the next job is dependent one

### ISSUE THREAD

**Issue by minhlongdo** [jobrunr/jobrunr#1176]
**Is your feature request related to a problem? Please describe.**
I am trying to schedule my jobs the following way:
Job A -> Job B + Job C -> Job D

**Describe the solution you'd like**
Job A needs to finish before executing Job B and Job C in parallel only after Job B and Job C have successfully finished Job D can be executed.

**Describe alternatives you've considered**
N/A

**Additional context**
For complex workflow like calculations that depends on multiple steps, this feature would be very helpful. This would also help to break bigger jobs into multiple smaller jobs accelerating the job processing process?

**Comment by rdehuyss** [comment]
This is possible in JobRunr Pro ☺️.

**Comment by minhlongdo** [comment]
Do you mean https://www.jobrunr.io/en/documentation/pro/job-chaining/?

**Comment by rdehuyss** [comment]
Yes. Just wrap your Job B + Job C in another job (e.g. `Job A'`), they will go parallel and you can wait for `Job A'` before starting `Job D`.
