### ISSUE TITLE
[Feature]  Dashboard - Implement filter / sort mechanism on the "jobs" screen

### ISSUE THREAD

**Issue by nlescure-pictet** [jobrunr/jobrunr#119]
Hi,

It would be nice to be able to filter (simple text filter) to be able to narrow down onto specific jobs executions instead of using the browser control-f. If the filter could be kept while changing pages, it would be even better :)
Moreover, having the possibility to select asc or desc on the timestamp field would be nice (although less useful than the filter mechanism).
Side question: unless I'm wrong, it appears that the deleted page sort jobs on timestamp asc (contrary to all the other pages). Is it a "bug" (as I find desc sorting much more useful) ?

Thanks again for the great work.

Cheers.

**Comment by rdehuyss** [comment]
The filtering will be an upcoming feature of the Pro version - I hope you understand but I put a lot of my free time in this and hope to convince some people with extra features to buy the Pro version.

Regarding the deleted page: for me it made more sense to sort ASC there as you then see the jobs that will be deleted soon, first.

And thanks for the nice feedback!

**Comment by rdehuyss** [comment]
This is now available in JobRunr Pro!
