### ISSUE TITLE
[Feature] Enable Defining worker's specific jobs that it can execute

### ISSUE THREAD

**Issue by TalRefaeli** [jobrunr/jobrunr#125]
Hi guys,
I recently tried jobrunr and it's lovely. simple, easy to understand and to integrate. I also like the fact that you widely enable customizing it with intuitive interfaces.

One thing that I didn't find a solution for is having the ability to limit job instances of specific types,
e.g. let's say that I have a job that I want to limit up to 2 instances to run simultaneously while I don't want to limit the rest of the job types (By writing "job type" I mean a lamda/method in jobrunr terminology).

Currently there's an option to control the number of workers (threads) by defining worker_count property, But it would be great to have an option to define for each worker the job types it could run, maybe by applying extra filter when calling StorageProvider.getJobs().

Thanks in advance and keep doing what you do.

**Comment by rdehuyss** [comment]
Isn't it the mutex feature from the pro version you want?

**Comment by TalRefaeli** [comment]
It certainly helps but it doesn't entirely solves my problem in the aspect of resource usage and efficiency.

Let's say I have a lambda which I want to run maximum of 2 jobs simultaneously.
With the mutex feature I can enqueue half of the jobs with mutex1 and the other half with mutex2. That should guarantee that no more than 2 workers will run the jobs.
Nevertheless, in case the jobs belonging to mutex1 will be finished before the jobs of mutex2, only 1 worker will run the rest of the jobs while the other worker will not do any job.

**Comment by rdehuyss** [comment]
You are completely correct... I think you mean something like throttling / rate limiting? 

Just out of curiosity, if this feature would be added to the Pro version, would you consider buying a license?

**Comment by TalRefaeli** [comment]
Yes, that's what I mean.
And regarding the Pro version, we'd consider using it if it will contain such feature.
Thanks,
Tal

**Comment by MikeyBower93** [comment]
Just wanted to add a +1 to this, I have some needs where specific jobs I am running need to run with some rate limiting. Specifically only x can run at once for a given job, but this isn't exclusive to all jobs (other jobs might have different rate limiting needs, or non at all).

**Comment by yop828** [comment]
I am also interested on this feature request
Is there any plan to release it in a upcoming release of jobrunr pro ?

**Comment by rdehuyss** [comment]
@yop828 @MikeyBower93 - we need some input from you to make sure we get the requirements right. Do you want to:
- for a certain job signature, limit the amount of concurrent jobs (e.g. max 2 jobs with the same job signature can run simultaneously)
- for a certain job signature, limit the amount of jobs per time duration (e.g. max 2 jobs / sec or max 2 jobs / min)
- or something else?

**Comment by yop828** [comment]
option A (limit the amount of concurrent jobs with the same job signature can run simultaneously) is what I need :-)

**Comment by MikeyBower93** [comment]
> @yop828 @MikeyBower93 - we need some input from you to make sure we get the requirements right. Do you want to:
> 
> * for a certain job signature, limit the amount of concurrent jobs (e.g. max 2 jobs with the same job signature can run simultaneously)
> * for a certain job signature, limit the amount of jobs per time duration (e.g. max 2 jobs / sec or max 2 jobs / min)
> * or something else?

Hey @rdehuyss , sorry for the late response here. I've actually seem good use cases for both before. One use case for point 1 is doing something processor intensive, you want to limit the amount of jobs that run that code at once. One good use case for the second option is imagine your using this to rate limit hitting a third party API, you might have a limit of 100 requests a minute, by controlling max jobs within a time frame, this requirement would become trivial to achieve.

**Comment by rdehuyss** [comment]
Development for this feature has started.

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro v7.0.0-beta.0

**Comment by yop828** [comment]
there is an technical issue with beta 7.0.0 : it does not work anymore with java 8.

see stack trace below : part of code uses now factory method of java 9+

```
Caused by: java.lang.NoSuchMethodError: java.util.Set.of([Ljava/lang/Object;)Ljava/util/Set;
	at org.jobrunr.storage.sql.common.db.Sql.using(Sql.java:57)
	at org.jobrunr.storage.sql.common.MetadataTable.<init>(MetadataTable.java:22)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.metadataTable(DefaultSqlStorageProvider.java:586)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.saveMetadata(DefaultSqlStorageProvider.java:190)
	at org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration.lambda$initializeRateLimiters$2(JobRunrAutoConfiguration.java:359)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration.initializeRateLimiters(JobRunrAutoConfiguration.java:359)
	at org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration.backgroundJobServer(JobRunrAutoConfiguration.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 112 more
```

Is the change of java support an required change for this version ?

**Comment by rdehuyss** [comment]
Hmm, I'm reaching out to my contacts at gradle as this should not be possible... 

See https://github.com/jobrunr/jobrunr/blob/master/build.gradle#L45-L46

**Comment by rdehuyss** [comment]
Hi @yop828 - that was a really strange error. Happy you found it. Apparently the compiler was creating Java 8 compatible bytecode yet using methods of JDK 9 🤔.

After contact with the gradle people, we changed our build to make sure this does not happen again. I'll create a new beta as soon as the build completes.

Can I also ask you to make issues related to JobRunr Pro against the JobRunr Pro repo? Thx!
