### ISSUE TITLE
Set concurrent execution count

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#13]
Is it currently possible to set the maximum number of concurrent jobs a worker executes at a time? I would like to be able to limit the load on workers somehow.

**Comment by rdehuyss** [comment]
Yes, this is possible. You can do so as follows, by creating the BackgroundJobServer yourself:

```
  @Bean
  public JobScheduler initJobRunr(ApplicationContext applicationContext) {
    StorageProvider storageProvider = new MongoDBStorageProvider("localhost", 27017);
    BackgroundJobServer backgroundJobServer = new BackgroundJobServer(storageProvider, applicationContext::getBean, 15, 10);
    backgroundJobServer.start();
    return JobRunr.configure()
        .useStorageProvider(storageProvider)
        .useBackgroundJobServer(backgroundJobServer)
        .useDashboard()
        .initialize();
  }
```

Here, you set the maximum number of concurrent jobs to 10. I'll also see whether I can enhance the fluent api to make it easier to configure the number of workers. 

Is there a reason why you would want to limit the number of workers?

**Comment by cemremengu** [comment]
We are planning to execute queries and produce reports that can use a lot of memory. I would like `JobRunr` to not overwhelm the background job servers if they are already very busy (i.e. to handle backpressure)
