### ISSUE TITLE
[BUG] Cannot access job details which are inside lambda

### ISSUE THREAD

**Issue by matveevajl** [jobrunr/jobrunr#134]
Into org.jobrunr.jobs.lambdas.JobLambda I put my own lambda expression. So I got this exception:

`Caused by: java.lang.IllegalAccessException: class org.jobrunr.jobs.details.JobDetailsGeneratorUtils cannot access a member of class ru.oblepihasticker.jobs.JobsRunnerServiceTest$$Lambda$493/0x00000008402de840 with modifiers "public"
	at ru.oblepihasticker.jobs.JobsRunnerServiceTest.runJobTest(JobsRunnerServiceTest.java:20)`

**Environment**
I'm using version 2.0.1 of JobRunr.
I'm running on JRE / JDK 11 with maven 3.8.1.
I'm using the following StorageProvider - h2 (but an exception is the same on postgres, for example)

**To Reproduce**
I created a repo - https://github.com/matveevajl/jobrunr-issue
Java code is in https://github.com/matveevajl/jobrunr-issue/tree/main/app
To run test use command
`mvn test`
from app directory, than in target/surefire-reports you'll find test result with exception.
You can also use prepared docker environment and run commands from Makefile.

**Expected behavior**
Test must pass without exception

**Comment by rdehuyss** [comment]
Hi, thanks for the Github issue reproducing the bug... but,  I'm afraid this won't work...

I'll try to translate your code to english: "Hey JobRunr, you need to run this task recurrently - which task, I don't know yet but start doing it each 5 minutes".

Because you pass the JobLambda interface to JobRunr (which in itself is a java lambda again), it cannot know which Task you want to schedule recurrently. 

You could solve it like this: 

```java
package ru.oblepihasticker.jobs;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.UUID;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = {JobsRunnerServiceTestConfiguration.class})
public class JobsRunnerServiceTest {

    private JobsRunnerService jobsRunnerService = new JobsRunnerService();

    //must be public
    public static class SomeJob implements JobLambda {

        @Override
        public Boolean run() {
            System.out.println("Do some work");
            return Boolean.TRUE;
        }
    }

    @Test
    @DisplayName("If job returns true it must be stopped")
    public void runJobTest() {
        jobsRunnerService.runJob(UUID.randomUUID(), "0/5 * * * * *", new SomeJob());
    }
}

```

I'm also updating JobRunr to give a better error in such a case.
