### ISSUE TITLE
Default schema for JobRunr tables using Oracle datasource

### ISSUE THREAD

**Issue by TomDeBacker** [jobrunr/jobrunr#136]
**Is your feature request related to a problem? Please describe.**
As explained [here ](https://stackoverflow.com/questions/2353594/default-schema-in-oracle-connection-url/2353905#2353905
),there's no straight forward way to specify the schema the datasource should use. 

After looking through Jobrunr source, I conclude there's no schema prefix in any of the queries made by Jobrunr. I have a case where the tables are in a different schema then the one the datasource picks by default. How to handle this?

My tables are under user/schema A but the application uses B. 

**Describe the solution you'd like**
Can/should JobRunr include a default schema in all it's queries (enabled by config for Oracle only)?
Does this work for anyone else?

**Describe alternatives you've considered**
Tried various solutions such as setting the Hikaripool default schema.. this works locally but when deploying to Tomcat the same issue occurs (using Tomcat, application must ignore the property somehow).
Tried creating custom DatabaseCreator class to ignore the validation of the schemas, but other queries have the same issue. 

**Additional context**
Error occurs at validating schemas in DatabaseCreator or wherever a query is used

**Comment by rdehuyss** [comment]
Hi @TomDeBacker!

The pain that it is to support Oracle :disappointed:. 

I'm a bit busy the coming weeks (I'm getting married!) and I want to think a little bit about a decent solution.

If you think you can find a good solution for this problem, I'm open for PR's on this one.

Cheers,
R

**Comment by rdehuyss** [comment]
Hi @TomDeBacker , if I create a branch with schema support for Oracle, are you able to check it out, build it and test it?

My Oracle knowledge is limited but I have tested schema support against H2.

**Comment by tan9** [comment]
Spring Batch provides [`spring.batch.jdbc.table-prefix`](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.batch.jdbc.table-prefix) application property, and [allowing user to prepend schema into this property](https://docs.spring.io/spring-batch/docs/current/reference/html/job.html#repositoryTablePrefix) like:

```java
factory.setTablePrefix("SYSTEM.TEST_");
```

Same logic applies to Spring Cloud Task too as [`spring.cloud.task.tablePrefix`](https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#features-table-prefix) property, and they further leave a note for user:

> By using the `spring.cloud.task.tablePrefix`, a user **assumes the responsibility** to create the task tables that meet both the criteria for the task table schema but with modifications that are required for a user’s business needs.

Even Quartz has [`org.quartz.jobStore.tablePrefix`](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJobStoreTX.html) property too.

Maybe JobRunr can adopt the same apporach like others. @rdehuyss , WDYT?

**Comment by rdehuyss** [comment]
Hi @tan9 - this is also the approach I've used.

Could you test the branch containing this feature, @tan9? I prefer that someone else then me also confirms it works.

**Comment by tan9** [comment]
@rdehuyss We would like to test the branch, because of we have a requirement to name every table with specific prefix. Which is not covered in this issue and the solution provided:

```java
    private String getFQTableName(String tableName) {
        if (isNullOrEmpty(schemaName)) {
            return tableName;
        }
        return schemaName + "." + tableName;
    }
```

Should I open another issue describing the requirement to specify table name prefix (without any alternative schema or database)?

Anyway, for the current issue, we have business requirement to run different schema in one PostgreSQL testcontainer and  run multiple Database in one SQL Server testcontainer. And we don't have any Oracle database available. Do you think this two use cases using database other than Oracle enough to cover this feature?

**Comment by rdehuyss** [comment]
I'll close this issue in favor of #152 as it also allows to add a schema.

**Comment by TomDeBacker** [comment]
I can confirm this works. Hope this does not reopen the issue.
