### ISSUE TITLE
The id of a recurring job can only contain letters and numbers[BUG]

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#139]
**Describe the bug**
this is sample of recurring job while start the app we got an exception

Caused by: java.lang.IllegalArgumentException: The id of a recurring job can only contain letters and numbers.
	at org.jobrunr.jobs.RecurringJob.validateAndSetId(RecurringJob.java:66) ~[jobrunr-3.0.1.jar:na]

**Environment**
I'm using version 3.0.1
I'm running on JRE / JDK 15
I'm using the following StorageProvider sql server 
spring boot

**To Reproduce**
BackgroundJob.scheduleRecurrently(Cron.daily(), () -> System.out.println("Easy!"));
```

**Comment by engahmedtahaa** [comment]
we have put a static Id for the job as he read the class name with $ while we annotate the method with transactional

**Comment by rdehuyss** [comment]
Hi @engahmedtahaa ,

I see - that issue will be solved in v3.1.0 which is due later today.

Cheers,
R
