### ISSUE TITLE
Store jobs in MongoDB as Binary type

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#14]
For some jobs we have to supply a report template. These templates **might** be above 16MB document limit of mongodb. So is it possible to use the [Binary type](https://mongodb.github.io/mongo-java-driver/3.6/javadoc/org/bson/types/Binary.html) when storing the job [on this line](https://github.com/jobrunr/jobrunr/blob/466445048dd4c6a4a391d6a70bd33a907a0c6e22/core/src/main/java/org/jobrunr/storage/nosql/mongo/JobDocumentMapper.java#L75).

**Comment by rdehuyss** [comment]
Mmm, I wonder if there is no better way - can't you just pass a pointer to the report template?

Typically, you would put the template on some shared storage (NAS/SAN) and pass the path to the template when you enqueue a job.

See also https://www.jobrunr.io/documentation/best-practices/. 

Would this work for you?

**Comment by cemremengu** [comment]
Yes you are right actually its better to have it that way (I am trying to convert a legacy system so sometimes I dont have much choice :))
