### ISSUE TITLE
How can I stop Jobrunr from creating default tables. 

### ISSUE THREAD

**Issue by yogi38in-taulia** [jobrunr/jobrunr#147]
I want to manually create tables using the scripts provided. Currently my application is failing on startup with message :Caused by: java.sql.SQLSyntaxErrorException: Table 'jobrunr_migrations' already exists

**Comment by yogi38in-taulia** [comment]
do we have any properties to disable same.

**Comment by rdehuyss** [comment]
Have you checked the docs?

**Comment by yogi38in-taulia** [comment]
Yes I tried to find this in docs. Could you please point me to the correct doc if you have it handy.

**Comment by yogi38in-taulia** [comment]
ok got it. Thanks
