### ISSUE TITLE
Jobs stuck at processing state

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#15]
**Describe the bug**
If server exists during processing, job gets stuck in that state

**Environment**
I'm using version 0.9.7
I'm running on JRE / JDK  11

**To Reproduce**
Start long running job (in my case something that times out) and just stop the server during execution.

**Expected behavior**
Should requeue the job.

My case is like this:
1- I have an unreachable database IP so it times out after 30 seconds.
2- Before it times out (i.e. Hikari pool is starting),  stop the server.
3- Job is stuck at processing state

**Comment by rdehuyss** [comment]
Confirmed bug
