### ISSUE TITLE
[BUG] When I delete a job, the job keep runing

### ISSUE THREAD

**Issue by frarondi** [jobrunr/jobrunr#151]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
When I delete a job, the job is flagged as deleted but the job keep runing.

I observed that the following method of the Job class throws a ClassCastException because the getJobState() method returns a DeletedState and not a ProcessingState.
```java
public void updateProcessing() {
        ProcessingState jobState = getJobState();
        jobState.setUpdatedAt(Instant.now());
}
```

**Environment**
I'm using JobRunr version: 3.1.2
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): jdk-11.0.2
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): PostgreSQL 

**How to Reproduce**
A simple code fragment which shows how to reproduce the issue.
```java
BackgroundJob.delete(jobId);
```

**Expected behavior**
The job is flagged as deleted and the job stops.

**Comment by rdehuyss** [comment]
Thanks for this bug report. It will be solved in the next release.

**Comment by rdehuyss** [comment]
Hi @frarondi - I originally thought that this was a bug introduced to a recent small refactoring but I have explicit end to end tests to cover this case - see [BackgroundJobTest](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/scheduling/BackgroundJobTest.java#L347-L357).

What is the value of your pollIntervalInSeconds?

**Comment by frarondi** [comment]
Hi @rdehuyss - I just saw BackgroundJobTest. In my case the job is set as deleted but it keeps runing and it ends successfully.

If you are refer to the property "org.jobrunr.background-job-server.poll_interval", the value is the default one: 15.

**Comment by rdehuyss** [comment]
I see - do you catch any exceptions in your code (Exception or InterruptedException)?

Could you share the method that does not stop?

**Comment by frarondi** [comment]
Yes, I catch Throwable. Below the code:
```java
@Transactional
@Job(name = "Importing Postgis %s")
public void importingPostgis(final UUID jobId) {
	final String METHOD_NAME = "importingPostgis(jobId)";
	startLog(METHOD_NAME, jobId);
	try {
		final BatchNetworkImportExecutionRequest executionRequest = getExecutionRequest(jobId);

		final TranslatedDraftModel translatedDraftModel = executionRequest.getTranslatedDraftModel();

		Long realTimestamp = translatedDraftModel.getTimestamp();
		if (realTimestamp == null) {
			realTimestamp = System.currentTimeMillis();
		}

		final Draft draft = draftService.getDraft(translatedDraftModel.getDraftId());

		postGisImporter.run(
				draft,
				translatedDraftModel.getTranslations(),
				realTimestamp
				);

		if (executionRequest.getDiscardDraft()) {
			draftService.physicallyDeleteDraft(draft.getId());
		}

		endLog(METHOD_NAME);
	} catch (final Throwable t) {
		errorLog(METHOD_NAME, t);
	}
}
```

**Comment by rdehuyss** [comment]
Hi @frarondi , I'm afraid this is not a bug in JobRunr but related to your code.

Please see the updated documentation about [deleting jobs](https://www.jobrunr.io/en/documentation/background-methods/deleting-jobs/).

I would also advice to read the [best practices](https://www.jobrunr.io/en/documentation/background-methods/best-practices/) as you are catching the `Throwable` which I think is not a good idea.
