### ISSUE TITLE
[Feature] Supports table name prefix.

### ISSUE THREAD

**Issue by tan9** [jobrunr/jobrunr#152]
**Is your feature request related to a problem? Please describe.**
We will run JobRunr under a shared big database, and all of our table must be prefix with specific pattern. 

**Describe the solution you'd like**
Add `tablePrefix` property.

**Describe alternatives you've considered**
Fork JobRunr and hand craft all Sql subclasses. And it is obviously too rude.

**Additional context**
Spring Batch provides [`spring.batch.jdbc.table-prefix`](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.batch.jdbc.table-prefix) application property, and [allowing user to prepend schema into this property](https://docs.spring.io/spring-batch/docs/current/reference/html/job.html#repositoryTablePrefix) like:

```java
factory.setTablePrefix("SYSTEM.TEST_");
```

Same logic applies to Spring Cloud Task too as [`spring.cloud.task.tablePrefix`](https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#features-table-prefix) property, and they further leave a note for user:

> By using the `spring.cloud.task.tablePrefix`, a user **assumes the responsibility** to create the task tables that meet both the criteria for the task table schema but with modifications that are required for a user’s business needs.

Even Quartz has [`org.quartz.jobStore.tablePrefix`](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJobStoreTX.html) property too.

And maybe this feature can be achieve in the same fashion as #136.

**Comment by rdehuyss** [comment]
Hi @tan9 ,

I changed branch feature/schema-support-in-sqlstorageprovider to use the same convention as Spring and Quartz.

If you can build and test the branch locally, I'll merge this to master.

Cheers!

**Comment by tan9** [comment]
@rdehuyss Thank you, we will test this branch later this week :)

**Comment by rdehuyss** [comment]
Resolved in [release v3.2.0](https://github.com/jobrunr/jobrunr/releases/tag/v3.2.0).
