### ISSUE TITLE
[BUG] Error when an index name contains a dot

### ISSUE THREAD

**Issue by neildeng** [jobrunr/jobrunr#155]
**Describe the bug**
When I run test cases for Postgres and SQLServer,  will occur errors with incorrect syntax '.'.
Normally,  execute the SQL statement is fine after calling the method of updateStatementWithSchemaName, such as creating tables and views, but not work for creating indexes with an index name that contains a dot.
For example, the original statement, 
**CREATE INDEX jobrunr_state_idx ON jobrunr_jobs (state)**
will update to 
**CREATE INDEX SOME_SCHEMA.SOME_PREFIX_jobrunr_state_idx ON jobrunr_jobs (state)**

**Environment**
I'm using version: feature/schema-support-in-sqlstorageprovider
I'm running on: JDK 8
I'm using the following StorageProvider: SQLServer and Postgres

To Reproduce

Test cases here: https://github.com/neildeng/jobrunr/commit/7d96d54b10f2da82815f026a5c1ddee9fd31c075

**Expected behavior**
it works for Postgres and SQLServer.

**Comment by rdehuyss** [comment]
Thanks for the issue and the PR!

Resolved in branch feature/schema-support-in-sqlstorageprovider.

I will add extra tests for the other databases and then this branch is good to merge.
