### ISSUE TITLE
[BUG] kotlin 1.5 break unit tests

### ISSUE THREAD

**Issue by AngeloChecked** [jobrunr/jobrunr#159]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
updating kotlin version to 1.5.20 in gradle file the unit test `test schedule with polymorphism` fail 
https://github.com/jobrunr/jobrunr/blob/master/jobrunr-kotlin-support/build.gradle#L5
https://github.com/jobrunr/jobrunr/blob/master/jobrunr-kotlin-support/src/test/kotlin/org/jobrunr/scheduling/JobSchedulerTest.kt#L124

**Environment**
I'm using JobRunr version: 3.12
I'm running on JRE / JDK: JDK 1.8.0_281

**How to Reproduce**
upgrade the kotlin version and run kotlin tests

**Comment by rdehuyss** [comment]
I was waiting for this issue to arrive :-)...

A bugfix release will be provided soon...

**Comment by rdehuyss** [comment]
Resolved in [release v3.2.0](https://github.com/jobrunr/jobrunr/releases/tag/v3.2.0).
