### ISSUE TITLE
Change API?

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#16]
I think it will be better to rename:

`scheduleRecurringly` -> `scheduleRecurring`

`deleteRecurringly` -> `remove`

Hangfire names are also similar. Especially `deleteRecurringly` sounds like it will repeat deleting the job.

**Comment by rdehuyss** [comment]
I also felt that `scheduleRecurringly` didn't feel right but from the beginning. But it was the best I could come up with. See also https://www.wordhippo.com/what-is/another-word-for/recurringly.html . I also have my doubts for`scheduleRecurring` however.

What about `scheduleRepeatedly`? Or `scheduleInARecurringManner`?

**Comment by cemremengu** [comment]
If we don't need to use `schedule` inside the keyword I think we can just use  `recur` or `repeat`. `scheduleInARecurringManner` is a bit long in my opinion. I personally like short and concise apis.

**Comment by rdehuyss** [comment]
I talked to a native English speaker and he would keep the `scheduleRecurringly`.

You also say `schedule weekly`, `schedule daily`, ... . So for him, `scheduleRecurringly` made sense.

I agree though to rename `deleteRecurringly` to `remove`. The `remove` api would be overloaded and if it's a UUID, it would remove a job. If it is a String, it removes a recurring job.

What do you think?

**Comment by cemremengu** [comment]
Sounds good to me

**Comment by rdehuyss** [comment]
Solved by commit dc0cc97.

In the end, I decided to use `delete` instead of `remove` as Jobs also have a `DeletedState`.
