### ISSUE TITLE
[Feature] Ability to "store" jobs and a web API to easily enqueue jobs from a remote source

### ISSUE THREAD

**Issue by JoonasC** [jobrunr/jobrunr#160]
**Is your feature request related to a problem? Please describe.**
To my knowledge, currently JobRunr only supports enqueueing jobs locally from code or re-enqueueing jobs through the web interface. This adds a layer of boilerplate code everytime you want to enqueue a job from a remote source, by having to wrap jobrunr with your own web API that enqueues the job. If the feature decribed here is implemented, it could also allow easy integration with other tools, such as using a DAG to enqueue jobs with [Apache Airflow](https://airflow.apache.org/).

**Describe the solution you'd like**
Two features should be implemented:
- A feature to store jobs
- A creation of a new web API, which allows for enqueueing jobs, among other things.

The feature to store jobs could work like this:
```java
jobScheduler.store("Foo", () -> myService.doWork());
```

And the web API to enqueue jobs could work like this:
`POST https://somejobrunrinstance/api/v1/job/enqueue/Foo`

The API could be secured using [JSON web tokens (JWT)](https://jwt.io/), and the web interface could be refactored to use this new API, which would allow for HTTP BASIC authentication to be replaced with JWT based authentication, improving security.

**Describe alternatives you've considered**
Haven't considered alternatives.

**Additional context**
For most usages of JobRunr, the preferred way to go about things is to have your own API, which uses JobRunr in the background, as clients having direct web API access to all of the commands of JobRunr wouldn't be useful, and could even pose a security risk. However, there are also cases, where you need to enqueue a JobRunr job internally within a network, such as when a server running on the same LAN or VPN as a cluster of JobRunr servers needs to trigger a job. In these cases having a web API to directly enqueue jobs would be very useful.

I hope you'll consider this feature.

Also, thanks for your great work on JobRunr, as it is now my favorite tool for background job processing with Java/Kotlin.

**Comment by rdehuyss** [comment]
So, if I understand correctly, it;s the extra work to wrap the JobRunr calls so that it's available in a Restful manner?

What about job arguments? You also serialize them via Json and pass them to JobRunr I assume?

**Comment by JoonasC** [comment]
Originally I was thinking that you would just pass the job aguments into the store function, and then have static arguments. But you're right, it would also be useful to pass arguments with the enqueue request. I think via JSON would be fine.

**Comment by rdehuyss** [comment]
After the whole log4shell issue, I've decided not to do this. The risk is too high for vulnerabilities.

**Comment by JoonasC** [comment]
@rdehuyss I think you could still do this responsibly by not having this feature enabled by default as the vulnerable feature in log4j was enabled by default. And ultimately if some developer decides to expose this api publicly, it's their responsibility, not jobrunr's. I won't fight you if you don't want to do this though.
