### ISSUE TITLE
[Feature] Ability to intercept ClassNotFound/MethodNotFound exceptions

### ISSUE THREAD

**Issue by mendess** [jobrunr/jobrunr#197]
**Is your feature request related to a problem? Please describe.**
When the application changes, some recurring jobs become invalid.

**Describe the solution you'd like**
Some way to register a handler for jobs that are invalid so I can delete them

**Describe alternatives you've considered**
I've tried to keep track of jobs and manually select from the database to find invalid jobs, but it's not very elegant or scalable.

If this is a feature that the development team decides is worth adding I wouldn't mind writing the pull request myself.

EDIT:

JobRunr reports this on boot, it would be sufficient to have a way of gathering this list of jobs programmatically. 
![image](https://user-images.githubusercontent.com/19352680/129593938-7a705982-a656-42fe-bc85-8a50f2715801.png)

**Comment by rdehuyss** [comment]
Hi @mendess , 

to be honest, this is not so easy to implement - this is not only the case for Recurring Jobs but also for Scheduled Jobs.

I need to think about how to add it elegantly as currently, the `StorageProvider` only lists all the distinct job signatures and currently does not have an API to find/delete jobs based on Job Signature.

**Comment by rdehuyss** [comment]
This has been resolved in JobRunr Pro v4.0.0 as there the necessary API's were already available (thanks to the Job Filtering feature).
