### ISSUE TITLE
JobDetailsAsmGenerator - how to improve cyclomatic complexity?

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#2]
## Background
The JobDetailsAsmGenerator is one of the backbones of JobRunr, it parses the java bytecode of your project to find the exact lambda you are passing. 

## Current status
The JobDetailsAsmGenerator is using a MethodVisitor of ASM to visit all the methods in the class file until it finds `INVOKEVIRTUAL` call which typically is your lambda. The score of this class in SonarCloud isn't the greatest due to the cyclomatic complexity.

## Question
How can this class be improved so that the cyclomatic complexity descends?

**Comment by plosson** [comment]
The question I had when I saw how you were achieving this is if it is really worth it. I completely agree it's super cool to be able to pass a lambda like what you allow, but compared to just a reference to a class/method+args, it would make the code way simpler. But it's quite a nice piece of code you wrote :-)

**Comment by rdehuyss** [comment]
Resolved in release v0.9.6 with commit a2e369412f3befc6fa349d8953b49f9bb09cf334.
