### ISSUE TITLE
Job selection based on some criteria

### ISSUE THREAD

**Issue by AlexDenisov** [jobrunr/jobrunr#22]
Hi @rdehuyss,

Thanks a lot for your work on this tool!

I'm now in the evaluation phase on whether JobRunr would fit our needs or not.
There are a few different use-cases, but here I'll focus only on one.

Is there a way to run specific jobs on a particular worker? Some examples:

 - OS-specific workers (Linux/macOS/Windows): let's say there are several different jobs, some of the jobs are OS agnostic, while some of them should strictly run on a specific OS
 - serial execution workers: some jobs are reading/writing shared state (e.g., on-disk git repo), so I'd like to restrict access to this worker only to a specific type of jobs and also make sure that they are executed in the strict sequential order, one by one

I looked at the source code, and it seems that the only way to achieve this at the moment is to implement custom `WorkDistributionStrategy` and somehow inject it into the places where it is relevant.
I would appreciate it if you can share your thoughts on the subject and give some comments on whether such features are planned in the future, or it's entirely out of scope.

Thank you,
Alex.

P.S. I might be approaching the problem in a wrong way, so if you have better suggestions - please do not hesitate to share them :)

**Comment by rdehuyss** [comment]
Hi @AlexDenisov ,

I've had a night of sleep about it and some answers regarding your questions:

**OS-specific workers:**
have you looked at the JobFilters? You can use an ElectStateFilter and change the state from PROCESSING to SCHEDULED again. This makes that another backgroundjob worker can pick up the job.
  - *Advantages*: fine grained control on whether to execute the job.
  - *Disadvantage*: possible extra round-trips to the database until the correct worker picks up the job.
  - Fine grained control about worker selection will be part of JobRunr Pro.

**Serial execution workers:** 
Do you mean something like this?  
```java
BackgroundJob
                .enqueue(() -> System.out.println("Job number one"))
                .continueWith(() -> System.out.println("Job number two"));
```

This will be part of JobRunr Pro (release by the end of this July) and allows job chaining. Job number two will only be started once Job number one has finished successfully. 

FYI - I also send you an email with some questions.

**Comment by AlexDenisov** [comment]
Hi, thanks for the hints. I thought about using the filter for OS-specific calls, but that has a disadvantage I guess - it is technically possible that the job will always be picked up by the same worker and the job will never execute, right?

re: sequential execution:

I must admit I picked the wrong word for the description. While your example is also important in our use case it is still can be worked around by scheduling another job at the end of the first one. Also, based on your example it is not clear how to pass arguments from one job to another, e.g.: the first job computes something and needs to pass the result to the next one.

Anyhow, what I meant originally is something more of a lock/mutex/etc. I.e. doesn't matter how many jobs were enqueued only one is being executed at a time. Did I make it more clear? :)

**Comment by rdehuyss** [comment]
@AlexDenisov , I can happily say that all the requested features (both OS-specific workers and mutex support) will be part of JobRunr Pro.

Do not hesitate to reach out if you want to try out a pre-release with premium support off-course ;-).

**Comment by rdehuyss** [comment]
These features are now available in [JobRunr Pro](https://www.jobrunr.io/en/documentation/pro/)!
