### ISSUE TITLE
[Feature] add ability to disable recurring job

### ISSUE THREAD

**Issue by ryapparov** [jobrunr/jobrunr#227]
**Is your feature request related to a problem? Please describe.**
There is no way to temporarily disable a recurring job.
There are some ways to do it manually but would be great if it'll be a part of this library.

**Describe the solution you'd like**
Add ability to disable/enable recurring jobs in `Recurring jobs` tab in the dashboard.

**Describe alternatives you've considered**
There are some ways to disable the jobs manually:
- add flag in the job itself to skip execution if current job is not enabled
- delete the job and restart the application
- create endpoint to delete/create job based on its `id`

**Comment by rdehuyss** [comment]
Hi @ryapparov , this is already part of JobRunr Pro.

It's always a difficult choice to make - put a feature in the free version or the pro version - but I feel like if I keep adding extra features to the free version, there is no incentive to buy the Pro version. I hope you understand my situation.
