### ISSUE TITLE
[Feature] Define contextPath via property 

### ISSUE THREAD

**Issue by bjsee** [jobrunr/jobrunr#228]
It would be great if I could define the contextPath under which the dashboard and api endpoints are reachable. This would make it possible (or much easier) to make the dashboard available through reverse proxy.

**Comment by rdehuyss** [comment]
There was already a feature request like this. I'm open for a PR but my initial investigation told me this is not so trivial to implement.

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro v5.0.0
