### ISSUE TITLE
[Feature] Recurring Jobs with a fixed Interval

### ISSUE THREAD

**Issue by eifinger** [jobrunr/jobrunr#231]
**Is your feature request related to a problem? Please describe.**
Hi and thank you for this project!

I have the following use case:

1. A customer registers to a program where he needs to send data 3 times per X days
2. After X days I want to check if the customer has indeed sent data 3 times

So when the customer registers I want to schedule a job "check now in X days". It has to be the same time every X days (down to the minute)

**Describe the solution you'd like**
A great api would be:

```java
BackgroundJob.scheduleRecurringly("my-recurring-job", Duration.parse("PT5D"), () -> service.doWork());
```

**Describe alternatives you've considered**
I have considered to compute a cron schedule depending on `now`.
But this leads to problems at the end of a month as described [here](https://stackoverflow.com/a/55087822)
The same is the case for a delays of hours and the end of a day.

**Additional context**
-

**Comment by rdehuyss** [comment]
Solved in v5.0.0 branch.
