### ISSUE TITLE
[BUG] Could not resolve ConcurrentJobModificationException

### ISSUE THREAD

**Issue by jeevangali-agi** [jobrunr/jobrunr#232]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
we use Jobrunr to execute lot of scheduled Tasks. Jobrunr is getting stopped, with the below exception logging.
![image](https://user-images.githubusercontent.com/73397163/136679281-b3b42ce9-2c2a-4264-acc4-ed88f4d768d9.png)

**Environment**
I'm using JobRunr version: 4.0.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): java-1.8.0-amazon-corretto 1.8.0_275-b01

I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Redis 

**How to Reproduce**
tobe frank we may not be able to simulate this.

**Expected behavior**
jonrunr should execute jobs, with out stopping
**Additional context**
* we Generate JobID as our own String

**Comment by jeevangali-agi** [comment]
I dont think this is invalid. I agree that this can be PRO feature, but, it shoudl be handled from JobRunr. either it shoudl not be able able to modify or wait until the job gets into waiting status

**Comment by rdehuyss** [comment]
@jeevangali-agi You can have a look at the ConcurrentJobModificationPolicy. It allows to decide what to do when a ConcurrentJobModification happens.

This is part of JobRunr 4.0.3.
