### ISSUE TITLE
[BUG] Cannot open details of Succeeded jobs

### ISSUE THREAD

**Issue by michalgce** [jobrunr/jobrunr#24]
**Describe the bug**
When i go to JobRunr dashboard and click on one of succeded job then appears white page with following error in console.
```
react_devtools_backend.js:2273 TypeError: t.latencyDuration.toFixed is not a function
    at ra (succeeded-state.js:62)
    at Xr (react-dom.production.min.js:153)
    at ms (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Gn (react-dom.production.min.js:122)
    at jn (react-dom.production.min.js:123)
overrideMethod @ react_devtools_backend.js:2273
es @ 2.144d0f26.chunk.js:2
i.callback @ 2.144d0f26.chunk.js:2
ur @ 2.144d0f26.chunk.js:2
rs @ 2.144d0f26.chunk.js:2
hl @ 2.144d0f26.chunk.js:2
t.unstable_runWithPriority @ 2.144d0f26.chunk.js:2
Gn @ 2.144d0f26.chunk.js:2
pl @ 2.144d0f26.chunk.js:2
Js @ 2.144d0f26.chunk.js:2
(anonymous) @ 2.144d0f26.chunk.js:2
t.unstable_runWithPriority @ 2.144d0f26.chunk.js:2
Gn @ 2.144d0f26.chunk.js:2
jn @ 2.144d0f26.chunk.js:2
Vn @ 2.144d0f26.chunk.js:2
L @ 2.144d0f26.chunk.js:2
$t @ 2.144d0f26.chunk.js:2
react-dom.production.min.js:123 Uncaught TypeError: t.latencyDuration.toFixed is not a function
    at ra (succeeded-state.js:62)
    at Xr (react-dom.production.min.js:153)
    at ms (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Gn (react-dom.production.min.js:122)
    at jn (react-dom.production.min.js:123)
```
**Environment**
I'm using version 0.9.11 JobRunr
I'm running on JRE / JDK 1.8.0_232
Dashboard has been setup to listen on custom port **8069**
**To Reproduce**
Go to dashboard, click on Succeeded jobs and click one of entry (id or description)

**Expected behavior**
Details of selected job entry.

**Additional context**
I'm using Postgresql storage with configured my custom json mapper.

**Comment by rdehuyss** [comment]
Could you provide me with the http error you receive in your browser.

My guess is that the custom json mapper is returning an http error.

**Comment by michalgce** [comment]
Request URL: http://localhost:8069/api/jobs/b939d1cb-8493-44de-a42c-0ee58b25d5fd
Response body
`{"version":2,"jobSignature":"Gate.dispatch(ArchiveMeasurementsCommand)","jobName":"Gate.dispatch(de.sonnen.core.domain.measurement.ArchiveMeasurementsCommand@6f51abed)","jobDetails":{"className":"de.sonnen.cqrs.command.Gate","staticFieldName":null,"methodName":"dispatch","jobParameters":[{"className":"java.lang.Object","object":{"@class":"de.sonnen.core.domain.measurement.ArchiveMeasurementsCommand","transactionId":1,"transactionUUID":"b405d967-89ea-4ed7-b9b4-28eecfa0e53d","chargerId":"e5e7b74c-f3b0-4949-b9bc-2af21bad83c1","from":"2020-07-24T08:28:21Z","to":"2020-07-24T08:28:28Z"}}]},"id":"b939d1cb-8493-44de-a42c-0ee58b25d5fd","jobHistory":[{"@class":"org.jobrunr.jobs.states.EnqueuedState","state":"ENQUEUED","createdAt":"2020-07-24T08:28:29.303Z"},{"@class":"org.jobrunr.jobs.states.ProcessingState","state":"PROCESSING","createdAt":"2020-07-24T08:28:39.371Z","serverId":"c6f37f17-018e-46ba-9e5c-75380f7871f3","updatedAt":"2020-07-24T08:28:39.371Z"},{"@class":"org.jobrunr.jobs.states.SucceededState","state":"SUCCEEDED","createdAt":"2020-07-24T08:28:39.497Z","latencyDuration":"PT10.194S","processDuration":"PT0.126S"}],"metadata":{"@class":"java.util.concurrent.ConcurrentHashMap","jobRunrDashboardLog-2":{"@class":"org.jobrunr.jobs.context.JobDashboardLogger$JobDashboardLogLines","logLines":[]}}}`

I've created custom json mapper to serialize/deserialize value object which i used inside Command class (mostly it is copy-paste of `JacksonJsonMapper` but with extra SimpleModule which adds serializers and deserializers).

Example:
`java
jobScheduler.enqueue(() -> gate.dispatch(archiveLastDayEventsCommand));
`
and within Commands i'm using my own Value Objects
