### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by amul-2023** [jobrunr/jobrunr#244]
**Warning**
JobRunr detected some CPU Allocation Irregularities (e.g. due to a very long garbage collect cycle or due to CPU starvation on shared hosting). This may result in unstable behaviour of your JobRunr cluster. You are urged to look into this as soon as possible.
BackgroundJobServer 19250acc-8319-4680-9043-f04dea396ded had a CPU Allocation Irregularity of 3524 seconds 34 minutes ago
**Fatal**
JobRunr encountered an exception that should not happen. To resolve this issue, can you please create a Github issue? To make life easy, you can click here to copy all necessary information to your clipboard and paste it in the Github issue.
You can still cancel the creation of the issue in Github if you think it contains sensitive information..
getting like this in dash board
![Uploading 2021-10-26 (1).png…]()

**Comment by Qiuqiu0505** [comment]
@amul-2023  I have the same problem and how  do you solve it ?
