### ISSUE TITLE
[BUG]Duplicate paragraph on the FAQ page

### ISSUE THREAD

**Issue by davidlzs** [jobrunr/jobrunr#253]
There is a duplicated paragraph on the [FAQ](https://www.jobrunr.io/en/documentation/faq/) page. At the bottom of section of  "Service Bus", there is a paragraph not related to that topic, which should be removed.

"This is because you stopped a running JVM instance where a BackgroundJobServer was processing a job. When a job is being processed, it is regularly updated with a timestamp so that in case of a node failure, the job can be retried automatically on a different server. The error message you see here, is an example of such a case."

**Comment by rdehuyss** [comment]
Thx! Solved...
