### ISSUE TITLE
[Feature] gson 2.8.8+ support

### ISSUE THREAD

**Issue by JanHolger** [jobrunr/jobrunr#255]
**Is your feature request related to a problem? Please describe.**
JobRunr currently doesn't support the latest gson version.

**Describe the solution you'd like**
Make fixGsonNotBeingExtensible compatible with latest gson versions (if possible) until https://github.com/google/gson/issues/1177 gets somehow fixed by Google.

**Describe alternatives you've considered**
I'm currently explicitly specifying the older gson version for each shaded jar in my projects to prevent the newer version getting shaded.

**Comment by rdehuyss** [comment]
@JanHolger, please do not create duplicate issues: this was solved in #252 by commit #ea23c7b. A new release will be created soon.

**Comment by JanHolger** [comment]
@rdehuyss In #ea23c7b you fixed that it shows the incompatibility error instead of the NoSuchFieldException and downgraded the gson version. The latest gson version still isn't supported. That's why I created this issue as a feature request.

**Comment by rdehuyss** [comment]
Yeah, small mistake for the downgrade. It does fix the issue though.A new version is building as we speak.

**Comment by JanHolger** [comment]
That's great. Thank you really much for the fast fix!
