### ISSUE TITLE
Unable to change the numberOfRetries in the RetryFilter in Jobrunr-Spring-Boot-Starter

### ISSUE THREAD

**Issue by archbobo** [jobrunr/jobrunr#259]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
Unable to change the numberOfRetries in the RetryFilter in Jobrunr-Spring-Boot-Starter.

**Environment**
I'm using JobRunr version: 4.0.2
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk version "11.0.6"
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): ElasticSearch

**How to Reproduce**
I can get the BackendJobServer bean in Spring, but there is no public interface to get the JobFilters and change the RetryFilter already configured in it. There is a getJobFilters method, but its signature is not public.

**Expected behavior**
I can change the numberOfRetries in the already configured RetryFilter, or make it configurable via Spring application.yaml file.

**Additional context**
https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/BackgroundJobServer.java

**Comment by rdehuyss** [comment]
Happy to accept a PR for this

**Comment by rdehuyss** [comment]
Cleaning up as no PR is coming in for this. Removing the enhancement label so that it is eligible for cleanup by stalebot.

**Comment by starrybleu** [comment]
I think you may be able to do that by creating a bean in your code like below.

```java
    @Primary
    @Bean
    public JobScheduler jobScheduler() {
        return JobRunr.configure()
            .withJobFilter(new RetryFilter(20, 4)) // this will result in 20 retries and the retries will happen after 4 seconds, 16 seconds, 64 seconds, ...
            .useJobActivator(jobActivator())
            .useStorageProvider(SqlStorageProviderFactory
                .using(dataSource()))
            .useBackgroundJobServer()
            .useDashboard()
            .initialize();
    }
```

I referred to the https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/filters/RetryFilter.java
