### ISSUE TITLE
MongoDB Job ID

### ISSUE THREAD

**Issue by AlexDenisov** [jobrunr/jobrunr#26]
HI @rdehuyss,

Just curious whether using `UUID` (as opposed to a `String`) is intentional?
I.e. shouldn't this https://github.com/jobrunr/jobrunr/blob/c6b7f35c1a53b0bac9780e7fbc2ea1f7d07148d0/core/src/main/java/org/jobrunr/storage/nosql/mongo/JobDocumentMapper.java#L32 be `job.getId().toString()`.

While the current implementation is working fine, I've never seen a binary object used as an ID, and I'm wondering whether it may cause any issues with other queries such as `aggregate`.

**Comment by rdehuyss** [comment]
Hi Alex, I'm not an MongoDB expert but I don't encounter any problems with it. I used the following resources to make a decision:
- https://docs.mongodb.com/manual/core/document/#the-id-field
- https://stackoverflow.com/questions/28895067/using-uuids-instead-of-objectids-in-mongodb

In JobRunr Pro there are different aggregations working fine. Do you encounter problems with it?

**Comment by AlexDenisov** [comment]
> Do you encounter problems with it?

Not really, was just curious :)
Thanks for the links, I didn't know about the `BinData` in that case.
I guess the issue can be closed now :)
