### ISSUE TITLE
[Feature] Allow setting poll interval to less than 5 seconds

### ISSUE THREAD

**Issue by vpavic** [jobrunr/jobrunr#260]
**Is your feature request related to a problem? Please describe.**
At present, `BackgroundJobServerConfiguration` does not allow setting poll interval to less than 5 seconds:

https://github.com/jobrunr/jobrunr/blob/1a3edfb15901c49be9e7a6c38ef6dd04e97f5d07/core/src/main/java/org/jobrunr/server/BackgroundJobServerConfiguration.java#L35-L46

In systems that require high-precision triggering of jobs, this isn't enough to ensure their timely execution (think of real-time use cases like auctions endings where seconds matter).

**Describe the solution you'd like**
Decrease the minimal allowed `pollIntervalInSeconds` to 1 second. This could be coupled with documentation update that discourages setting it to less than 5 seconds, similar like Quartz Scheduler does: see [here](https://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html), look for `org.quartz.scheduler.idleWaitTime`.

Realistically, poll interval of 1 seconds means 60 queries per minute, which isn't really a big deal and even a mildly used system will see by far bigger load on its database that this will be able to produce.

**Describe alternatives you've considered**
Making it a responsibility of job consumer to ensure exact time of job execution, but that's quite a hacky workaround.

**Additional context**
n/a

**Comment by Ragin-LundF** [comment]
I had the same request: https://github.com/jobrunr/jobrunr/issues/256

**Comment by rdehuyss** [comment]
See #256

**Comment by navrocky** [comment]
For testing, you can trigger job polling with the such call:

```java
backgroundJobServer.getJobZooKeeper().run();
```
