### ISSUE TITLE
[Question] High CPU on RDS/PostgreSQL  

### ISSUE THREAD

**Issue by declanlawlor** [jobrunr/jobrunr#271]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
My service runs once a day and enqueues approximately 65,000 jobs. These jobs are simple and fast. Each job queries an ElasticSearch cluster, and then optionally send a message to a RabbitMQ cluster.

During the course of running the jobs, which takes approximately 30 minutes, the PostgreSQL cluster maxes out at 100% CPU. Once complete, the CPU returns to normal levels ~%10 CPU. From analysing the performance of the cluster, I see the following query exhibiting a high latency:-

`select jobAsJson from jobrunr-jobs where state.= $1 ORDER BY updatedAt ASC LIMIT.
`

Calls/sec - `1.11`
Rows/sec - `8.55`
Avg Latency (ms)/call - `289.77`

There is a second query has an avg latency of 120 ms.

`select * from jobrunr_jobs_stats ORDER BY total ASC LIMIT $1 OFFSET $2`

At the time, Write IOPS peak at  ~89/sec.

**Environment**
I'm using JobRunr version: 4.0.2
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk version "11.0.6"
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): PostgreSQL running on Amazon RDS (t4g.medium)

**How to Reproduce**
Enqueue a large number (greater than 60,000)  jobs at once. 

**Expected behavior**
Reduced query latency & cpu utilisation.

**Additional context**

**Comment by rdehuyss** [comment]
I'm definitely not a Postgres specialist but I don't think the query can be any simpler. There are also indices put on the fields that are used in the query.

How many Background Job servers are running?

**Comment by declanlawlor** [comment]
2 Background job servers with 16 workers per server. I reduced the number of workers to 8, but there was no improvement.

**Comment by rdehuyss** [comment]
Can you reproduce this locally?

**Comment by rdehuyss** [comment]
And to be honest, for me this is not a bug. There is so much what could cause this that is locally to your environment that I'm afraid that it's out of the scope for JobRunr. I'm happy to help if you can pinpoint the exact issue. 

The fact that your jobs don't have a lot of work just causes JobRunr to finish jobs quickly and ask for the next batch of jobs, which is the query you see.

**Comment by declanlawlor** [comment]
Agreed, this is not a bug with JobRunr. The value for `work_mem` on our RDS postgres is the default value of 4MB. This is low and I believe may be the cause of the slow sort/subselect operations, as postgres is resorting to disk to perform sort operations. We will investigate more and I will report back our findings. Thanks for your help.

**Comment by raqeebkhan1** [comment]
@declanlawlor we are also facing the same issue and in our case also `work_mem` is set to 4MB. Was your issue resolved by increasing `work_mem`?  I'd be grateful if you can update your findings here.

**Comment by rdehuyss** [comment]
What version of JobRunr are you on?

**Comment by raqeebkhan1** [comment]
5.13

**Comment by rdehuyss** [comment]
How much memory does your give to your DB?
