### ISSUE TITLE
[BUG] Unknown INVOKEDYNAMIC instruction: get

### ISSUE THREAD

**Issue by benallard** [jobrunr/jobrunr#278]
**Are you running the latest version of JobRunr?**
Yes (4.0.2)

**Describe the bug**
I've been trying to enqueue complicated lamdbas. wasn't really expecting it to work (would have been cool though), but wasn't expecting this kind of error either.

**Environment**
I'm using JobRunr version: 4.0.2
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): Adopt 8
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): h2

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
BackgroundJob.enqueue(() -> run(() -> fetch(5, 8), aFunctionalInterface);
```

**Expected behavior**
Not sure, but not a shouldNotHappenException.

**Additional context**
.

**Comment by benallard** [comment]
Tell me if you need more info.

**Comment by rdehuyss** [comment]
Don't run lambda's within lambda's. That is not supported.

See https://www.jobrunr.io/en/documentation/background-methods/best-practices/
