### ISSUE TITLE
Does jobrunr support azure cosmos db?[Feature]

### ISSUE THREAD

**Issue by pt-wm** [jobrunr/jobrunr#287]
**Is your feature request related to a problem? Please describe.**
Would like to know if nosql azure cosmos db is supported by jobrunr. If yes, can you please share how to add it as a storage provider? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rdehuyss** [comment]
No - if it is not mentioned in the docs, it isn't supported.

I also don't have any plans on adding it myself. Open for PR's though.
