### ISSUE TITLE
[BUG] Issue when upgrading a jobrunr application

### ISSUE THREAD

**Issue by andrerigon** [jobrunr/jobrunr#288]
We were using version 4.0.0. Then we upgraded to version 4.0.4. When accessing the dashboard, it still lists the old decommissioned pods in the servers listing, with old heartbeat timestamps. 
Jobs are listed but they never get scheduled and run. No error can be found in the logs.
Any help to troubleshoot would be appreciated. 
Do we need to run any procedure when migrating to a new version?

Thanks,

Andre

**Environment**
I'm using JobRunr version: 4.0.4
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): java-11-openjdk-headless
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): LettuceStorageProvider

**Expected behavior**
Jobs should continue to be scheduled and run in the new version.

**Additional context**
We use jobrunr's quarkus extension - _org.jobrunr:quarkus-jobrunr:4.0.4_

**Comment by rdehuyss** [comment]
No, that should be it. The only thing, I can think of is #254 but that was fixed already.

But, without you providing me a repo that reproduces this, I'm afraid I cannot give you support on this.

Feel free to reopen once a repo is available that reproduces it and even then, my time is so limited for the moment that I cannot continue giving free support for everybody. I hope you understand.

**Comment by andrerigon** [comment]
Thanks @rdehuyss. The issue was not with jobrunr directly, but with quarkus after an update: the job server was not running.
