### ISSUE TITLE
[Feature] Configuring RetryCount via `JobRunr.configure()`

### ISSUE THREAD

**Issue by AlexDenisov** [jobrunr/jobrunr#29]
**Is your feature request related to a problem? Please describe.**

We have some jobs that are failing for reasons that won't be solved after any number of retries (e.g. underlying logic crashes for whatever reason).

**Describe the solution you'd like**

Some way to stop mark the job failed after 1 or 2 retries.

**Describe alternatives you've considered**

Looked at the source code trying to find a way to change the retry count of `RetryFilter`, but that would require setting up the whole machinery manually, i.e. without using `JobRunr.configure()`.

**Comment by rdehuyss** [comment]
Hi @AlexDenisov ,

I think this is already possible: have you tried the following?

```java
JobRunr.configure()
    .withJobFilters(new RetryFilter(2))
    .useBackgroundJobServer(new BackgroundJobServer(...))
    ....
```

**Comment by AlexDenisov** [comment]
This is amazing, I can confirm that both options work as expected!
I thought about using the first option, but misread the source code and wasn't sure if it'll work or not - turns out it works 👍 
Thanks a lot for your help!
