### ISSUE TITLE
upgrade to latest version Found non-empty schema(s)

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#298]
we have used version 3.0.1 while we upgrade to the latest version 4.0.5 the application failed to start due to the below exception 

Found non-empty schema(s) [dbo] but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.

**Environment**
I'm using JobRunr version: 4.0.5
I'm running on JRE / JDK :15
I'm using the following StorageProvider: SQL server

**Comment by rdehuyss** [comment]
Please search in the existing issues before opening new issues.

**Comment by engahmedtahaa** [comment]
can you please mention that issue as I have search before open the bug I did not find any thing

**Comment by rdehuyss** [comment]
https://github.com/jobrunr/jobrunr/discussions/224
