### ISSUE TITLE
The background job sever stopped after exceptions occurred on the recurring jobs

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#299]
the background job severs stopped after exceptions occurred on the recurring jobs.

**Environment**
I'm using JobRunr version: 3.0.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 15
I'm using the following StorageProvider : Sql server

**Comment by rdehuyss** [comment]
I'm sorry but there is not enough information in the issue to help you. 

Also, as my time is limited and JobRunr is working fine for a lot of other people - I decided to limit support unless you take a pro version.
