### ISSUE TITLE
GitHub Actions CI

### ISSUE THREAD

**Issue by kibertoad** [jobrunr/jobrunr#306]
**Describe the solution you'd like**
.github configuration is added to execute tests as a CI pipeline

**Comment by rdehuyss** [comment]
I'll currently using drone ci. What's wrong with that?

**Comment by kibertoad** [comment]
@rdehuyss Does it have any GitHub integration? At least PRs that I've seen do not display any checks ran on them in GitHub UI.

**Comment by rdehuyss** [comment]
Yeah, it does - but I've set it up long before, when not a lot PR's came in. Currently, it only listens for changes on the master branch. I'll have a look to also setup on PR branches (or indeed, perhaps move to Github Actions CI).

**Comment by rdehuyss** [comment]
Should be solved with commit a8fe04a186480b5598598243d92d44667a407b1e. Will monitor if this is the case.
