### ISSUE TITLE
[BUG]Recurring jobs with Cron.daily, the jobs run repeatedly

### ISSUE THREAD

**Issue by ellisonchiu** [jobrunr/jobrunr#31]
**Describe the bug**
I try recurring jobs with 0.9.16 version. when I run recurring jobs with Cron.hourly, everything is perfect. 
But run recurring jobs with Cron.daily, the jobs run repeatedly. 
After job running,  the next run of hourly job in dashboard displays xTime from now, but daily job is  xTime ago. 

**Environment**
I'm using version 0.9.16
I'm running on JRE / JDK 11.0.2

**To Reproduce**
jobScheduler.<MyService>scheduleRecurringly("Daily", myService -> myService.doSimpleJob("Hello!"),  Cron.daily());

**Expected behavior**
Daily job should be running daily. After  job running, the next run of job should be xTime ago.

**Comment by rdehuyss** [comment]
Hi @ellisonchiu , thanks for reporting this issue!

Even with 399 tests for all the Cron Expressions, this one slipped through - it was related to time zones.

I added some tests (see commit 5b1e926b639440a66805d041be6768f6b71e38c4) that make sure this will not happen in the future.

Thanks again,
Ronald

**Comment by ellisonchiu** [comment]
Tested, and works properly! Thank you!

**Comment by rdehuyss** [comment]
Wauw, you are fast! You build it yourself?
I'm finishing up support for elasticsearch and will then release a new version. Thanks for the swift feedback!

**Comment by rdehuyss** [comment]
Solved in release v0.9.17 -> 05c585e08661372f3010307412795e4b1a92b637
