### ISSUE TITLE
Integrate with KEDA for Kubernetes autoscaling

### ISSUE THREAD

**Issue by sschuberth** [jobrunr/jobrunr#311]
**Is your feature request related to a problem? Please describe.**

I'm generally interested in the "hosting in the cloud (hello Kubernetes)" usage [mentioned in the README](https://github.com/jobrunr/jobrunr/blame/master/README.md#L36). However, I could not really find good examples of how to setup Jobrunr to autoscale horizontally in Kubernetes. It seems there's a feature gap for a tool that spins up new Jobrunr nodes based on load.

As a Kubernetes newbie, I'm more or less just *guessing* that this gap could be filled by a tool like [KEDA](https://github.com/kedacore/keda) (also see my [related question on StackOverflow](https://stackoverflow.com/q/69835689/1127485) where someone recommended KEDA).

**Describe the solution you'd like**

From my brief understanding, KEDA uses so-called "[scalers](https://keda.sh/docs/2.5/concepts/external-scalers/)" to understand the load and eventually launch new pods. It seems to me like having an (external) scaler for Jobrunr (like there are [built-in scalers](https://keda.sh/docs/2.5/scalers/) for Kafka etc.) would be a beneficial thing.

**Describe alternatives you've considered**

As mentioned above, I'm a complete newbie on the topic of Kubernetes scaling, and as such I'm not aware of alternatives, not saying that there would be none.

**Additional context**

My goal would be to be able to write Jobrunr applications that automatically scale dynamically and "indefinitely" on Kubernetes depending on the load / queue length, just limited on the Kubernetes resources, without the need to manually spin up nodes / Kubernetes pods. If load decreases, resources should be freed to save costs.

**Comment by sschuberth** [comment]
BTW, I found https://cloudblogs.microsoft.com/opensource/2020/05/12/scaling-kubernetes-keda-intro-kubernetes-based-event-driven-autoscaling/ to be a good introduction to KEDA and its scalers.

**Comment by rdehuyss** [comment]
I'm afraid I don't have time to do this. Open for a PR though

**Comment by sschuberth** [comment]
> I'm afraid I don't have time to do this.

That's completely fine. I just wanted to publicly track this, also to check if other want this, too.

> Open for a PR though

So you generally agree with the feature?

**Comment by rdehuyss** [comment]
Yes, I agree the feature would come in handy.
