### ISSUE TITLE
[BUG] Succeeded jobs are not visible (Javascript error)

### ISSUE THREAD

**Issue by maborg** [jobrunr/jobrunr#32]
The job shows correctly only the detail of process in status "processing" while the others give a error in the console and a "white" page 

**Environment**
I'm using version Jobrunr  0.9.17
I'm running on JRE / JDK 11
Chrome and Firefox

Jobrunr started with (processJob and dashboard are true)
```java
        MysqlDataSource da = new MysqlDataSource();
        da.setURL(url);
        da.setUser(user);
        da.setPassword(pwd);
        JobRunrConfiguration jr = JobRunr.configure()
                .useStorageProvider(new DefaultSqlStorageProvider(da, DefaultSqlStorageProvider.DatabaseOptions.SKIP_CREATE))
                .useJobActivator(applicationContext::getBean);
        // start as a processor
        if (processJob) {
            jr.useDefaultBackgroundJobServer();
        }
        // web dashboard?
        if (hasJobDashboard)
        {
             jr.useDashboard(8000);
        }

        jr.initialize();
```
There is another processor running with both processJob and dashboard false.

The project add some job that are processed correctly but in the dashboard only the "processing" details are correctly displayed.
When you click on the link for the job:
![image](https://user-images.githubusercontent.com/1446/93296523-b094af00-f7ef-11ea-878e-9f2d98cf3328.png)

 you get an error in this js code:

![image](https://user-images.githubusercontent.com/1446/93296185-fe5ce780-f7ee-11ea-981b-2a7868117059.png)

with this log in the console:
```
react-dom.production.min.js:123 Uncaught TypeError: Cannot read property '1' of null
    at $e (succeeded-state.js:45)
    at Qe (succeeded-state.js:59)
    at Xr (react-dom.production.min.js:153)
    at ms (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Gn (react-dom.production.min.js:122)
```

**Expected behavior**
Display of the detail information

**Additional context**
We are in develop so the project has been restarted multiple times

**Comment by rdehuyss** [comment]
Hi @maborg , I think I know what is the cause: jackson is not configured to provide the time in a correct date format.

Can you perhaps open the developer tools and post me the JSON response of the REST API for one of your succeeded jobs? That way, I can perhaps solve it in a way that you don't have to change anything.

**Comment by maborg** [comment]
This probably the response JSON you need:
[response.log](https://github.com/jobrunr/jobrunr/files/5231645/response.log)

**Comment by rdehuyss** [comment]
> This probably the response JSON you need:
response.log

Indeed, excellent, I'll see whether I can reproduce it.
