### ISSUE TITLE
[Feature] Documentation clarification

### ISSUE THREAD

**Issue by wrey75** [jobrunr/jobrunr#321]
Hi,

In the page https://www.jobrunr.io/en/documentation/background-methods/logging-progress/, I was lost with your explanation when you say: 
> or - even easier - wrap your existing Logger as follows:
> new JobRunrDashboardLogger(LoggerFactory.getLogger(MyService.class))

In fact, you _have to_ declare _first_ and use the `JobRunrDashboardLogger`, not only assigning a Slf4J!

    JobRunrDashboardLogger logger = new JobRunrDashboardLogger(LoggerFactory.getLogger(MyService.class))
    logger.info("Now, at {}, I am the king of the logs", new Date());

As expected, while I read more carefully the code and tested, the logs are both visible on the console (or everywhere the logs are redirected) _AND_ in the dashboard. That's pretty cool :-)

Have a good day.

**Comment by rdehuyss** [comment]
You can always do this yourselves by clicking on the pencil icon on the website. It will bring you to a github file where you can edit the content of the website.

So, feel free to open a PR there! Thanks!
