### ISSUE TITLE
[Feature] Display on the dashboard

### ISSUE THREAD

**Issue by wrey75** [jobrunr/jobrunr#324]
Hi,

I suppose not a big challenge but putting the button of the left will help to enqueue "failed" when you want to replay a dozen jobs after a bug has been fixed. It saves mouse moves.

![jobr-display](https://user-images.githubusercontent.com/1238802/149888764-417df5cb-b49d-435c-aedc-d418263f2355.png)

Have a good day,
William.

**Comment by rdehuyss** [comment]
Hmmm, in the Pro version I will be adding a requeue all failed jobs. 

So, I don't mind that it costs some mouse moves in the free version.
