### ISSUE TITLE
[Feature] Password protect the dashboard UI

### ISSUE THREAD

**Issue by afrancis-incomm** [jobrunr/jobrunr#330]
I am planning on deploying this application in the cloud and so would need a way to restrict access to the dashboard UI by requiring that users enter a username/password or maybe some other mechanism with JWT tokens.
Do you have any documentation on how this can be achieved in a Spring Boot application using the jobrunr starter?

I would be happy with any mechanism to restrict access since the dashboard allows us to trigger and delete jobs.
Let me know if you have any suggestions.

**Comment by rdehuyss** [comment]
Please search the existing Github issues before opening a new issue.

It's not something I like to promote as the password is stored in clear text.
