### ISSUE TITLE
Deadlock on the MS SQL Server 

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#340]
we have a deadlock happens on the below query and after that background, server stopped 
sql_text (@P0 nvarchar(4000),@P1 bigint,@P2 int)select jobAsJson from jobrunr_jobs where state = @P0 ORDER BY updatedAt ASC OFFSET @P1 ROWS FETCH NEXT @P2 ROWS ONLY

**Comment by rdehuyss** [comment]
I'm a little bit fed up with people just chatting issues without even taking the time to properly follow the bug template or even formatting their code here in Github issues.

This is open-source where I spend my free and limited time on. There are explicit guidelines in the bug report which you did not follow thus making the bug report invalid.
