### ISSUE TITLE
[BUG] Generic UUID parameter gets serialized as a String, causing an exception when the job runs

### ISSUE THREAD

**Issue by smellsblue** [jobrunr/jobrunr#345]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
Using generic job class and parameter will result in an error if your parameter is a UUID.

**Environment**
I'm using JobRunr version: 4.0.3
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 17.0.2
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgresql

**How to Reproduce**
https://github.com/smellsblue/UuidSerialization is an example project that demonstrates the issue, the README has details of the issue.

**Expected behavior**
If I queue a UUID parameter as a generic type, it should be serialized as a UUID and deserialized as a UUID when the job runs.

**Additional context**
If you look at the serialized parameter, it says the actual class is String rather than UUID. A workaround of having a specific UUID parameter when processing the job works, and you can see in the database that the parameter is serialized as a UUID in that case.

**Comment by rdehuyss** [comment]
Hi @smellsblue , this issue was already solved in release 4.0.6.

If you upgrade JobRunr in your example project from 4.0.3 to 4.0.7, you will see that all is well.

**Comment by rdehuyss** [comment]
Relates to #282
