### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by cbrautigam2** [jobrunr/jobrunr#346]
On this page: https://www.jobrunr.io/en/documentation/configuration/spring/

for the org.jobrunr.background-job-server.poll_interval property, that is incorrect it should be:
org.jobrunr.background-job-server.poll-interval-in-seconds

A thorough scrub of all documented properties should be performed to make sure they sync up with the code

**Comment by rdehuyss** [comment]
Feel free to create a PR for the website - each page has an edit icon to make life easy.
