### ISSUE TITLE
[BUG] Paging statement not support oracle 11g

### ISSUE THREAD

**Issue by zgcgwin** [jobrunr/jobrunr#35]
Exception happened when execute query:

select * from jobrunr_jobs_stats ORDER BY total ASC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY

The OFFSET syntax is not support in Oracle 11g.

**Comment by rdehuyss** [comment]
Hi, which version of Oracle are you using?

**Comment by zgcgwin** [comment]
Release 11.2.0.1.0

**Comment by rdehuyss** [comment]
> Release 11.2.0.1.0

See my updated comment. Are there plans to upgrade your Oracle 11 version?

**Comment by zgcgwin** [comment]
The version is determined by our customer.
