### ISSUE TITLE
[Feature] Allow to run migrations manually

### ISSUE THREAD

**Issue by shawnest** [jobrunr/jobrunr#356]
**Is your feature request related to a problem? Please describe.**
I'm working on a project which is capable of resetting and migrating the currently running database through an endpoint. Database migration is run though Flyway which allows to DI the managed Flyway object and simply run flyway.clean() and flyway.migrate(). The problem is that flyway.clean() also drops jobrunr tables, but there is no way to migrate them again in runtime. Application restart solves the problem but it is less than ideal.

**Describe the solution you'd like**
Public method in StorageProvider or any other class for running migrations manually.

**Comment by rdehuyss** [comment]
Thanks for the input - feel free to create a PR for this.

**Comment by JanHolger** [comment]
This is already possible but there is no real api for it.

You can use `StorageProviderUtils.DatabaseOptions.SKIP_CREATE` to disable automatic database creation.

Then use the DatabaseCreator command line utility to manually migrate the database like this:
`DatabaseCreator.main(new String[]{ jdbcUrl, dbUser, dbPassword });`

This should work for you but an actual api for it would be nice anyway.

**Comment by shawnest** [comment]
Thanks @JanHolger! This is working workaround.

**Comment by rdehuyss** [comment]
Solved by @shawnest via commit 94fe6fb94c2c45713033771d0532a33f5714cb7b in branch feature/v5.
