### ISSUE TITLE
Getting NPE while running enqueued job, also unable to Autowire/Inject JobScheduler Or any such classes (Without default Constructor)

### ISSUE THREAD

**Issue by JavaGuru-04** [jobrunr/jobrunr#359]
**Are you running the latest version of JobRunr?**
Yes [4.0.8]
JDK 8
Spring Boot 2.4.9

1) Unable to Autowire/Inject JobScheduler Or any such classes (Without default Constructor)
Spring application not started due to Inject/Autowire so initialize as below
**JobScheduler jobScheduler = JobRunr.configure().useStorageProvider(storageProvider()).useBackgroundJobServer()
				.useDashboard(dashboardPort).initialize().getJobScheduler();** 

2) Unable to run enqueued job due to below error [job.enqueue(() -> jobService.execute());]
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:78)
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:63)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.<init>(AbstractJobDetailsFinder.java:17)
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:16)

3) No provision to access dashboard using application context path except http://localhost:9021/dashboard
Expected : http://localhost:9021/mycontext/dashboard

4) Planning to develop Jobrunr core scheduler engine(Plug-N-Play) which can be used to schedule any job from any of the application/microservice
1) Saving JOB details from other microservices
2) Update/Delete jobs from Jobrunr core scheduler engine if any updation/deletion done at microservice side.
3) Run all jobs of any frequencies (custom time/day/zone etc.) via Jobrunr core scheduler engine.

**Comment by rdehuyss** [comment]
Closing issue as:
- not following bug template 
- not providing a reproducible example

**Comment by rdehuyss** [comment]
There are plenty examples available on how to integrate with Spring. Have a look at https://github.com/jobrunr/example-java-mag before creating random issues.

**Comment by JavaGuru-04** [comment]
@rdehuyss This is NOT INVALID/RANDOM issue, followed example only then raised issue.
Can you tell me WHAT was missing  (Version, Code, Error ?)
Shared each and every thing code snippet as well , simply asked normal queries.
You must be co-operative to resolve issue in order to encourage using JobRUNR.

**Comment by JavaGuru-04** [comment]
@rdehuyss Resolved now, it was due to ASM jar issue.
Kindly remember, try to assist people who is seeking your help. Anyway thanks for great JOBRUNR.

**_Would you like to help on below_**

1. Planning to develop Jobrunr core scheduler engine(Plug-N-Play) which can be used to schedule any job from any of the application/microservice
2. Saving JOB details from other microservices
3.  Update/Delete jobs from Jobrunr core scheduler engine if any updation/deletion done at microservice side.
4. Run all jobs of any frequencies (custom time/day/zone etc.) via Jobrunr core scheduler engine.

**Comment by JavaGuru-04** [comment]
@rdehuyss I am using FREE version, Just wanted to check 
1) If scheduler core engine can be developed using Jobrunr or not (custom frequencies and many microservices) which will trigger all JOBS defined and set by other microservices.
2) If dashboard can be customized (contextpath or any other settings/icon/menu can be hidden/visible)
