### ISSUE TITLE
[Feature] Add support for Micrometer metrics

### ISSUE THREAD

**Issue by JoonasC** [jobrunr/jobrunr#361]
**Is your feature request related to a problem? Please describe.**
To my knowledge, JobRunr doesn't currently support exporting metrics to external systems such as Prometheus. As such, it would be nice if JobRunr had a Micrometer extension that exposed metrics which are normally only available through the dashboard.

**Describe the solution you'd like**
Create a Micrometer extension, which exposes metrics through Micrometer.

**Describe alternatives you've considered**
Haven't considered alternatives.

**Additional context**
[Micrometer](https://micrometer.io/) is a vendor neutral metrics facade for the JVM.

**Comment by rdehuyss** [comment]
Are you using an integration like Spring, Micronaut or Quarkus?

**Comment by JoonasC** [comment]
I'm not using any integration, I noticed that the spring boot starter integration already has support for Micrometer. Maybe this could be moved to JobRunr core either through the Fluent API or dependency injection?

**Comment by rdehuyss** [comment]
Feel free to create a PR for this.

**Comment by rdehuyss** [comment]
Fixed in feature/v5 branch.
