### ISSUE TITLE
[BUG] Scheduled jobs are not getting enqueued

### ISSUE THREAD

**Issue by ShubhajitM** [jobrunr/jobrunr#365]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
Scheduled jobs are saved in relational database with status as `SCHEDULED`, but jobs are never `ENQUEUED`

**Environment**
I'm using JobRunr version: <4.0.3>
I'm running on JRE / JDK <17> 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): <postgres> 

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
JobId jobId = BackgroundJob.schedule(Instant.now().plusSeconds(60), () -> System.out.println("Job completed"));
```

**Expected behavior**
after 60 seconds jobs should be processed.

**Additional context**
Jobs are always in `SCHEDULED` state.

**Comment by rdehuyss** [comment]
You did not enable a background job server. Please read the docs.

**Comment by ShubhajitM** [comment]
@rdehuyss , I enabled background job server. And enqueuing the job is working without any issue
```
org.jobrunr.job-scheduler.enabled=true
org.jobrunr.background-job-server.enabled=true
```

**Comment by rdehuyss** [comment]
Well, there are over 2000 automated tests that make sure this works. If you can setup a Github repo that reproduces it, I can have a look.

**Comment by rdehuyss** [comment]
See https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/scheduling/BackgroundJobByJobLambdaTest.java

**Comment by rdehuyss** [comment]
As you're the first one reporting this, it must be something related to your setup as last month JobRunr was downloaded 45.000 times and I did not receive another bug report like this.

**Comment by rdehuyss** [comment]
Which db are you using?

**Comment by ShubhajitM** [comment]
@rdehuyss I am using postgres

**Comment by rdehuyss** [comment]
That's what most other users also run.

If you can setup a repo that reproduces it, I'll be more than happy to reopen the issue (you can run Postgres in docker of you want). But I tried earlier today also with Postgres and all is working fine.

**Comment by rdehuyss** [comment]
Note that JobRunr only checks every 15 second if there are jobs to schedule. So the job should start processing after max 75 second.

**Comment by ShubhajitM** [comment]
@rdehuyss 
I am also getting below error:

```
Exception in thread "pool-4-thread-1" java.lang.IllegalAccessError: class org.jobrunr.jobs.states.ScheduledState$Creator4JacksonDeserializer67892a8f tried to access protected method 'void org.jobrunr.jobs.states.ScheduledState.<init>()' (org.jobrunr.jobs.states.ScheduledState$Creator4JacksonDeserializer67892a8f is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @36b4f07f; org.jobrunr.jobs.states.ScheduledState is in unnamed module of loader 'app')
        at org.jobrunr.jobs.states.ScheduledState$Creator4JacksonDeserializer67892a8f.createUsingDefault(org/jobrunr/jobs/states/ScheduledState$Creator4JacksonDeserializer.java)

```

**Comment by rdehuyss** [comment]
You are using a library (Afterburner) that has not been updated for the last 6 years and that is deprecated. If you search the github issues, here, you will see that afterburner is the reason.

See[ is:issue afterburner ](https://github.com/jobrunr/jobrunr/issues?q=is%3Aissue+afterburner+)

**Comment by rdehuyss** [comment]
You're welcome for the help and free support. Feel free to star the repo.
