### ISSUE TITLE
[Feature] Add support for Groovy

### ISSUE THREAD

**Issue by dangxunb** [jobrunr/jobrunr#367]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
This is the Groovy version of  #68, #77 
Calling BackgroundJob.enqueue with Groovy closure fail at Runtime with exception: 
`Please provide a lambda expression (e.g. BackgroundJob.enqueue(() -> myService.doWork()) instead of an actual implementation.`

**Environment**
I'm using JobRunr version: 4.0.9
I'm running on Open JDK 11 and Groovy 3.0.9

**How to Reproduce**
```groovy
BackgroundJob.enqueue( {service.doWork()} as JobLambda) //must cast because groovy can't distinguish JobLambda vs IoCJobLambda
```
Use Groovy 3's lambda syntax support doesn't work too.
```groovy
BackgroundJob.enqueue( () -> {service.doWork()} as JobLambda)
```
**Additional context**
Currently, I must use a Java Wrapper to make it work. The JobRequest/JobHandler pattern works too, but it is overcomplicated for simple use cases with many simple jobs in a project.

**Comment by rdehuyss** [comment]
Not really a bug in my eyes - I never mentioned that JobRunr supports Groovy. I honestly also don't think that I will add the support for it due to time constraints. Feel free to create a PR though.

**Comment by rdehuyss** [comment]
Time to do some spring cleaning - closing this as no PR is coming in.
