### ISSUE TITLE
Spring: Jobrunr does not use my default datasource

### ISSUE THREAD

**Issue by valh1996** [jobrunr/jobrunr#368]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
Hi, I use a MySQL database for my spring boot application. But I also have elasticsearch configured to index some texts. But my MySQL database is the main database auto-configured by spring.

I tried to install JobRunr but could not get it to work, I got this error when running `mvn clean install`:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'recurringJobPostProcessor' defined in class path resource 
[org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'recurringJobPostProcessor' parameter 0; nested exception is 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in
class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed 
through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/spring/autoconfigure/storage/JobRunrElasticSearchStorageAutoConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'elasticSearchStorageProvider' threw exception; nested exception is org.jobrunr.storage.StorageException: java.net.ConnectException: Connection refused
```

I tried to create a custom configuration based on your examples, but it does not change anything:

```java
@Configuration
public class JobRunrStorageConfig {
    @Bean
    public JobScheduler initJobRunr(DataSource dataSource, JobActivator jobActivator) {
        return JobRunr.configure()
                .useJobActivator(jobActivator)
                .useStorageProvider(SqlStorageProviderFactory
                        .using(dataSource))
                .useBackgroundJobServer()
                .useDashboard()
                .initialize().getJobScheduler();
    }
}
```

**Environment**
I'm using JobRunr version: `4.0.9`
I'm running on JRE / JDK: `AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)`

**Dependencies** (`pom.xml`):
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>

<dependency>
    <groupId>org.jobrunr</groupId>
    <artifactId>jobrunr-spring-boot-starter</artifactId>
    <version>${jobrunr.version}</version>
</dependency>

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <scope>runtime</scope>
</dependency>

<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>elasticsearch-rest-high-level-client</artifactId>
    <version>7.12.1</version>
</dependency>			
```

**Comment by rdehuyss** [comment]
Thanks for the report - for the moment, JobRunr indeed does not support 2 different databases in the standard jobrunr-spring-boot-starter.

If you would only depend on JobRunr (and not the spring boot starter), the above will work. You will not be able to use the `@RecurringJob` but can use the normal `jobScheduler.scheduleRecurrently(...)`

**Comment by rdehuyss** [comment]
Solved in branch feature/v5 scheduled to be released this month.

**Comment by valh1996** [comment]
> Thanks for the report - for the moment, JobRunr indeed does not support 2 different databases in the standard jobrunr-spring-boot-starter.
> 
> If you would only depend on JobRunr (and not the spring boot starter), the above will work. You will not be able to use the `@RecurringJob` but can use the normal `jobScheduler.scheduleRecurrently(...)`

That's the problem, I didn't use the `@RecurringJob` anywhere. It's just a fresh install of jobrunnr.
With a single datasource (mysql), but the Elasticsearch client installed in the dependencies.

I was able to correct the error below by replacing my current custom config with this:
```java
@Configuration
@ComponentScan(basePackageClasses = JobRunrStorageConfig.class)
public class JobRunrStorageConfig {
    @Autowired
    DataSource dataSource;

    @Bean
    public StorageProvider storageProvider(JobMapper jobMapper) {
        SqlStorageProvider storageProvider = new SqLiteStorageProvider(this.dataSource);
        storageProvider.setJobMapper(jobMapper);
        return storageProvider;
    }
}
```
