### ISSUE TITLE
Recurring Jobs bug

### ISSUE THREAD

**Issue by havenotfear** [jobrunr/jobrunr#373]
### Discussed in https://github.com/jobrunr/jobrunr/discussions/369

<div type='discussions-op-text'>

<sup>Originally posted by **havenotfear** March  2, 2022</sup>
I am running into an issue with long running Recurring Jobs that are in state processing and the server restarts its recurringJobId is set to null and another Job is created that has the correct recurringJobId.

These screenshots my help explain the issue.

![image](https://user-images.githubusercontent.com/1484177/156406199-174cdb45-4d55-4895-90d8-8691571471be.png)

Restarted the server and getting these processing jobs.

![image](https://user-images.githubusercontent.com/1484177/156406582-931cc0fb-4d88-4f75-8bd7-c5029707fe37.png)
</div>

**Comment by rdehuyss** [comment]
Fixed in branch feature/v5
