### ISSUE TITLE
[BUG] Fails to deserialize JobDetails from Enum with abstract member

### ISSUE THREAD

**Issue by JonasGroeger** [jobrunr/jobrunr#375]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
When serializing an Enum that has a abstract member implemented in each enum member, the `actualClassName` in the Enum is something like `Pet$2` which fails to deserialize using `@JsonCreator`. This is in the JobDetails:

```json
{
    "className": "de.example.Pet",
    "actualClassName": "de.example.Pet$2",
    "object": "dog"
},
```

Changing (manually) the `"actualClassName": "de.example.Pet$2",` to `"actualClassName": "de.example.Pet",` works fine. Might be another exception for `org/jobrunr/utils/mapper/jackson/modules/JobParameterDeserializer.java:31`?

**Environment**
I'm using JobRunr version: 4.0.9
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 11
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgres

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
BackgroundJob.enqueue(() -> myService.doWork(myDog));

public enum Pet {

    CAT("dog") {
        @Override
        public String sound() {
            return "miao";
        }
    },
    DOG("cat") {
        @Override
        public String sound() {
            return "wuff";
        }
    };

    @JsonValue
    private final String name;

    private Pet(String name) {
        this.name = name;
    }


    @JsonCreator
    public static Pet getPet(String name) {
        return Arrays.stream(values())
            .filter(pet -> pet.name.equals(name))
            .findFirst()
            .orElseThrow(NoSuchElementException::new);
    }

    public abstract String sound();
}
```

**Expected behavior**
Pet will be correctly deserialized (here: `dog`).

**Comment by rdehuyss** [comment]
This is a though one :-)

**Comment by JonasGroeger** [comment]
> Cleaning the house - wishing I were in zone

I laughed :D Thanks for the quick fix.

**Comment by rdehuyss** [comment]
No problem - feel free to star the repo if you're happy with JobRunr!
