### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by vo-davydov** [jobrunr/jobrunr#381]
### Runtime information
- __Timestamp__: 2022-03-10T10:59:55.931886900Z
- __Location__: BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101
- __JobRunr Version__: 4.0.8
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 14.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 7c1e34aa-f857-47ff-ac33-705e53006e83
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-03-10T06:29:30.266850Z, lastHeartbeat: 2022-03-10T11:00:48.029156Z)
- BackgroundJobServer id: c31567e6-540b-4378-b139-c441e03850a0
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-03-10T08:47:34.468293Z, lastHeartbeat: 2022-03-10T11:00:53.455113Z)
- BackgroundJobServer id: 705cf8f6-28e8-4703-8571-5cb1ca46a466
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2022-03-10T10:59:18.505469Z, lastHeartbeat: 2022-03-10T10:59:48.667656Z)
- BackgroundJobServer id: 698cde90-5e26-4184-949e-566580c85101
(workerPoolSize: 48, pollIntervalInSeconds: 15, firstHeartbeat: 2022-03-10T10:59:39.677054Z, lastHeartbeat: 2022-03-10T10:59:54.748969Z)

#### Concurrent modified jobs:
Job id: 8c134e40-3526-43c4-b960-ef1da17bfe93
	Local version: 4; Storage version: 5
	Local state: PROCESSING (at 2022-03-10T10:59:55.922950600Z on BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101) ← ENQUEUED (at 2022-03-10T10:59:48.646058Z) ← SCHEDULED (at 2022-03-10T10:59:48.522229Z)
	Storage state: FAILED (at 2022-03-10T11:00:19.596540Z) ← PROCESSING (at 2022-03-10T10:59:05.508478200Z on BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101) ← ENQUEUED (at 2022-03-10T10:59:48.646058Z)
Job id: c50647d7-6a41-4a6f-9c43-cf4e43b0e6bb
	Local version: 4; Storage version: 5
	Local state: PROCESSING (at 2022-03-10T10:59:55.922950600Z on BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101) ← ENQUEUED (at 2022-03-10T10:59:48.646059Z) ← SCHEDULED (at 2022-03-10T10:59:48.552485Z)
	Storage state: FAILED (at 2022-03-10T11:00:19.596899Z) ← PROCESSING (at 2022-03-10T10:59:05.508478200Z on BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101) ← ENQUEUED (at 2022-03-10T10:59:48.646059Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by rdehuyss** [comment]
Are you using read replicas in oracle?

**Comment by vo-davydov** [comment]
@rdehuyss 

No, It is not a replica, maybe an error has happened because a few users work with a local application that uses the same database. Could it be because of this?

**Comment by rdehuyss** [comment]
Are you creating jobs using your own uuids?

**Comment by vo-davydov** [comment]
Yes, I do

**Comment by rdehuyss** [comment]
The only reason I can think of, is that one of the PC's was so busy (doing other work like compilation) causing this error.

Normally, each job is updated with a timestamp every 15 seconds, but for some reason (probably the one above), the job was not updated for more than a minute causing this error. 

See here: `FAILED (at 2022-03-10T11:00:19.596899Z) ← PROCESSING (at 2022-03-10T10:59:05.508478200Z on BackgroundJobServer 698cde90-5e26-4184-949e-566580c85101)` - the maximum there should be between those timestamps is 15 seconds in your case.

If you have this error again in PRD, feel free to reopen the issue.
