### ISSUE TITLE
[BUG] Micronaut optional dependencies

### ISSUE THREAD

**Issue by dawiemalan** [jobrunr/jobrunr#392]
**Are you running the latest version of JobRunr?**
Yes
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
JobRunrFactory should not require all storage provider dependencies when running with Micronaut.

**Environment**
I'm using JobRunr version: 5.0.0-RC1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 11
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): SQL

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
Any micronaut project without for e.g. ElasticSearch client dependency.

**Expected behavior**
Should run with dependencies of selected storage provider only, or fall back to in-memory provider.

**Additional context**
Patch attached:
[micronaut-deps.tar.gz](https://github.com/jobrunr/jobrunr/files/8303156/micronaut-deps.tar.gz)

**Comment by rdehuyss** [comment]
Hi and thanks for the patch.

It's strange that you have this error as the [micronaut demo project](https://github.com/jobrunr/example-micronaut) doesn't suffer from this issue.

There, the ElasticSearch client dependency is not added and everything works (unless it comes in as a transitive dependency via micronaut).

**Comment by rdehuyss** [comment]
I'm also afraid that your patch seems to be inverted (so the extra classes you added are deleted inside the path) and if I do everything as I think you intended to setup, tests fail.

**Comment by dawiemalan** [comment]
No problem. I've actually implemented an extension of jobrunr-micronaut-feature to support domain-specific functionality for internal projects, and thought to share this in case it is useful.
