### ISSUE TITLE
[Feature] Java standard interface for enquee parameter method

### ISSUE THREAD

**Issue by leoandrea7** [jobrunr/jobrunr#393]
Hi,
is possible to add the possibility to pass a java standard Interface as parameter (e.g. Runnable) in jobScheduler.enqueue method instead of JobLambda? This improves interopererability a lot. Thanks

**Comment by rdehuyss** [comment]
This is not possible as a Runnable is not Serializable by default which is needed for the lambda analysis.

Why is it bothering you?

**Comment by leoandrea7** [comment]
@rdehuyss It does not bother me but simply this not allow interoperability.
For example in a wrapper scenario where you want to parameterize lambda, who call start method is couple with your library.
` public class JobService {
  .....
       public void start(JobLambda jobLambda) {
           //do some stuff
          jobScheduler.enqueue(jobLambda);
       }
 .....
}`

If you add the possibility to pass some Java standard interface there would be no such problem.
