### ISSUE TITLE
[Feature] Allow RetryFilter to be set on each Job

### ISSUE THREAD

**Issue by arvindkgs** [jobrunr/jobrunr#399]
**Is your feature request related to a problem? Please describe.**
RetryFilter can be set only on JobScheduler/JobSchedulerRequest, which is a singleton and only one exists per application, implying that RetryFilter is set only once for all jobs. However, some jobs require different retry value, based on if time elapsed then don't retry (as it is a real time application)

**Describe the solution you'd like**
Allow `BackgroundJob.schedule`,`BackgroundJob.enqueue`  etc to accept RetryFilter param

**Describe alternatives you've considered**
Tried creating new JobScheduler per job, but this defeats the purpose of JobScheduler

**Comment by rdehuyss** [comment]
This is already possible using the `Job` annotation.

See https://www.jobrunr.io/en/documentation/background-methods/dealing-with-exceptions/

**Comment by arvindkgs** [comment]
@rdehuyss but is this possible without annotations? I mean creating jobs dynamically with retryfilter?

**Comment by rdehuyss** [comment]
No, currently it is only possible with annotations. What is the disadvantage of using the annotation in your eyes?

Because currently, I'm not following your exact use case. Can you give a complete example?
