### ISSUE TITLE
[BUG] RetryFilter alwas falls into number of retries from Job annotation

### ISSUE THREAD

**Issue by mikekay68** [jobrunr/jobrunr#401]
**Are you running the latest version of JobRunr?**
Yes 
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
I am implementing RetryFilter and noticed that retries from Job annotation supersedes numberOfRetries from RetryFilter and if I do not pass retries in Job annotation then it uses default, which is 10, which leads RetryFilter implementation to run 10 times although number of retries in Filter is set to 5.
So in order to have number of retries being 5 when I use explicit implementation of RetryFilter I have to set retries in both places - Filter and Job annotation.

```java
private int getMaxNumberOfRetries(Job job) {
        return JobUtils.getJobAnnotation(job.getJobDetails()).map(org.jobrunr.jobs.annotations.Job::retries).orElse(this.numberOfRetries);
    }
```
```java
public @interface Job {

    String name() default "";

    int retries() default RetryFilter.DEFAULT_NBR_OF_RETRIES;

    Class<? extends JobFilter>[] jobFilters() default {};
}
```

**Environment**
I'm using JobRunr version: 4.0.10
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJdk 11 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Oracle

**How to Reproduce**
implement RetryFilter set numberOfRetries to 5 and then do not set retries in Job annotation. JobRunr will try to run failed job 10 times instead of 5.
```java
public class RetryFailedJobFilter extends RetryFilter {

  private final int retryNumber;

  public RetryFailedJobFilter(int retryNumber,) {
    super(retryNumber);
    this.retryNumber = retryNumber;
  }

  @Override
  public void onStateElection(Job job, JobState newState) {
    super.onStateElection(job, newState);
    long failedCount = job.getJobStates().stream().filter(FAILED_STATES).count();
    if (failedCount > retryNumber) {
      log.info("Job with Id={} failures reached={} times. Rescheduing...", job.getId(), failedCount);
    }
  }
```

**Expected behavior**
Default number of retries from Job annotation should not supersede numberOfRetries in Filter if no retries set in Job. 

**Additional context**

**Comment by rdehuyss** [comment]
Feel free to star the JobRunr repository!

It will be part of release 5.0.1 which will be available somewhere before the end of the month.
