### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wuyuan2009123** [jobrunr/jobrunr#402]
jdk1.8 There are two classes:
sun.misc.ServiceConfigurationError
java.util.ServiceConfigurationError
jdk 11  There's only one class:
java.util.ServiceConfigurationError

Launching locally with JDK 11 has no problems if deployed with JBoss
Factory method 'dashboardWebServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: java.lang.ClassNotFoundException: sun.misc.ServiceConfigurationError from [Module

**Comment by rdehuyss** [comment]
Closing as to not following bug report guidelines.
