### ISSUE TITLE
Newest version of JobRunr has critical vulnerability

### ISSUE THREAD

**Issue by mikekay68** [jobrunr/jobrunr#407]
Tried to use latest version of jobrunr-spring-boot-starter:5.0.0 and it was rejected by our system due to spring-beans:5.3.16  having vulnerability - https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2436751. Please update spring-boot version

**Comment by rdehuyss** [comment]
Feel free to open a PR.

**Comment by rdehuyss** [comment]
The part that is really not fun on open-source - having some days with family and then all these support issues...

Anyway, a new CD pipeline is running. Will be released somewhere early next week I think.
