### ISSUE TITLE
[Feature] Add ability to have own Authenticator implementation

### ISSUE THREAD

**Issue by mikekay68** [jobrunr/jobrunr#410]
**Is your feature request related to a problem? Please describe.**
We need to secure access to the dashboard and having option of stored plain username/password is not acceptable by our rules.
Does Dashboard in Pro have this option?

**Describe the solution you'd like**
Have ability to pass own Authenticator implementation to JobRunrDashboardWebServer or have SecurityConfig available in spring-boot version with ability to load our own config.

**Describe alternatives you've considered**
There is no other alternative except writing our own version of JobRunrDashboardWebServer to use custom Authenticator, then disable actual class from loading as Spring bean and use ours, which is, correct me if I'm wrong, not a good idea.

**Additional context**

**Comment by rdehuyss** [comment]
I'll look into it - OpenId connect support was already planned for JobRunr Pro.

**Comment by rdehuyss** [comment]
@mikekay68: could you please also add me on LinkedIn? I'm curious for what you are using JobRunr.

**Comment by mikekay68** [comment]
Thanks, but this is not what I meant. OpenId is fine but you're limiting users to it. In our case OpenId s not an option.
What I meant is users need to have ability to pass they own Authenticator like this. This is just an example without all constructors you have. 

```java

import com.sun.net.httpserver.Authenticator;
import com.sun.net.httpserver.HttpContext;
import java.util.Objects;
import lombok.extern.slf4j.Slf4j;
import org.jobrunr.dashboard.JobRunrApiHandler;
import org.jobrunr.dashboard.JobRunrDashboardWebServer;
import org.jobrunr.dashboard.JobRunrSseHandler;
import org.jobrunr.dashboard.JobRunrStaticFileHandler;
import org.jobrunr.dashboard.server.HttpExchangeHandler;
import org.jobrunr.dashboard.server.WebServer;
import org.jobrunr.dashboard.server.http.RedirectHttpHandler;
import org.jobrunr.storage.StorageProvider;
import org.jobrunr.storage.ThreadSafeStorageProvider;
import org.jobrunr.utils.mapper.JsonMapper;

@Slf4j
public class JobRunrDashboardWebServer  {

  private final StorageProvider storageProvider;

  private final JsonMapper jsonMapper;

  private final int port;

  private Authenticator authenticator;

  private WebServer webServer;

  public JobRunrDashboardWebServer(StorageProvider storageProvider, JsonMapper jsonMapper, int port) {
    this.storageProvider = new ThreadSafeStorageProvider(storageProvider);
    this.jsonMapper = jsonMapper;
    this.port = port;
  }

  public void setAuthenticatior(Authenticator authenticator) {
    this.authenticator = authenticatior;
  }

  @Override
  public void start() {
    RedirectHttpHandler redirectHttpHandler = new RedirectHttpHandler("/", "/dashboard");
    JobRunrStaticFileHandler staticFileHandler = createStaticFileHandler();
    JobRunrApiHandler dashboardHandler = createApiHandler(storageProvider, jsonMapper);
    JobRunrSseHandler sseHandler = createSSeHandler(storageProvider, jsonMapper);

    webServer = new WebServer(port);
    registerContext(redirectHttpHandler);
    registerSecuredContext(staticFileHandler);
    registerSecuredContext(dashboardHandler);
    registerSecuredContext(sseHandler);
    webServer.start();

    log.info("CustomJobRunrDashboardWebServer using {} started at http://{}:{}/dashboard",
        storageProvider.getName(),
        webServer.getWebServerHostAddress(),
        webServer.getWebServerHostPort());
  }

  @Override
  public void stop() {
    if (webServer == null) {
      return;
    }
    webServer.stop();
    log.info("JobRunr dashboard stopped");
    webServer = null;
  }

  HttpContext registerContext(HttpExchangeHandler httpHandler) {
    return webServer.createContext(httpHandler);
  }

  HttpContext registerSecuredContext(HttpExchangeHandler httpHandler) {
    HttpContext httpContext = registerContext(httpHandler);
    if (Objects.nonNull(authenticator)) {
      httpContext.setAuthenticator(authenticator);
    }
    return httpContext;
  }

  JobRunrStaticFileHandler createStaticFileHandler() {
    return new JobRunrStaticFileHandler();
  }

  JobRunrApiHandler createApiHandler(StorageProvider storageProvider, JsonMapper jsonMapper) {
    return new JobRunrApiHandler(storageProvider, jsonMapper);
  }

  JobRunrSseHandler createSSeHandler(StorageProvider storageProvider, JsonMapper jsonMapper) {
    return new JobRunrSseHandler(storageProvider, jsonMapper);
  }

}
````

**Comment by pixnbit** [comment]
OpenId support would be a great addition. This can be a primary differentiator for the pro version vs free

**Comment by qanik1307** [comment]
Using our own Authenticator would a great addition. I would also suggest that the build in Configuration should not use plain passwords. There should be something like BCrypt involved to only have the hashed passwords in the configuration.

I would also like to suggest, that there should be an option to integrate the Dashboard in Spring Boot, so there is no need to start its own webserver. Then the whole security configuration can be handled by Spring Security.

**Comment by rdehuyss** [comment]
Also look at Okta for SSO.

**Comment by gitmiro** [comment]
I second @qanik1307 input. Integrating the dashboard into Spring Boot would solve our auth-issue which relies on Spring Security. Don't mind if only in pro =)

**Comment by rdehuyss** [comment]
Well, then you're going to love JobRunr 6 😉.

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro v6 branch to be released by the end of the year.

**Comment by rdehuyss** [comment]
@qanik1307 and @gitmiro : a little bit later than expected but ... https://github.com/jobrunr/jobrunr/releases/tag/v6.0.0-M0

**Comment by gitmiro** [comment]
wohooo! I‘m gonna spread the word 🎉
