### ISSUE TITLE
[Feature] Ability to keep dashboard logs after job success

### ISSUE THREAD

**Issue by ofayau** [jobrunr/jobrunr#411]
**Is your feature request related to a problem? Please describe.**
A breaking change in 5.0.0 was to clear metadata on job success.
I use jobrunr for database monitoring with a K8S microservice.
The dashboard logging is the easiest way to "watch the watcher" ;-)

**Describe the solution you'd like**
Use a new flag (and new property) to allow to keep metadata after success (at least dashboard logs).

**Describe alternatives you've considered**
Add classic log and access them on K8S console or add distributed log. Both seems overkill.

**Comment by rdehuyss** [comment]
Fixed. You could do me a favor if you star the repo.

**Comment by ofayau** [comment]
Thanks! ⭐
