### ISSUE TITLE
[Feature] Non standard character cron expression like W and # for recurring jobs.

### ISSUE THREAD

**Issue by miteshjoshi** [jobrunr/jobrunr#419]
**Is your feature request related to a problem? Please describe.**
What are trying to acheive is recurring job scheduling with requirement such as - 

1. `Every 3rd MON of month at 10:00AM` -> 0 10 ? * 2#1 * alternatively cron 0 10 15-21 * 1 can also be a potential solution but require business logic. 

2.  `Every first MON of month at 10:00AM`

**Describe the solution you'd like**
For that we can have non-standard character support of `#` - [wiki](https://en.wikipedia.org/wiki/Cron#Non-standard_characters
)

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro branch v6.
