### ISSUE TITLE
[BUG] Cannot resolve method 'awaitAll' in 'Futures' when using lettuce

### ISSUE THREAD

**Issue by paz-raon** [jobrunr/jobrunr#42]
**Describe the bug**

the 'awaitAll' method not found in LettuceRedisStorageProvider, LettuceRedisPipelinedStream classes

<img width="491" alt="스크린샷 2020-10-08 오후 2 08 46" src="https://user-images.githubusercontent.com/1497209/95417526-3f6c9580-0970-11eb-911e-b929a5cc03ef.png">

**Environment**
I'm using version 1.0.0
I'm running on JRE / JDK 11, lettuce-core 5.3.3.RELEASE

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```java
BackgroundJob.enqueue(() -> service.helpMe());
```

**Expected behavior**

**Additional context**

changes Futures.awaitAll to LettuceFutures.awaitAll maybe?

**Comment by rdehuyss** [comment]
Hi,

I guess this is because JobRunr is using Lettuce 6.0 (whereas you are using 5.3). I'll look into the effort on supporting 5.x but is it an option for you to upgrade Lettuce?

**Comment by paz-raon** [comment]
Hi,

I am using spring boot 2.3.x.
It is resolved when the dependency version is raised (https://github.com/spring-projects/spring-boot/issues/23360)
I think it will apply to Spring Boot 2.4, but I want to use it right now.

**Comment by rdehuyss** [comment]
If you indeed upgrade to spring-boot-2.4.0-M3, all should be well. Is that an option?

**Comment by rdehuyss** [comment]
Version 1.0.1 is released.
