### ISSUE TITLE
[BUG] 'Next run' in dashboard page is not reset but count up after count down to 0

### ISSUE THREAD

**Issue by joejoe2** [jobrunr/jobrunr#425]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
'Next run' in dashboard page is not reset but count up after count down to 0, I have to reload the page to get the normal values

**Environment**
I'm using JobRunr version: 5.0.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 1.8.0_292
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): pgsql 

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
jobScheduler.scheduleRecurrently(Duration.ofMinutes(1), ()->jwtService.deleteExpiredTokens());
```

**Expected behavior**
you can see the video in below, the 'Next run' should be reset after count down to 0

**Additional context**
https://user-images.githubusercontent.com/39475537/164582826-2caa49c6-82e8-44fa-a726-0a0d78234d97.mp4

**Comment by rdehuyss** [comment]
To be honest, I actually like the fact that I can see how long ago it has run and I know that by refreshing the page, it will updated again to the next run.

I'm closing this for now and if more people complain about it (you are the first), we can revisit this.

**Comment by joejoe2** [comment]
> To be honest, I actually like the fact that I can see how long ago it has run and I know that by refreshing the page, it will updated again to the next run.
> 
> I'm closing this for now and if more people complain about it (you are the first), we can revisit this.

I suggest replace 'next run' with 'last run'
