### ISSUE TITLE
[Feature] Allow null parameter values using an annotation

### ISSUE THREAD

**Issue by JanHolger** [jobrunr/jobrunr#428]
**Is your feature request related to a problem? Please describe.**
When trying to pass null into an optional parameter of type UUID we ran into the following issue:
```
java.lang.NullPointerException: You are passing null as a parameter to your background job for type java.util.UUID - JobRunr prevents this to fail fast.
```
I totally get why this protection exists and it's definitely a good idea but as we often use null for optional parameters and do null checks inside the method before using those parameters it would be great to have an annotation to disable this protection for certain parameters. I haven't tried but I guess the Optional type probably isn't properly serialized either.

**Describe the solution you'd like**
An `@AllowNull` or `@Nullable` annotation that disables the null check for a parameter.

**Describe alternatives you've considered**
The only solution I see to get around this at the moment is using some wrapper class or using String instead of UUID and interpreting empty strings as null but those are pretty ugly and painful solutions and as JobRunr aims to be simple there should be some easier way for it. I could also write a second method that takes less parameters and forward the call to the actual method but that's pretty verbose and doesn't work in every case.

**Comment by JanHolger** [comment]
Sure like explained in the initial comment that's an option but with multiple optional parameters this get's quite messy and the overload methods would just end up calling the actual method with null values again. It's just an idea, if you don't think it's necessary we can work around it using wrapper classes.

**Comment by rdehuyss** [comment]
To be honest, I'm not a big fan of this. One of the reasons I like java is method overloading (compared to other languages like Typescript). 

In my personal opinion: if you pass an explicit null to a method, this looks like a design smell. Off-course I don't know your codebase and there can also be a legit reason for it but I have not encountered this a lot to be honest.

I'll close it for now and if this question [comes again](https://github.com/jobrunr/jobrunr/search?q=prevents+this+to+fail+fast), we can discuss this again.
