### ISSUE TITLE
[BUG] Severe JobRunr Exception - caused by RedisStorageProvider (BETA)

### ISSUE THREAD

**Issue by lrgalego** [jobrunr/jobrunr#429]
### Runtime information
- __Timestamp__: 2022-04-25T11:23:38.911857Z
- __Location__: BackgroundJobServer 7bb626e4-87d8-4047-ad04-171490e5a9fc
- __JobRunr Version__: 4.0.9
- __StorageProvider__: org.jobrunr.storage.nosql.redis.LettuceRedisStorageProvider
- __Java Version__: 11.0.14.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 7bb626e4-87d8-4047-ad04-171490e5a9fc
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-22T19:03:43.277795Z, lastHeartbeat: 2022-04-25T11:23:27.555527Z)
- BackgroundJobServer id: 14075d2a-7139-4582-8599-dde439d47950
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-22T19:07:37.339742Z, lastHeartbeat: 2022-04-25T11:23:31.941296Z)
- BackgroundJobServer id: dfe78ec5-1ace-4915-a5d5-388b22e404e0
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-23T20:56:36.567183Z, lastHeartbeat: 2022-04-25T11:23:25.668342Z)
- BackgroundJobServer id: 48ce8d81-3a4a-4b6c-89ac-9faec8d9a471
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-24T04:14:16.265493Z, lastHeartbeat: 2022-04-25T11:23:37.106664Z)
- BackgroundJobServer id: e1da85ca-69d8-45a2-873a-28e45af5b13c
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-24T22:05:15.627386Z, lastHeartbeat: 2022-04-25T11:23:38.404756Z)

#### Concurrent modified jobs:
Job id: b2bbceca-3ef6-4ad4-9851-6042e77b65d7
	Local version: 356; Storage version: 360
	Local state: PROCESSING (at 2022-04-25T11:23:38.907085Z on BackgroundJobServer 7bb626e4-87d8-4047-ad04-171490e5a9fc) ← ENQUEUED (at 2022-04-25T09:55:04.411949Z) ← SCHEDULED (at 2022-04-25T09:54:49.401021Z)
	Storage state: SUCCEEDED (at 2022-04-25T11:23:38.043461Z) ← PROCESSING (at 2022-04-25T11:23:37.272624Z on BackgroundJobServer 14075d2a-7139-4582-8599-dde439d47950) ← ENQUEUED (at 2022-04-25T11:23:29.094214Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment]
I'm afraid [Redis StorageProvider](https://www.jobrunr.io/en/documentation/installation/storage/) is still in beta because of this reason. Under load, the RedisTransaction does not save all keys for some reason. 

I did not find the root cause yet.

**Comment by rdehuyss** [comment]
I wanted to let you know that I'm currently looking it with the guys from Redis! They are awesome!

**Comment by rdehuyss** [comment]
@lrgalego - can I ask how many recurring jobs you have to diagnose this issue?

**Comment by lrgalego** [comment]
Hi, it's just 1 job that I need to run every 10 min. since I have many intances, I'm using JobRunr to have an easy way to run just one job at a time.

**Comment by rdehuyss** [comment]
Does this recurring job take a lot of time?

**Comment by lrgalego** [comment]
Yes, it can take some minutes

**Comment by rdehuyss** [comment]
So if I'm correct, that recurring job does not generate any other jobs?

**Comment by lrgalego** [comment]
no, its a self contained job

**Comment by rdehuyss** [comment]
Ok, this should be solved with the next release of JobRunr but it's a long time I've seen this. As I cannot reproduce this locally, I'm curious on how it will go. Please reopen if it's not solved with the next release of JobRunr.

**Comment by lrgalego** [comment]
Thanks @rdehuyss!
Do you have a schedule for the release?
