### ISSUE TITLE
[BUG] execute only one recurring job

### ISSUE THREAD

**Issue by paz-raon** [jobrunr/jobrunr#43]
**Describe the bug**
Even though two jobs are registered, only one works.

<img width="1228" alt="스크린샷 2020-10-08 오후 10 36 51" src="https://user-images.githubusercontent.com/1497209/95466170-060b4880-09b7-11eb-8c35-fe7b605d77ab.png">

**Environment**
I'm using version 1.0.0
I'm running on JRE / JDK 11

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```java
BackgroundJob.enqueue(() -> service.helpMe());
```

**Expected behavior**
All recurring jobs are executed at same cron expression.

**Additional context**

**Comment by rdehuyss** [comment]
Is this using the LettuceStorageProvider?

**Comment by rdehuyss** [comment]
This is indeed a bug but I don't know what to do with it as it is working as designed. 

Let me give an example: you schedule a recurring method every minute with a variable:
E.g. `BackgroundJob.enqueue(() -> service.helpMe(LocalDateTime.now()));`

 But the `service.helpMe()` method takes longer than 30 seconds to complete. In this case, you will keep adding jobs faster than you can process.

To prevent that, JobRunr checks that the same `class.method()` is not already scheduled or running.

In your case, as you are two jobs using `System.out.println`, JobRunr thinks the same job is already running.

I'm thinking of a way on how to handle this gracefully but don't know how yet. But at least you know why only one job is running.

**Comment by rdehuyss** [comment]
Idea: 
- create a @RecurringJob annotation which is similar to the @Job annotation
- it will have a setting `schedule` which will be by default `serial` meaning that JobRunr will check that the same job is not already scheduled/running. You can also provide the option `parallel` which allows overriding the aforementioned behavior 

Downside: your example will still not work as you can not put an @RecurringJob annotation on `System.out.println`.

What do you think?

**Comment by rdehuyss** [comment]
Will be solved by using the recurring job id to check whether the job is already `SCHEDULED`, `ENQUEUED`, or `PROCESSING` instead of the job signature.

This solved the OP's problem completely.

**Comment by rdehuyss** [comment]
Includes new migration -> adds recurringJobId as column
