### ISSUE TITLE
[BUG] Unicode strings in JobRequest fields causes java.sql.SQLException: Incorrect string value for column 'jobAsJson' at row 1

### ISSUE THREAD

**Issue by patkujawa-wf** [jobrunr/jobrunr#436]
**Are you running the latest version of JobRunr?**
No, this is on the latest of v4. We're upgrading to v5 ASAP though!

**Describe the bug**
When a string field (`filename`, say) includes unicode characters (e.g. â) and you try to enqueue that job, an exception is thrown and the job isn't enqueued:

> stacktrace: org.jobrunr.storage.StorageException: java.sql.SQLException: Incorrect string value: '\xE2\x9A\xBE\xEF\xB8\x8F...' for column 'jobAsJson' at row 1 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java) at org.jobrunr.scheduling.AbstractJobScheduler.saveJob(AbstractJobScheduler.java) at org.jobrunr.scheduling.AbstractJobScheduler.enqueue(AbstractJobScheduler.java) at org.jobrunr.scheduling.JobRequestScheduler.enqueue(JobRequestScheduler.java) at org.jobrunr.scheduling.JobRequestScheduler.enqueue(JobRequestScheduler.java) at

**Environment**
I'm using JobRunr version: 4.0.10
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 64-Bit Server VM 11.0.15+9-LTS
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): MySQL (Aurora)

**How to Reproduce**
I can supply more here in a bit, just wanted to raise the issue first in case it's an obvious fix.

```kotlin
class ExportCombinedContentJobRequest(
    val filename: String,
) : JobRequest {
    override fun getJobRequestHandler(): Class<ExportCombinedContentRequestHandler> {
        return ExportCombinedContentRequestHandler::class.java
    }
}
```

**Expected behavior**
The unicode string field is converted to json and stored in the db as a normal job.

**Comment by patkujawa-wf** [comment]
I'm not a db expert, but I can see the table in our cluster showing "Table collation" as `latin1_swedish_ci`, rather than, say, `utf8_general_ci`. Is that something jobrunr's migration scripts would/should be setting on the tables, or something we should be doing as defaults, maybe?

**Comment by rdehuyss** [comment]
Indeed, when you create a database, you setup the default collation. It's outside of JobRunr's scope as it doesn't know upfront what type of Jobs (e.g. is support for unicode needed) you would create (although I always use UTF-8 just out of convenience).

Why is it by default `latin1_swedish_ci`? Quoting Giacomo1968 from [stackoverflow](https://stackoverflow.com/questions/6769901/why-is-mysqls-default-collation-latin1-swedish-ci): 
> [The bloke who wrote it](http://en.wikipedia.org/wiki/Michael_Widenius) was co-head of a [Swedish company](http://en.wikipedia.org/wiki/MySQL_AB).

I also can highly recommend Postgres over MySql ([and I'm not the only one](https://www.theregister.com/2021/12/06/mysql_a_pretty_poor_database/)).

**Comment by patkujawa-wf** [comment]
Thanks, that makes sense, and clearly we should have set better defaults in the beginning 😆 .

My plan is to change those defaults, then alter all the tables to use a unicode collation.
