### ISSUE TITLE
[BUG] Not all the recurring jobs are getting scheduled

### ISSUE THREAD

**Issue by ms-precisely** [jobrunr/jobrunr#437]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
This is to reopen bug in https://github.com/jobrunr/jobrunr/issues/426. Details provided in bug[#426](https://github.com/jobrunr/jobrunr/issues/426)

**Environment**
I'm using JobRunr version: 5.0.1
I'm running on JRE / JDK: java 11
I'm using the following StorageProvider : MongoDB Atlas

**How to Reproduce**
I have create github repo [SchedulerService](https://github.com/ms-precisely/SchedulerService). @rdehuyss, I have provided access to you. Please let me know if anyone else needs to get access to this.
It has a create schedule API. Details of this API are available in readMe file.
This issue occurs with storage provider MongoDB Atlas. The recurring job occurence used is Daily.

**Comment by rdehuyss** [comment]
Thanks for this. As soon as I have some time, I'll look into it. It feel free to have a look yourselves and create a PR.

**Comment by rdehuyss** [comment]
After discussion with @ms-precisely, this apparently only happens with MongoDB Atlas.

**Comment by rdehuyss** [comment]
I was able to reproduce it. The reason is that there are so many jobs triggering at exactly the same time. If they are spread in time, this would not happen.

Some history: In the applications I mostly create, I have max 20 to 30 CRON jobs. The way I do it is that a CRON job starts at a certain moment and that CRON job then schedules extra work.

Is there a reason that you have so many jobs triggering at the same time? I'm curious in the exact reason why you have so many of these jobs triggering at the same instant. 

I am able to solve this but it requires some time. I think that about 1000 recurring jobs should work out.

**Comment by rdehuyss** [comment]
See discussion https://github.com/jobrunr/jobrunr/discussions/465

**Comment by rdehuyss** [comment]
Will soon be fixed.

**Comment by ms-precisely** [comment]
Hi @rdehuyss,

Is this fix available now?

**Comment by rdehuyss** [comment]
Hi @ms-precisely , this is already solved in the pro version. I'm still deciding on whether this amount of recurring jobs should also be available in the free version. (currently my free time is limited until the end of August).

I tried contacting you a while ago regarding this.

**Comment by ms-precisely** [comment]
Thanks @rdehuyss.

**Comment by rdehuyss** [comment]
Not stale

**Comment by ms-precisely** [comment]
Hi @rdehuyss,

As you would already know, my company has started the procurement of JobRunr Pro license. I tried about 5K concurrent jobs with the Pro version and was able to process those without any issues. Just wanted to confirm with you if there is any upper limit to the number of concurrent jobs with the Pro version.

**Comment by rdehuyss** [comment]
Hi @ms-precisely , I personally have tested up to 5000 jobs in the Pro version. More jobs could work but I did not profile it enough yet.

I hope to have some time to test this in September.

**Comment by rdehuyss** [comment]
JobRunr 6 Pro is around the corner and has (in theory) support for unlimited recurring jobs. First tests of up to 25.000 recurring jobs where successful.
