### ISSUE TITLE
Edit Schedule (Create Schedule + Delete Schedule + Create Schedule With same Id) Not working

### ISSUE THREAD

**Issue by kapilbablani** [jobrunr/jobrunr#450]
Team, I am facing an issue explained in steps below-

- I have created the scheduled job with daily event using jobRunr.
- Now, after its execution, now the user editted it to some other time for the day.
- In this case, I delete the existing schedule and create the new one with the same Id for the newer time.
- This editted scheduler is visible properly on the JobRunr Dashboard with the updated time but this don't run on the newer time.

The issue is very critical for us and we are blocked to proceed further.

**Comment by kapilbablani** [comment]
@rdehuyss Please take a look

**Comment by rdehuyss** [comment]
I'm sorry but I do not give priority support on the free version. 

Updating scheduled Jobs is part of a Pro feature. See the [JobRunr Pro docs](https://www.jobrunr.io/en/documentation/pro/replace-jobs/).

**Comment by kapilbablani** [comment]
Our organization is soon planning to go for PRO. But at this point we are handling edit through create and deleting the scheduler again.

**Comment by kapilbablani** [comment]
Can you just tell us if this is an known issue and the approach we are following is workable (creating the schedule with id -> then deleting it -> crating again with updated data but same Id)
