### ISSUE TITLE
[BUG] Jobrunr auto removes working nodes without resuming in case of heartbeat timeout

### ISSUE THREAD

**Issue by PhilipJu11** [jobrunr/jobrunr#453]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
There is an existing bug in jobrunr package, when request from jobrunr for last-heartbeat got timed out due to network or DB connection latency, it will auto remove all working nodes without unlocking master node, hence no node would be restarted afterwards, when next scheduled job tries to run however found no working node, it pops up an 'shouldNotHappen' Exception.

**Environment**
I'm using JobRunr version: jobrunr-spring-boot-starter: 3.2.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 1.8.0_322
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Oracle

**How to Reproduce**
can reproduce this issue when there is a network or DB connection latency

**Expected behavior**
when the last heartbeat got timed out, master node should be unlocked so that the jobrunr knows there is an issue and it should do auto restart to resume.

**Additional context**
please find below exception:
'org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)'
caused by: java.lang.IllegalStateException: No servers available?!

**Comment by rdehuyss** [comment]
Please first upgrade to the latest version and see whether or still happens.

**Comment by rdehuyss** [comment]
This was already solved in v4.
