### ISSUE TITLE
[Feature] Ability to still customize JobRunr programmatically when configured through a framework 

### ISSUE THREAD

**Issue by pixnbit** [jobrunr/jobrunr#458]
Either the feature is not documented or missing. I wanted to setup the micrometer tracking, but I didn't find a way to customize JobRunner instanced after it's setup through application config in Micronaut. It would be nice to provide a callback so we could still customize even if the scheduler is setup with a framework

**Comment by pixnbit** [comment]
Actually nvm, micrometer has already been wired up without me needing to do anything. But still a callback point to customize could still be useful for some.

**Comment by rdehuyss** [comment]
Just create the beans you want to alter yourselves, then these will be used instead of the standard beans provided by JobRunr.
