### ISSUE TITLE
[BUG] Dashboard graph shows negative jobs

### ISSUE THREAD

**Issue by biggms8x8** [jobrunr/jobrunr#462]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
When running 1700 recurring jobs every 3 minutes the realtime graph shows negative values

![image](https://user-images.githubusercontent.com/76120087/169573418-47d07747-0b23-4267-9061-410771fc3d77.png)

Using the following jobrunr settings:
`org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 10
      poll-interval-in-seconds: 15
      delete-succeeded-jobs-after: 1
      permanently-delete-deleted-jobs-after: 2
    dashboard:
      enabled: false
    jobs:
      default-number-of-retries: 0
`
With a dashboard running on a seperate server and 6 background servers

I suspect the bug is related to the deletion of jobs inbetween updates of the graph

**Environment**
I'm using JobRunr version: 5.1.1
JDK 11, under spring-boot on k8s

**How to Reproduce**
Add 1700 fast executing recurring jobs

**Expected behavior**
Bars on the graph should only be positive

**Comment by rdehuyss** [comment]
Lol: I initially thought that 50 recurring jobs in a project was a lot 🤣 . That's why the recurring jobs page does not have paging. Now I see you are doing 1700.

Looking for some feedback here: I'm thinking of limiting the amount of CRON jobs in JobRunr OSS to 200. I assume it's a dealbreaker for you?

**Comment by rdehuyss** [comment]
See discussion https://github.com/jobrunr/jobrunr/discussions/465

**Comment by rdehuyss** [comment]
Causes regression - reason it is negative is that succeeded jobs go to deleted state (so there are less) and that's why the count is negative.

**Comment by rdehuyss** [comment]
Solved with commit 8bc28bc645cabbdfb500d27d7df76e26da8384fc
