### ISSUE TITLE
JobRunr cache should be refreshed upon job configuration change.

### ISSUE THREAD

**Issue by sajawaji** [jobrunr/jobrunr#471]
As per V5.0.0, JobRunr uses cache to run recurring jobs(cache refreshed only when a job is deleted). This is causing issue when there is change in job configuration(e.g change in schedule or cron expression). The jobs are run as per old schedule instead of new schedule even after changing the schedule.
When the application is restarted it picks latest schedule. This is not desirable as we have multiple jobs and we can not restart our application for every change.

**Comment by rdehuyss** [comment]
This is already solved in master and will soon be released. See #460 .

**Comment by rdehuyss** [comment]
Please star the repo if you're happy with how fast issues are resolved ;-).
