### ISSUE TITLE
[BUG] JobRunr can not detect that JavaTimeModule is registered with ObjectMapper in a Spring Boot Application

### ISSUE THREAD

**Issue by cefalo-partha** [jobrunr/jobrunr#479]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
In our spring boot application, we'd like to use the standard Jackson `JavaTimeModule` to (de)serialize various temporal objects. However, even though the module is registered with the `ObjectMapper`, JobRunr thinks that it is not registered and registers its own `JobRunrTimeModule` which fails to work with various data types (e.g. `java.time.Instant`).

Looking at JobRunr code, it seems the problem is in `org.jobrunr.utils.mapper.jackson.JacksonJsonMapper#isJSR310JavaTimeModule`. It checks the `typeId` with the value `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule` but in reality, with spring boot `v2.6.7`, tye typeId is `jackson-datatype-jsr310`. Jackson version with spring boot is `2.13.2`.

We can work around this bug by providing our own `JacksonJsonMapper` subclass but it is a bit hacky. Would be great if this bug is fixed in JobRunr.

Thank your for all your great work!

**Environment**
I'm using JobRunr version: 5.1.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): JDK 17
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgres

**Comment by rdehuyss** [comment]
Hi, I just checked it and with me all works fine. With me, in a Spring Boot 2.6.6 project, the typeId is `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule`

See also the screenshot below.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/567842/171563587-7b4e415d-9e75-4f45-b4e4-3a1994bfbeba.png">

If you can create a github repo reproducing the issue, feel free to reopen.

**Comment by cefalo-partha** [comment]
Here is a screen of what I see with the attached demo project:
![Screenshot 2022-06-03 at 4 43 41 PM](https://user-images.githubusercontent.com/2785605/171839822-b6f0ffaa-2c75-485b-9c17-3f3ee513a57e.png)

Here is the demo project: 
[bug_demo.zip](https://github.com/jobrunr/jobrunr/files/8831756/bug_demo.zip)

**Comment by rdehuyss** [comment]
Sorry for my language but WTF?

**Comment by cefalo-partha** [comment]
:-)

I am not sure about this but the `typeId` value probably changed sometime around jackson `v2.12.x`. That might be the reason for this.

**Comment by cefalo-partha** [comment]
@rdehuyss : Thank you very much for the fix. This is yet another great experience with JobRunr.
