### ISSUE TITLE
[BUG] jobrunr 5x and Quarkus build via gradle @version problem

### ISSUE THREAD

**Issue by fwelland** [jobrunr/jobrunr#485]
Gradle/Quarkus Build,  Using:  

```
    implementation 'org.jobrunr:jobrunr:5.1.3'   
    implementation 'org.jobrunr:quarkus-jobrunr:5.1.3' 
```
I get errors like this: 

```Execution failed for task ':quarkusGenerateCode'.
> Could not resolve all dependencies for configuration ':quarkusProdRuntimeClasspathConfigurationDeployment'.
   > Could not find org.jobrunr:quarkus-jobrunr-deployment:@version.
     Searched in the following locations:
       - https://<blah>/org/jobrunr/quarkus-jobrunr-deployment/@version/quarkus-jobrunr-deployment-@version.pom
       - https://<blah>/org/jobrunr/quarkus-jobrunr-deployment/@version/quarkus-jobrunr-deployment-@version
     Required by:
         project 
```
This is the case for 5.1.2 and 5.0.0. 

When I pivot towards these deps: 

```    
    implementation 'org.jobrunr:jobrunr:4.0.10'
    implementation 'org.jobrunr:quarkus-jobrunr:4.0.10'
```
NOTE:   This doesn't change with version of quarkus;  I tried the 2.2.1.Final  (as per example) as well as, latest 2.9.2.Final ; behavior is same.     Something seems fishy with org.jobrunr:quarkus-jobrunr:5.x.x, perhaps?

**Comment by rdehuyss** [comment]
Please star the repo if you're happy with the swift issue resolution!

**Comment by fwelland** [comment]
cloned repo, and did:  

export DRONE_TAG=5.1.4-Snapshot
 ./gradlew clean build publishToMavenLocal -x test

And then used the following DEPS: 

    implementation 'org.jobrunr:jobrunr:5.1.4-Snapshot'
    implementation 'org.jobrunr:quarkus-jobrunr:5.1.4-Snapshot'


Built fine,  my app ran well too.    

Something went side ways with the /dashboard  (404's) ;  but I think that is un-related.  Flipping back to 4.0.10, /dashboard works again -- so maybe something I did wrong in build process that messed up the dashboard.       Can retry if/when official build/GAV becomes available. 

Thanks!!!

**Comment by rdehuyss** [comment]
If you follow the build instructions on the readme.md, the dashboard will work fine too.

This will probably be released somewhere next week.

**Comment by fwelland** [comment]
Yeah sorry just blasted a build via gradle  w/o reading the whole MD file.      

That said, and totally out of scope if the original issue -- so this maybe just fyi:    

(I am NOT a node guy)  -- but looks like the npm run build stuff is running afoul of openssl v3.    

NOTE:  I work on Fedora 36 (using distro provided stuff for node/npm/openssl) , so I got: 
```
$node --version
v16.14.0
$ npm -version
8.3.1
$openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

```
There is some 'noise' on the WWW about node + openssl v3.     About errors like this: 

```
 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
I get this when doing the npm run build step. 

Can totally wait for next official version to come in public MVN repos. 

Thanks again for help and solid tool -- may just be what I am looking for.
