### ISSUE TITLE
Error running database migration v013__alter_table_recurring_job_add_createdAt.sql [BUG]

### ISSUE THREAD

**Issue by vo-davydov** [jobrunr/jobrunr#489]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
An error occurs during migration installation `Caused by: java.lang.IllegalStateException: Error running database migration v013__alter_table_recurring_job_add_createdAt.sql` `ORA-30649: missing DIRECTORY keyword`

**Environment**
I'm using JobRunr version: 5.1.3
I'm running on JDK: 14
I'm using the following StorageProvider: Oracle

**How to Reproduce**
Try to install migration on oracle database

**Expected behavior**
Migration successfully installed on oracle

**Comment by rdehuyss** [comment]
Will be solved with the next release. Please star the repo if you're enjoying JobRunr and are happy with the support!
