### ISSUE TITLE
[Feature] Add a crash detection / auto restart option to the BackgroundJobServer

### ISSUE THREAD

**Issue by JanHolger** [jobrunr/jobrunr#498]
**Is your feature request related to a problem? Please describe.**
Since a certain JobRunr update we experienced random crashes of our job runr workers pretty much every few hours, probably because of some database connection errors but we didn't see any exceptions so we are not even sure why. We didn't expect this to happen so we only monitored the process but not the actual count of running workers so we didn't even notice the crash for 2 days until users reported issues with the application. Our temporary solution for this was to simply spin up a few dozen worker instances and replace the crashed ones every day.

Now we've seen that you provided a fix for allowing to restart a crashed server in the last release. This would allow us to implement a crash detection but as we are seemingly not the only one's having this issue (see #473) it might be a good idea to provide an auto restart solution in the library to make it more reliable.

**Describe the solution you'd like**
The simplest solution would be an option in the BackgroundJobServerConfiguration that restarts the server instead of stopping it, when it hits an unrecoverable situation.

**Describe alternatives you've considered**
Writing some code myself that runs in an extra thread and periodicly checks whether the server is still running to restart it when it crashes. I would need to manually add this to every project though and it would be quite a hacky solution.

**Comment by rdehuyss** [comment]
I'm afraid I won't do this - if your background job server dies for some reason, I want to know the root cause. If such an error happens, JobRunr also automatically suggests to create a GitHub issue in the dashboard normally so that I can find that root cause. Feel free to create an issue if you can provide me with the logs.

If your DB connection fails, that's an infrastructure problem on your side and I don't feel that the free version of JobRunr should solve that. There are companies running over 25.000.000 jobs per day with JobRunr without any problems.

If you're still a student or a startup, I'm also open to discuss pricing - feel free to reach out.

**Comment by SympathyForTheDev** [comment]
Hello @rdehuyss, sorry to come back on this closed issue. 
I ran in a similar issue when BackgroundJobServer died 
and maybe related to this discussion https://github.com/jobrunr/jobrunr/discussions/304

Let me give more details : 

I'm using lastest version of jobrunr with spring boot 2.7.2, deployed in container in AWS (one instance), using AWS RDS Aurora PostgreSQL.
(with one writer instance and one read only replica instance)

For some reason the AWS get network issue or what ever, so the RDS instance switch to another availability zone during few minutes the rds cluster was pointing over the read only replica, then it's get back into the writer instance.

During this time my application log many database exception (org.postgresql.util.PSQLException: ERROR: cannot execute UPDATE in a read-only transaction), after the failover my application successful get back alive but not the jobrunr background server.

Last log I get form the jobrunr background server : 

```2022-08-23T09:48:45.673Z	org.jobrunr.server.ServerZooKeeper: - An unrecoverable error occurred. Shutting server down...
        2022-08-23T09:48:45.673Z	web: org.jobrunr.storage.StorageException: org.postgresql.util.PSQLException: ERROR: cannot execute UPDATE in a read-only transaction
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java:89)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.ThreadSafeStorageProvider.signalBackgroundJobServerAlive(ThreadSafeStorageProvider.java:59)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAlive(ServerZooKeeper.java:94)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:77)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:49)
        2022-08-23T09:48:45.673Z  web: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        2022-08-23T09:48:45.673Z  web: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        2022-08-23T09:48:45.673Z  web: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        2022-08-23T09:48:45.673Z  web: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        2022-08-23T09:48:45.673Z  web: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        2022-08-23T09:48:45.673Z  web: at java.base/java.lang.Thread.run(Thread.java:829)
        2022-08-23T09:48:45.673Z  web: Caused by: org.postgresql.util.PSQLException: ERROR: cannot execute UPDATE in a read-only transaction
        2022-08-23T09:48:45.673Z  web: at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
        2022-08-23T09:48:45.673Z  web: at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:149)
        2022-08-23T09:48:45.673Z  web: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        2022-08-23T09:48:45.673Z  web: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:149)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:130)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.sql.common.BackgroundJobServerTable.signalServerAlive(BackgroundJobServerTable.java:61)
        2022-08-23T09:48:45.673Z  web: at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java:85)
        2022-08-23T09:48:45.923Z  web: ... 10 common frames omitted



 2022-08-23 09:48:45 org.jobrunr.server.BackgroundJobServer:  BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
```

background server stay in this state in the database : 
```
id	workerpoolsize	pollintervalinseconds	firstheartbeat	lastheartbeat	running	systemtotalmemory	systemfreememory	systemcpuload	processmaxmemory	processfreememory	processallocatedmemory	processcpuload	deletesucceededjobsafter	permanentlydeletejobsafter
a3a41208-40e0-45bf-8b02-cc81b56ff3ff	16	15	2022-08-22 16:24:01.367476	2022-08-23 09:48:10.528761	1	4121407488	151552000	0.02	1031798784	348138824	683659960	0.02	PT36H	PT72H
```

after that if I create a new job in my application, it's stay in 'SCHEDULED' state indefinitely and the job is not processed.


So my question, how I can restart my backgroundjobServer without restarting my spring boot application (I don't have the jobrunr dashboard in production environment) ?

Maybe you can add the ability to configure an automatic attempt to recover the  backgroundjobServer after an amount of time ?
Or maybe when jobrunr is scheduling a new job, it could be possible to check and recover the backgroundjobServer ?
what do you think ?

**Comment by rdehuyss** [comment]
Well, all the things you're asking for, are available in the Pro version. 

Opensource doesn't mean free - in this case the cost is you having to restart the cluster. If this cost is too high, feel free to take a Pro license.

**Comment by SympathyForTheDev** [comment]
I didn't know this feature was available in the pro version, thank you  very much for your work

**Comment by JanHolger** [comment]
> Well, all the things you're asking for, are available in the Pro version.

If that's the case we definitely had a lot of miscommunication. Like I already told you, we would be happily paying you because this is not our own business case but is an essential part of our application. My boss was happy with buying the Pro version and we were already kind of sold. If the Pro version would have reliably fixed those silent crashes we would have instantly bought it but all communication from your side didn't sound like it actually solves the silent crashes and instead of making it more reliable to crashes you wanted to solve the root causes. And I definitely agree that the root causes should be fixed aswell but reliability is the most important factor for us and probably any user. We don't care if the worker processes crash a couple times a day as long as they don't silently die without any notice and without any way to implement automatic recovery. That's the reason we created the fork as a temporary solution and are now in the process of switching to an alternative.

> Opensource doesn't mean free - in this case the cost is you having to restart the cluster. If this cost is too high, feel free to take a Pro license.

I 100% agree that opensource doens't mean free and especially it doesn't mean you receive free support. And if it solves a problem I'm a big fan of giving something back, that's why I also started sponsoring you even though I didn't even actively use JobRunr at that time and when we started using it in the company I convinced my boss that we need the Pro version. What I don't agree on is that software should be purposely broken to sell a paid version or at least that should be properly communicated. We spent quite some time learning and implementing your library, just to now find out that we need to find an alternative because you are "wont-fix"ing issues that are essential to us and even other users. If the communication is "buy Pro to have reliability and auto-restarts", "buy Pro to be able to use intervals smaller than 5 sec", etc. we would've been happy customers but this way you just made us doubt more and more whether it's a good idea to invest in your product.

We also noticed that the german translation of the website is pretty outdated and even the pricing table is different. Maybe it's better to remove the translation and let Google translator make it's job to ensure all information are correct and up to date.

For the sake of clarification for people falling over this in the future, can you clarify what the Pro version includes/solves regarding this issue?

**Comment by rdehuyss** [comment]
Hi @JanHolger ,

I'm not completely following to be honest. I take each issue seriously and try to fix it as soon as possible. Most issues are solved within a week (except for issue 448 which is a difficult one). So, your comment about me 'won't-fixing' issues hurts my feelings to be honest.

Database fault tolerance is something I've never needed myself (we run Kubernetes clusters on premise and we did not have any connection issues at all). That's why I decided to put this feature in the pro version.

Intervals smaller than 5 seconds are also not a must have in my eyes. Performance wise, it's also not a good idea but in JobRunr Pro you have instant job processing (implemented in a much better way).

The complete list with JobRunr Pro features has always been available on the website and the database fault tolerance is a reason why some companies go for the Pro version.

All the features of JobRunr Pro are listed here: https://www.jobrunr.io/en/documentation/pro/.
Is there something not clear about this?

**Comment by SympathyForTheDev** [comment]
IMHO it's totally fair to have "prod/battle ready" features in the pro version.
I can confirm in some other projects (big client with big load) I already used jobrunr inside k8s cluster and never get this kind of issues.

So for my current setup with only one instance (with one BackgroundJobServer, no k8s cluster and a cheap database support) at the moment it doesn't make sense to have pro version.

So I did the following work around, which is good enough at the moment, then if I need something more fault tolerant, I will go for k8s or jobrunr pro :


```
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jobrunr.jobs.lambdas.JobLambda;
import org.jobrunr.scheduling.JobScheduler;
import org.jobrunr.server.BackgroundJobServer;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;


@Slf4j
@Service
@RequiredArgsConstructor
public class JobSchedulerAdapter {

    private final JobScheduler jobScheduler;
    private final BackgroundJobServer backgroundJobServer;

    private static final Duration JOB_SERVER_STALE_LIMIT_DURATION = Duration.ofMinutes(15);

    public void schedule(final UUID jobId, final Instant scheduledAt, final JobLambda job) {
        try {
            checkBackgroundServerRunning();
            jobScheduler.schedule(jobId, scheduledAt, job);
        } catch (final Exception e) {
            LOG.error("Unable to schedule job with jobId {}", jobId, e);
            throw e;
        }
    }

    private void checkBackgroundServerRunning() {
        if (!backgroundJobServer.isRunning()) {
            LOG.error("JobRunr background server is not running since {}", backgroundJobServer.getServerStatus().getLastHeartbeat());
            if (backgroundJobServer.getServerStatus().getLastHeartbeat().isBefore(Instant.now().plus(JOB_SERVER_STALE_LIMIT_DURATION))) {
                LOG.warn("Look like JobRunr background server is not running and stuck for a while, try to restart ...");
                backgroundJobServer.start();
            }
        }
    }

    public void delete(final UUID jobId, final String reason) {
        try {
            checkBackgroundServerRunning();
            jobScheduler.delete(jobId, reason);
        } catch (final Exception e) {
            LOG.error("Unable to delete scheduled job with id {}", jobId, e);
        }
    }


}

import lombok.extern.slf4j.Slf4j;
import org.jobrunr.jobs.JobId;
import org.jobrunr.jobs.lambdas.JobLambda;
import org.jobrunr.scheduling.JobScheduler;
import org.jobrunr.server.BackgroundJobServer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.time.Instant;
import java.util.UUID;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
@ExtendWith(SpringExtension.class)
@Slf4j
class JobSchedulerAdapterTest {

    @Mock
    private JobScheduler jobScheduler;
    @Mock
    private BackgroundJobServer backgroundJobServer;

    @InjectMocks
    private JobSchedulerAdapter jobSchedulerAdapter;

    @Test
    void test_schedule() {

        final var jobId = UUID.randomUUID();
        final var scheduledAt = Instant.now();
        final JobLambda job = () -> LOG.info("JOB EXECUTION!");

        when(backgroundJobServer.isRunning()).thenReturn(true);
        when(jobScheduler.schedule(jobId, scheduledAt, job)).thenReturn(new JobId(UUID.randomUUID()));

        jobSchedulerAdapter.schedule(jobId, scheduledAt, job);

        verify(backgroundJobServer).isRunning();
        verify(jobScheduler).schedule(jobId, scheduledAt, job);
    }

    @Test
    void test_delete() {

        final var jobId = UUID.randomUUID();
        final var reason = "delete reason";

        when(backgroundJobServer.isRunning()).thenReturn(true);

        jobSchedulerAdapter.delete(jobId, reason);

        verify(backgroundJobServer).isRunning();
        verify(jobScheduler).delete(jobId, reason);
    }

```

**Comment by JanHolger** [comment]
> Hi @JanHolger ,
> 
> I'm not completely following to be honest. I take each issue seriously and try to fix it as soon as possible. Most issues are solved within a week (except for issue 448 which is a difficult one). So, your comment about me 'won't-fixing' issues hurts my feelings to be honest.

From what we've seen you are fixing issues as long as they meet your ideas and requirements to the software and that's totally fine since it's your project and your decision what you want to address. If you are closing issues because you don't think that a certain issue or feature should be addressed that's your decision and we as a user need to live with it. But for us as a company this means that we can't rely on you and yes this might be better with the Pro version but from the conversations we had and the quite aggressive reaction to our fork, we simply don't have the trust in you anymore so we decided to go for an alternative. 

I definitely don't want to intentionally hurt your feelings and even though it might not look like it, i'm still really thankful for all the work that you put into JobRunr. I'm just being honest about my opinion and I might even be the idiot in this case 😄

> Database fault tolerance is something I've never needed myself (we run Kubernetes clusters on premise and we did not have any connection issues at all). That's why I decided to put this feature in the pro version.

The database connection issues are coming from our pretty unstable non-prod db setup. It also runs on on-prem k8s but backed by NFS mounted storage that sometimes looses connection because we don't have proper storage setup in the dev cluster. Those are problems that we need to solve ourselves but this issue wasn't just about database related issues.

> Intervals smaller than 5 seconds are also not a must have in my eyes. Performance wise, it's also not a good idea but in JobRunr Pro you have instant job processing (implemented in a much better way).

That's fixed with the pro version now and that's totally fine but it wasn't back at the time when me and quite a few other people were asking for a smaller interval, even if it would have been "do it on your own risk". 

> The complete list with JobRunr Pro features has always been available on the website and the database fault tolerance is a reason why some companies go for the Pro version.
> 
> All the features of JobRunr Pro are listed here: https://www.jobrunr.io/en/documentation/pro/. Is there something not clear about this?

The german translation (https://www.jobrunr.io/de/documentation/pro/) was pretty outdated so it wasn't even listed there but you already removed the language selector as far as I can see so that's fixed now.

Our main problem is that even if database crashes are fixed, what happens if something else goes wrong? I don't remember exactly but wouldn't the background server shut down silently in this case aswell? If that's the case, is there something in the Pro version that would prevent that or allow detection of such events?

**Comment by rdehuyss** [comment]
Detection of BackgroundJobServer stops has always been available in the Pro and Free version since JobRunr 4.0 using Health checks.

**Comment by alamos-gmbh** [comment]
> private void checkBackgroundServerRunning() {
>         if (!backgroundJobServer.isRunning()) {
>             LOG.error("JobRunr background server is not running since {}", backgroundJobServer.getServerStatus().getLastHeartbeat());
>             if (backgroundJobServer.getServerStatus().getLastHeartbeat().isBefore(Instant.now().plus(JOB_SERVER_STALE_LIMIT_DURATION))) {
>                 LOG.warn("Look like JobRunr background server is not running and stuck for a while, try to restart ...");
>                 backgroundJobServer.start();
>             }
>         }
>     }

Must be Instant.now().minus, otherwise always true

You want the heartbeat to be older than now minus a certain amount of time, right?

**Comment by AndrewBedscastle** [comment]
I agree.
Buying the PRO license for all our applications would cost more than our annual revenue.
So this is impossible.

**Comment by rdehuyss** [comment]
> I agree. Buying the PRO license for all our applications would cost more than our annual revenue. So this is impossible.

@AndrewBedscastle - the enterprise license is cheaper than you think (about 4 times the business license) and allows unlimited use off JobRunr within your organization.

**Comment by jamesfredley** [comment]
For Spring Boot apps with Spring Boot Actuator, using `/actuator/health` as your health check endpoint will allow you to detect  issues with BackgroundJobServer and have your environment restart the impacted instances.
