### ISSUE TITLE
WANTED: who is using JobRunr?

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#5]
# Who is Using JobRunr
First of all, thanks sincerely for using and supporting JobRunr. I will try my best to make JobRunr better, and keep the community and eco-system growing.

## The purpose of this issue
- I’d like to listen to the community to make JobRunr better.
- I'm willing to learn more JobRunr use-case scenarios from the field for better planning.

## What I expect from you
Pls. submit a comment in this issue and include the following information:

- your company, school or organization.
- your city and country.
- your contact info: blog, email, twitter (at least one).
- for what business scenario do you use JobRunr

You can refer to the following sample answer for the format:
```
* Organization: Rosoco
* Location: Leuven, Belgium
* Contact: ronald.dehuysser@gmail.com
* Purpose: used as cornerstone in a distributed service architecture for generating a large amount of documents.
```

Thanks again for your participation !

**Comment by plosson** [comment]
* Organization: Docunit
* Location: Brussels, Belgium
* Contact: plosson@docunit.be
* Purpose: Used (in the future) to generate reports in background and send them by email.

**Comment by dawuzi** [comment]
The project seems to contain only gradle config files. No maven support ?

**Comment by rdehuyss** [comment]
Hi @dawuzi - there is definitely maven support! I just build using Gradle. Maven support is explained in the [Readme](https://github.com/jobrunr/jobrunr/blob/master/README.md) and there is an example project using [Maven](https://github.com/jobrunr/example-spring)

**Comment by dawuzi** [comment]
@rdehuyss I saw that maven dependency in the read me. I am talking about contribution and building the project itself. I couldn't find a pom.xml in the project. Did I miss it ?

**Comment by rdehuyss** [comment]
@dawuzi just import the project as a Gradle project in IDEA and you should be up & running.

**Comment by dawuzi** [comment]
@rdehuyss But I neither use gradle nor IDEA except when I have to work on an android project where is more or less compulosory. You really should add maven support for building. The last time I (or most other Java devs I know) used any other build except Maven was years back. Its more or less the de factor build tool now for Java apps

**Comment by rdehuyss** [comment]
Well it's all a matter of taste, isn't it? Biggest plus for me is build speed where Gradle is sometimes (depending on build cache) 20 times faster. 
For the projects I mostly work on, I tend to advise Gradle more and more...

**Comment by dawuzi** [comment]
_"Still, I don't understand why it is an issue"_. Well, In your own words : "_it's all a matter of taste, isn't it?_" . 

I really think it will be beneficial to a lot of developers if you add it though

**Comment by plosson** [comment]
I have to agree on that one. Maven is the mainstream standard.

Le mer. 8 juil. 2020 à 23:52, Okafor Ezewuzie <notifications@github.com> a
écrit :

**Comment by ChristianCiach** [comment]
Who cares which build tool is being used here? As a consumer of the library it doesn't matter to you anyway. Gradle is absolutely fine and there is no reason to "go back" to Maven.

**Comment by plosson** [comment]
Indeed but if you choose to open source and encourage will contribution it
might make sense

Le lun. 27 juil. 2020 à 19:43, ChristianCiach <notifications@github.com> a
écrit :

**Comment by ChristianCiach** [comment]
> Indeed but if you choose to open source and encourage will contribution it might make sense 

I disagree. I know tons of hugely successful open source projects that have switched to Gradle and there is no shortage of contributions (Spring Boot, Hibernate ORM...).

Personally, I prefer Gradle over Maven, but I happily contribute to projects that use whichever build tool. If you (not personally you, but speaking generally) are able to contribute to Maven projects but struggle to contribute to Gradle projects (or Ant or Bazel or whatever), then I would question your ability to provide anything of quality anyway.

**Comment by plosson** [comment]
Seems you have a made up mind. No need for me to comment here.
Cheers :-)

**Comment by rdehuyss** [comment]
Ok, I'm going to close this issue as it is going totally off-topic.

The goal was to collect some info from people who are using JobRunr. I'll need to find another way :-).

Thanks to all for your input!
