### ISSUE TITLE
[BUG] Unit Test Coverage issue for Job Lambda

### ISSUE THREAD

**Issue by aashishgoyal2000** [jobrunr/jobrunr#500]
I am scheduling a job something like this. 

jobScheduler.scheduleRecurrently("Job Name", "Cron Time", () -> invokeFuncFromFunctionName("Function Details"));

    public void invokeFuncFromFunctionName(FunctionClass function) {
        try {
            Class<?> classs = Class.forName(this.getClass().getName());
            Method method = classs.getDeclaredMethod(function.getFunctionName());
            method.invoke(this);
        }
        catch (Exception e) {
            throw new NotFoundException("Method not found " + function.getFunctionName());
        }
    }

I am not able to write a unit test in which invokeFuncFromFunctionName() is invoked. Logs specifically mention that there is no unit test for lambda part of scheduleRecurrently function call.

I have tried mocking scheduleRecurrently, but it still expects a unit test for job lambda.

**Comment by rdehuyss** [comment]
This is indeed not possible as JobRunr is async by default. You can use a Mockito `ArgumentCaptor` to capture the lambda and do verification.
