### ISSUE TITLE
[Feature] [Dashboard] Optimize Job Listing screen loading time

### ISSUE THREAD

**Issue by jmrsnt** [jobrunr/jobrunr#507]
**Is your feature request related to a problem? Please describe.**

With DataStorage ORACLE, I noticed that the job listing screen takes a long time to load, probably due to the inclusion of the JOBASJSON column in the request that returns the Jobs list.

![](https://i.imgur.com/MCS8Jdz.png)

**Describe the solution you'd like**

Wouldn't it be interesting to create a column to save the "Job details" information, which is used in the listing screen, and not return JOBASJSON in this request, as this information is not used in the listing screen.

**Comment by jmrsnt** [comment]
Actually I don't know if the loading delay is due to the JOBASJSON column, I'm just speculating, let me know if I'm wrong

**Comment by rdehuyss** [comment]
That's really strange. What is the size of the response (I could not find it on your screen).

Normally, this is less than 1sec (and mostly something like 200ms).

**Comment by jmrsnt** [comment]
@rdehuyss the size of response is 152MB

**Comment by rdehuyss** [comment]
Well, you're doing a lot of logging :-). I would expect the result size to not be bigger than 20MB (and even that is way too much in my eyes).

**Comment by rdehuyss** [comment]
Can you send me the response somehow (pastbin, wetransfer)?

**Comment by rdehuyss** [comment]
Hi @jmrsnt : did you find out why the response is so large?
