### ISSUE TITLE
Cannot run on CockroachDB

### ISSUE THREAD

**Issue by z0mb1ek** [jobrunr/jobrunr#508]
Hi, I cannot run migrations on CockroachDB

> Caused by: org.postgresql.util.PSQLException: ERROR: at or near "(": syntax error
  Detail: source SQL:
CREATE TABLE jobrunr_migrations
(
    id          nchar(36) PRIMARY KEY,
                           ^

does postgresql support nchar type?

**Comment by rdehuyss** [comment]
There are more than 200 tests that say Postgres supports nchar :-).

No where on the JobRunr website it is mentioned that CockroachDB is supported. Feel free to contact me for a Pro version where paid feature development happens.
