### ISSUE TITLE
[BUG] VFS FileSystem isn't supported

### ISSUE THREAD

**Issue by dhyegocalota** [jobrunr/jobrunr#509]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
I got the error `Unknown FileSystem required vfs` while JobRunr tried to load the Migrations folder.
![image](https://user-images.githubusercontent.com/5576007/177797247-453270e2-91c4-4e0f-8a97-95e61af608c9.png)

Apparently, the Thorntail (JBoss) framework uses the VFS filesystem but JobRunr doesn't support it.
![image](https://user-images.githubusercontent.com/5576007/177797580-bfeead2f-7730-4d33-9be1-8b281098bd27.png)

**Environment**
I'm using JobRunr version: 5.1.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): Temarin8 `javac 1.8.0_322`
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgres
I'm using Thorntail version: 2.7.0.Final

**How to Reproduce**
I initialized the JobRunr within an ApplicationScoped instance:

```java
@ApplicationScoped
public class JobRunrWorkerService {

  @Resource
  private DataSource dataSource;

  void init(@Observes @Initialized(ApplicationScoped.class) Object event) throws InterruptedException {
    initJobRunr();
  }

  public JobRunrConfiguration.JobRunrConfigurationResult initJobRunr() {
    return JobRunr.configure()
      .useStorageProvider(SqlStorageProviderFactory.using(dataSource))
      // .useStorageProvider(new InMemoryStorageProvider()) // ← InMemory Storage works just fine because it doesn't need to locate the database migrations folder
      .useBackgroundJobServer()
      .useDashboard()
      .initialize();
  }
}
```

**Expected behavior**
I expected that JobRunr could locate the migrations folder just fine using the VFS filesystem.

**Comment by rdehuyss** [comment]
Thorntail is end of life.

JobRunr will not add support for things that are end of life.

**Comment by dhyegocalota** [comment]
Got it. I mentioned Thorntail to give more context, but this is specific about the VFS library isn't it? Thank you for the quick answer!
