### ISSUE TITLE
[BUG] Elasticsearch: no more than 10 recurring jobs supported

### ISSUE THREAD

**Issue by jloisel** [jobrunr/jobrunr#510]
JobRunr 5.1.4, issue is pretty simple in https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/storage/nosql/elasticsearch/ElasticSearchStorageProvider.java:

```java
@Override
    public RecurringJobsResult getRecurringJobs() {
        try {
            SearchRequest searchRequest = new SearchRequest(recurringJobIndexName);
            SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
            searchSourceBuilder.query(matchAllQuery());
            searchSourceBuilder.storedField(RecurringJobs.FIELD_JOB_AS_JSON);
            searchRequest.source(searchSourceBuilder);
            SearchResponse search = client.search(searchRequest, RequestOptions.DEFAULT);
            List<RecurringJob> recurringJobs = Stream.of(search.getHits().getHits())
                    .map(elasticSearchDocumentMapper::toRecurringJob)
                    .collect(toList());
            return new RecurringJobsResult(recurringJobs);
        } catch (IOException e) {
            throw new StorageException(e);
        }
    }
```

If you don't specify any size here, the default size is 10. If you have more than 10 recurring jobs, Jobrunr simply won't see them.

**Comment by jloisel** [comment]
Besides, a search is limited to max 10.000 results.

**Comment by jloisel** [comment]
Same issue for: (10 max)

- `public List<BackgroundJobServerStatus> getBackgroundJobServers()`,
- `public Set<String> getDistinctJobSignatures(StateName... states)`,
- `public JobStats getJobStats()`.

**Comment by jloisel** [comment]
Is there any possible release date?

**Comment by rdehuyss** [comment]
Somewhere next week. Feel free to star the repo!
