### ISSUE TITLE
problem with flyway jobrunr table mysql scripts[BUG]

### ISSUE THREAD

**Issue by benbowles** [jobrunr/jobrunr#517]
**Are you running the latest version of JobRunr?**
YES
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**

I am using the new functionality that allows me to incorporate table creations into flyway. I wanted to use this with org.jobrunr.database.skip-create=true to ensure that flyway only creates the tables. However, jobrunr gives me an error at a validation step saying ": Factory method 'sqlStorageProvider' threw exception; nested exception is org.jobrunr.JobRunrException: Not all required tables are available by JobRunr!"

Is there a workaround @rdehuyss  ?? thank you

**Environment**
I'm using JobRunr version: <your JobRunr version>
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): <your jre/jdk version> 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): <your storageprovider> 

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
BackgroundJob.enqueue(() -> service.helpMe());
```

**Expected behavior**

**Additional context**

**Comment by rdehuyss** [comment]
Please complete all the requested questions and provide a simple example project. Then I'll have a look.
