### ISSUE TITLE
Recurring job: having a node assignement process for reccuring job instead of lock for every execution

### ISSUE THREAD

**Issue by w3blogfr** [jobrunr/jobrunr#533]
**Is your feature request related to a problem? Please describe.**

I would trigger a task every 5 seconds, and I'm worry about the charge on the Storage.

In my process, I would say my task could be re-execute multiple time. I would just try to avoid, but it would not be a big problem if sometime it happens. When I have 3 or 4 instances running, I would have only one single instance that do the job.

In the ticket #105, you menetion that each job execution trigger at least 6 calls.

Here is your explanation

- every 15 seconds the BackgroundJobServer checks if there are new recurring jobs to execute
- if there is one to execute, it schedules the job to be executed at the correct time (which is a state change and saved to the database)
- from scheduled, the job goes to enqueued (which is a state change and saved to the database).
- as there may be many (more than 10) BackgroundjobServers trying to execute all enqueued jobs, these all would need to check the StorageProvider each second where as they now do it only every 15 seconds.
- as soon as a BackgroundjobServer is idle, it starts processing enqueued jobs and changes the state to 'Processing' (which is a state change and also saved to the database). This is done because otherwise multiple BackgroundjobServers would execute the same job around the same time, which is something you typically don't want.
- As soon as the job is finished, it is again a state change and saved to the database again.

**Describe the solution you'd like**

In my mind, as the task is recurring, I wondering if it's not possible to have a kind of election for jobs. Something like, "ok, this node will manage this job and will trigger every x seconds until there a failure".
In case of failure, another BackgroundJobServer will be assigned to that job, and will manage it. 
With that behavior, we may avoid few call that are only here to see if there is a job to execute or not.

Another way to explain this.

if recurring task duration is lower than poll-interval-in-second, BackgroundJobServer  could take care of all the execution during the poll-interval-in-second.
Exemple: 
with a poll-interval-in-second of 15 seconds, and a job that should be executed every 5 second, BackgroundJobServer execute 3 time the job before to poll again

With the way JobRunR is developped today, I don't have the feeling that behavior is possible, right? Which solution or alternative do you recommend?

Regards

**Comment by rdehuyss** [comment]
Well, JobRunr is now battle-tested and works well with a pollIntervalInSeconds of 5. There are companies processing 25.000.000 jobs a day on a postgres server. But again, it was originally developed for long-running tasks. 

The solution you propose may work but is not something I'm currently considering to add to JobRunr.

Regarding solutions or alternatives: no idea - I personally don't have a need for it thus did not search for it yet.

**Comment by w3blogfr** [comment]
I finally found a solution for that specific scenario.

As you mention, jobRunr has been designed for a long-running task, so I create one jobrunr job executed every 10 minutes and inside the job, I'm doing a classic java loop for 10 minutes, and manage the tempo with a Thread.sleep.

In that way, jobRunR allow me to trigger instance on only 1 server (that was my original need), every 10 minutes, may jobRunR can switch to another server. If server crash, jobRunR rerun the task on another server.

Fortunatly, i have only one task with this kind of complex behavior, others task much more match with the original purpose of jobRunR.

Thanks
