### ISSUE TITLE
[Feature] Show detailed timestamps for job state transitions on dashboard

### ISSUE THREAD

**Issue by dmurphy-ambra** [jobrunr/jobrunr#540]
**Is your feature request related to a problem? Please describe.**
The Jobrunr dashboard shows the duration since a job state occurred, but not the actual timestamp.  For example, job enqueued "2 hours ago".  When troubleshooting jobs that executed at around the same time, this makes it very difficult to see the exact sequence in which jobs executed.  The sequence can be relevant if you are trying to debug a race condition or to track interactions across different services. The only way to see this level of detail is to directly query the storage provider.

![image](https://user-images.githubusercontent.com/82825614/185439722-10db8226-1e0d-4fe2-b74a-97ca3b0bcdf6.png)

**Describe the solution you'd like**
Show the timestamps associated with job states and transitions

**Describe alternatives you've considered**
Querying the storage provider directly

**Comment by rdehuyss** [comment]
Hi @dmurphy-ambra - If you hoover over these dates, it will show you the exact timestamp.

**Comment by dmurphy-ambra** [comment]
The tooltip is useful, but for debugging, you need something that doesn't require a mouse action. I still think the interface here can be improved to provide more "at a glance information".  For example, so I could compare two jobs side by side.
