### ISSUE TITLE
[Feature] More seamless Spring support

### ISSUE THREAD

**Issue by JanecekPetr** [jobrunr/jobrunr#547]
### Is your feature request related to a problem? Please describe.
It's very surprising to see that `jobrunr-spring-boot-starter` does not just use whatever `RedisConnectionFactory` and/or `RedisTemplate` is available, but instead requires an explicit `RedisClient` (with Lettuce) or `JedisPool` (with Jedis). The big difference is that the first two types are coming from Spring and are autoconfigured, so they'll always be there if Spring and Redis are there. The two latter types are specific to Lettuce and Jedis client libraries, are not autoconfigured and need to be manually provided. This sucks because
1. We're using Lettuce, but we do not use ANY Lettuce types because Spring abstracts over them. Now we have to look into the library and understand it at least a little.
2. The client creation is actually trickier than it looks. We need to manually care whether the Redis instance is standalone, Cluster or Sentinel, whether it has a username or password or both - and each of these options is slightly different. We know because we got them wrong the first time. Normally Spring provides all this and gets it right.
3. Speaking of Cluster (#546) and Sentinel, Spring abstracts over those, too. Therefore using a Spring client automagically gives us Cluster and Sentinel support (but obviously still no transactions...). We currently do not have at least one of those.

### Describe the solution you'd like
We'd like to see the starter to pick up the autoconfigured `RedisConnectionFactory` and/or `RedisTemplate` and use them as its connection strategy. This would also solve #546, at least for Spring projects.

Whoever uses the starter will have the beans available. If their projects currently declare `RedisClient` and they're not using it for anything else other than JobRunr (as we do), those extra beans can be removed from the projects.
However, there is a problem with projects who use Jedis or Lettuce, but no Spring. For them the current functionality (`LettuceStorageProvider` and `JedisStorageProvider`) still need to stay.

### Describe alternatives you've considered
It might also be possible for `jobrunr-spring-boot-starter` to autoconfigure the `RedisClient` / `RedisClusterClient` / `JedisPool` / `JedisCluster` if they're missing. This is probably much easier to do than to develop a whole new connection strategy, but I feel it's not JobRunr's job to autoconfigure DB clients...

### Additional context
N/A

**Comment by rdehuyss** [comment]
Closing as JobRunr 7 will be the last version that will support Redis.

We will deprecate the `RedisStorageProvider` with the release of v7.
