### ISSUE TITLE
[Feature] Initial delay for recurring jobs

### ISSUE THREAD

**Issue by JanecekPetr** [jobrunr/jobrunr#548]
### Is your feature request related to a problem? Please describe.
I'm scheduling a recurring a job with a period of 3 hours which means that the first occurrence will run in 3 hours. Now, I'd also like the job to run almost immediately after start of the application, let's say after 5 minutes. The current API does not easily allow this. The naive "just schedule the task in 5 minutes and also schedule the recurring one with the period of 3 hours" fails when the application has multiple nodes that come and go, every node would schedule the one in 5 minutes unnecessarily. I only want the job to run once when the system starts up, then recurrently.

I eventually found a way to achieve this: Schedule a one-time job in 5 minutes to register the job recurringly and run the actual job once. Both the one-time job and the recurring job must have the same ID. This _feels_ fragile, although it should work (untested yet). It took a while to come up with this scheme.

### Describe the solution you'd like
Not sure. A naive solution is a `ScheduledExecutorService`-like parameter `Duration initialDelay` to `scheduleRecurring()` which would specify the first run of the job. This kinda explodes the API, though.

### Describe alternatives you've considered
Use task chaining from the Pro version. I think this does not work because the chain does not allow recurrent scheduling. Maybe the new API could be there.
Use waiting for the task result from the Pro version (or poll something somewhere). This works, but feels nasty.

### Additional context
N/A

**Comment by rdehuyss** [comment]
Some feedback:
- in JobRunr Pro we're adding the possibility to implement your own schedule so you would have complete control on when a `RecurringJob` would run.
- I am not going to add the initial delay as I think there is not enough interest in this feature that warrants the extra complexity it might add. It could however easily be done with the solution above.

Also, there is an easy workaround (create a scheduled job and a recurring job).
