### ISSUE TITLE
[Feature] Index on table jobrunr_jobs

### ISSUE THREAD

**Issue by samuelpisa** [jobrunr/jobrunr#561]
**Is your feature request related to a problem? Please describe.**
I've been using JobRunr for a few weeks with MySQL 5.7.
When the database was with 1M jobs scheduled and 100K enqueued, this query started to be very slow, taking many seconds to execute.
`select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 3 OFFSET 0;`

**Describe the solution you'd like**
My solution was to create a composite index with columns state and updatedAt.
`alter table jobrunr_jobs add index jobrunr_jobs_state_updated_idx(state, updatedAt)`
That solved the problem and the throughput is high again

Could this index be by default in the database migrations?

**Additional context**
JobRunr Version: 5.1.7
Mysql: 5.7
OpenJDK: 11
JobServer Master: 3
Thread Workers: 3

**Comment by rdehuyss** [comment]
Hi @samuelpisa ,

I just did some query analysis but the results from the mysql query analyser are different than what I would think based on your description.

I made sure to have enough jobs in the DB:
```
select count(*) from jobrunr_jobs;

`count(*)`
1430000
```

# MySQL 8
I use the query you mentioned (this is on MySQL 8) for analysis:
```
explain analyze select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0;
```

Each time I ran the analysis, I first made sure to run the query 10 times so the analyser can optimise it.

## Without your index, the output is as follows:
```
-> Limit: 1000 row(s)  (cost=198.11 rows=1000) (actual time=0.026..1.913 rows=1000 loops=1)
    -> Filter: (jobrunr_jobs.state = 'ENQUEUED')  (cost=198.11 rows=1000) (actual time=0.025..1.859 rows=1000 loops=1)
        -> Index scan on jobrunr_jobs using jobrunr_job_updated_at_idx  (cost=198.11 rows=2000) (actual time=0.023..1.726 rows=1000 loops=1)
```


| Duration | Query |
| ------------- | ------------- |
| 0.0087595 | /* ApplicationName=IntelliJ IDEA 2022.2.1 */ select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0 |

## With the newly added index, the output is as follows:
```
-> Limit: 1000 row(s)  (cost=182009.76 rows=1000) (actual time=0.024..1.973 rows=1000 loops=1)
    -> Index lookup on jobrunr_jobs using jobrunr_jobs_state_updated_idx (state='ENQUEUED')  (cost=182009.76 rows=609310) (actual time=0.023..1.917 rows=1000 loops=1)
```

| Duration | Query |
| ------------- | ------------- |
| 0.007083 | /* ApplicationName=IntelliJ IDEA 2022.2.1 */ select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0 |


What I find strange is that the cost of the query is a multitude of the original query (182009.76 vs 198.11)



# MySQL 5.7 (latest)
Tree analysis is unavailable. 

## Without your index:
| Duration | Query |
| ------------- | ------------- |
| 0.02523075 | /* ApplicationName=IntelliJ IDEA 2022.2.1 */ select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0 |

## With the newly added index:
| Duration | Query |
| ------------- | ------------- |
| 0.02436675 | /* ApplicationName=IntelliJ IDEA 2022.2.1 */ select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0 |

# Conclusion:
I'm by no means a MySQL (or even a SQL expert) but this does reveal some other insights:
- MySQL 8 is almost 10 times faster than MySQL 5.7
- Currently, I don't see a lot of difference with the extra index added

**Comment by rdehuyss** [comment]
Could you do some testing (especially profiling) with and without the query on your side?

To get the duration result from the query, I use:

```
set profiling = 1;

select jobAsJson from jobrunr_jobs where state = 'ENQUEUED' ORDER BY updatedAt ASC LIMIT 1000 OFFSET 0; -- I run this query 10 times

show profiles ;
```

**Comment by rdehuyss** [comment]
I also measured this in Postgres and there the new index indeed helps. I assume the MySQL analyser is wrong in analysis.

This has now been added in commit 949f62d382f750d5b1.
