### ISSUE TITLE
[BUG] Why recurring jobs are limited to 5000 even for JobRunr Platinum?

### ISSUE THREAD

**Issue by mikekay68** [jobrunr/jobrunr#562]
**Are you running the latest version of JobRunr?**
Yes / No
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
We have to reschedule single jobs every time we run them due to this limitation. 5000 recurring jobs is not enough for us(currently in our pilot we have 15000 jobs running already and there will be lot more), Is there any plans not to have limit on recurring jobs?

**Environment**
I'm using JobRunr version: 5.1.6
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): JDK 11
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Oracle 

**How to Reproduce**
Nothing to reproduce. We've got information about limited recurring jobs here https://www.jobrunr.io/en/pricing/

```

**Expected behavior**
We expected that JobRunr won't have such limitations on recurring jobs.

**Comment by rdehuyss** [comment]
JobRunr was originally only designed for 10 to 20 recurring jobs. As some Pro customers were using it heavily for a lot of recurring jobs, the code was optimized and I tested up to 5000 recurring jobs. More could work but was not yet tested (this is planned in Q4).

Feel free to reach out via email if you're considering a Pro license - there may be other ways to solve your problem.
