### ISSUE TITLE
Spring applications using spring-context-indexer are unable to register jobs via @Recurring

### ISSUE THREAD

**Issue by william00179** [jobrunr/jobrunr#563]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
We have just upgraded JobRunr and noticed that new jobs stopped being registered via the `@Recurring` annotation.

Related to #513

When using `spring-context-indexer` jobs will not be detected as the `@Component` in the library won't be part of the index. Manually registering the `RecurringJobPostProcessor` as a bean resolves the issue.

**Environment**
I'm using JobRunr version: 5.2.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 18
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): postgres

**How to Reproduce**
Create a spring boot project and add spring-context-indexer to the pom (per https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index) and attempt to register a job via `@Recurring`.

When the application starts the RecurringJobPostProcessor component won't be loaded and the job will not be executed.

**Expected behavior**
The job should be registered.

**Comment by rdehuyss** [comment]
Hi @william00179 , is it possible this error also existed with JobRunr 5.1.x? 

I don't think a lot of things changed related to spring bean scanning in JobRunr 5.2.

**Comment by rdehuyss** [comment]
Current fix breaks this functionality for all users not using the `spring-context-indexer`.
