### ISSUE TITLE
[Feature] Configurable Retries for Each Job

### ISSUE THREAD

**Issue by pritam02** [jobrunr/jobrunr#566]
We are working on a project where we need to configure retry interval, max retries for each job. is it possible to get it done using the existing features?

**Comment by rajadilipkolli** [comment]
Did you tried @Job Annotation to set the retries?

**Comment by pritam02** [comment]
@Job allows us to configure only the number of retries.

In our use case, we want to support the following features - 

1. Choose between Simply and Exponential Backoff Retry Policy.
2. Configure the time interval between two retries.
3. For Exponential backoff policy, we should be able to configure the Multiplier, the max retry interval between two retries.

We want the above three features to be configurable for each job.

**Comment by rdehuyss** [comment]
Hi @pritam02 , the features above will be available in JobRunr Pro 6.0.0. We're currently working on these features.

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro v6
