### ISSUE TITLE
[Feature] Support for MongoDB cluster

### ISSUE THREAD

**Issue by mlubiejewski** [jobrunr/jobrunr#569]
**Are you running the latest version of JobRunr?**
Yes 
**Describe the bug**
### Runtime information
- __Timestamp__: 2022-09-27T16:15:50.589312Z
- __Location__: BackgroundJobServer 0bf788b8-9fb4-46a2-9d09-459df9a4d4d1
- __JobRunr Version__: 5.2.0
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.16
- __Is running from nested jar__: true
### Background Job Servers
- BackgroundJobServer id: 0bf788b8-9fb4-46a2-9d09-459df9a4d4d1
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2022-09-27T15:48:47.380Z, lastHeartbeat: 2022-09-27T16:15:48.187Z)
#### Concurrent modified jobs:
Job id: 06e6728d-6e7f-4d62-83fe-e6afe7eea099
    Local version: 1; Storage version: 2
    Local state: ENQUEUED (at 2022-09-27T16:15:50.583994Z) ← SCHEDULED (at 2022-09-27T16:15:35.549667Z)
    Storage state: ENQUEUED (at 2022-09-27T16:15:50.575003Z) ← SCHEDULED (at 2022-09-27T16:15:35.549667Z)
### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
    at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
    at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
    at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
    at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
    at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
**Environment**
I'm using JobRunr version: 5.2.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 11.0.16
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider 
**How to Reproduce**
Spring-boot app (2.3.12.RELEASE) with task
```
@Component
public class ExampleTask {
    private static final Logger log = LoggerFactory.getLogger(ExampleTask.class);
    private static final Logger jobLog;
    private static final int LIMIT = 100;
    private final Service1 service1;
    private final Service2 service2;
    @Recurring(
        interval = "PT5M"
    )
    @Job(
        name = "Task"
    )
    public void execute() {
        jobLog.info("Starting task");
        List<DTO> dtos = this.service2.method1(100);
        if (!dtos.isEmpty()) {
            try {
                this.service1.method1(dtos);
                this.service2.method2(dtos);
            } catch (HttpServerErrorException | HttpClientErrorException ex) {
                jobLog.info("Error in tests AB reset: {}", ex.getMessage(), ex);
            }
        }
    }
    public ExampleTask(
            final Service1 service1, 
            final Service2 service2) {
        this.service1 = service1;
        this.service2 = service2;
    }
    static {
        jobLog = new JobRunrDashboardLogger(log);
    }
}
```
**Expected behavior**
Shuold not fail when task is enqueued.
**Additional context**
Mongodb is a cluster with two nodes (one primary + one secondary)

**Comment by rdehuyss** [comment]
This is related to your MongoDB cluster. The write operation did not propagate to the from the primary to the secondary node.

JobRunr does not support MongoDB clusters at this time.

**Comment by tiarebalbi** [comment]
just reading this ticket, in the environment, I'm seeing in #659, the database behind the jobrunr is a MongoDB configured in a cluster.

**Comment by erohana** [comment]
we have the same problem too with DoucmentDB cluster .
@rdehuyss I don't understand how it is related to a cluster, it looks like because there are two applications polling from the database in parallel, so one will succeed and the second will fail, and if we have pore applications running it will happen to more applications .

can you share how the applications are synced together to make sure they don't step on each other ?

**Comment by rdehuyss** [comment]
@erohana - it's opensource, feel free to have a look yourself 😊.

**Comment by rdehuyss** [comment]
And it's mentioned in the docs...

**Comment by thjaeckle** [comment]
> JobRunr does not support MongoDB clusters at this time.

Is that statement still valid?

> And it's mentioned in the docs...

Might I ask where?  
I did not find that MongoDB clusters are not supported in the docs.

That would translate to no production MongoDB setup with primary and replicated secondaries is supported. 
Or is the restriction about a sharded Mongo setup?

**Comment by rdehuyss** [comment]
Well, I know several customers are now running Mongo in production, so that should not be an issue.

Important is that you also read from the master and not from the replica as there is too much delay for writes to propagate.

**Comment by rdehuyss** [comment]
Closing as I definitely tested against MongoDB Atlas with huge loads. Important thing to remember is to read from the master and not from the replica as there is too much delay for writes to propagate.

**Comment by thjaeckle** [comment]
@rdehuyss thanks for clarifying.

Yeah, reading from MongoDB secondaries works only consistently when writing when using `majority` write concern and reading with `linearizable` read concern.

**Comment by rdehuyss** [comment]
Thanks, tbh, I don't know enough about MongoDB clusters... Still on my to-do list to learn more about it.

**Comment by nphotchkin** [comment]
Hope your well Ronald :)

Ahh was going to reply as I'm starting a new project to report that I've had no issues, been running on atlas for 2 years :)

Read preference by default is the primary, I'll be sure to explicitly set it he read preference from now

Encase it helps anyone, literally given a standard atlas instance I include these flags in the connection string (with read preference update):

`mongodb+srv://[USER].mongodb.net/?retryWrites=true&w=majority&readPreference=primary`

**Comment by nphotchkin** [comment]
> Hi Nathan, long time no see! Thanks for your answer on this. It will definitely help others.
> 
> We should meetup for some beers again next time I'm in Barcelona 🥳 🍻

For sure that would be amazing, reachout anytime and I'll come see you! Working at a new company now same area jumped straight for jobrunr
