### ISSUE TITLE
[question] How to get result when job execute finished

### ISSUE THREAD

**Issue by leven-space** [jobrunr/jobrunr#57]
Hi，I want to get result when job execute finished in a Controller, but don't want to query database， Do you  have any suggestions?

**Comment by rdehuyss** [comment]
The result of the job? Whether it succeeded or not?

JobRunr doesn't know anything about the result of your job, just whether it succeeded or not...

Could you please elaborate what you exactly want?

**Comment by leven-space** [comment]
like using CompletableFuture ，Consumers can use the get() to block the current thread until the result of get()

**Comment by rdehuyss** [comment]
Currently, this is not possible.

Why don't you want to look it up in the database? JobRunr would also need to look it up in the database as it is distributed and may have run the job on another server then where you query.

I'm just trying to understand your use case.

**Comment by maxerbox** [comment]
I'm gonna eloborate on this because it is interesting to have a way to retrieve the result.
I'm trying to make a parallel job executor for a REST API.
I need the result, because I need to send to the client.
I have an endpoint to start the job (which return the job ID).
And an endpoint which return the status of the job, and the result if the job is finished.
(I know, I can use Websockets, but that's a no).

**Comment by maxerbox** [comment]
There is feedback

**Comment by patkujawa-wf** [comment]
FWIW I have the same use case (parallel job executor, API to start, API to poll for status). I don't understand the "but don't want to query database" bit in the original post, but perhaps it was more along the lines of, "don't want to maintain a db schema just for the results of a job". If so, we are currently using metadata to store the result of a job, similar to completable future. This results in the job result being persisted as JSON just like other job info.

We use some helpers to store the metadata object name as the key:

```kotlin
import org.jobrunr.jobs.Job
import org.jobrunr.jobs.context.JobContext

fun <E : Any> JobContext.saveTypedMetadata(data: E) =
    this.saveMetadata(data::class.java.canonicalName, data)

fun <E : Any> Job.saveTypedMetadata(data: E) {
    this.metadata[data::class.java.canonicalName] = data
}

inline fun <reified E : Any> Job.getTypedMetadata(): E? =
    this.metadata[E::class.java.canonicalName] as? E
```

An example of a metadata class is:
```kotlin
import org.jobrunr.jobs.context.JobContext

class FooJobMetadata(
    val fooOne: String,
    val fooTwo: Map<Long, List<String>>,
) : JobContext.Metadata
```

And then in the job runner, when the job finishes successfully:
```kotlin
jobContext().saveTypedMetadata(result) // where result is a FooJobMetadata
```

Finally, in the job polling handler:
```kotlin
val job = storageProvider.getJobById(UUID.fromString(jobId))
val jobResult: FooJobMetadata = job.getTypedMetadata<FooJobMetadata>()
print(jobResult.fooOne) // for example
```

**Comment by rdehuyss** [comment]
In JobRunr Pro 5, this feature will be implemented and you wil be able to get the result of a job.

The reason I don't like the approach you are using, is that consumers of your API can do a DOS attack really easy by requesting the job result in a for loop, ... . 

JobRunr Pro 5 will prevent this by returning a result that either contains the actual result or some information when the client can poll again for the result (taking into account the duration of previous related jobs). If the client does not reflect that duration, it will throw a back off exception.

I hope that makes sense?

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro branch feature/v5.

**Comment by neldrak** [comment]
> In JobRunr Pro 5, this feature will be implemented and you wil be able to get the result of a job.
> 
> The reason I don't like the approach you are using, is that consumers of your API can do a DOS attack really easy by requesting the job result in a for loop, ... .
> 
> JobRunr Pro 5 will prevent this by returning a result that either contains the actual result or some information when the client can poll again for the result (taking into account the duration of previous related jobs). If the client does not respect that duration, it will throw a back off exception.
> 
> I hope that makes sense?

I can see why the back-off/ddos prevention system is a PRO feature, but I don't really get why the "normal" version now suddenly has less features. Having the metadata persisted was quite usefull for us to save small job related details, which we didn't want to join a seperate table for. Now this is gone just by upgrading. As we don't expose the job APIs to anything outside our control storage and ddos concerns aren't really a thing for us.
An optional setting would be a great thing, but I guess not worth your time and adding complexity.
We'd really like to buy Pro, but we are a small project inside a Fortune500 company, so getting budget for 5k/year and going through global procurement is not an option, I'd rather shoot myself ;)

Just wanted to give my feedback.
Thanks for the great work!

**Comment by rdehuyss** [comment]
Hi Daniel,

well - the reason why I removed is that somebody did exactly this (getting results via metadata without DDOS prevention) and started complaining about JobRunr performance. It took me quite some time to find the root cause (as people don't tend to tell you this when you ask for details). As this is still something I maintain in my free time, I also need to protect myself for these kind of issues - maintaining open-source is hard and takes a lot of time.

If you want discuss a license (I understand your situation), feel free to contact me (contact details are on the website) and I'm sure we'll be able to work something out.

Thanks for your kind words,
R

**Comment by BeamLiu** [comment]
I agree this feature is a fundamental feature, may consider going with community version. BTW, thanks for the great work of this project.
