### ISSUE TITLE
[Feature] Provide Liquibase and Flyway scripts

### ISSUE THREAD

**Issue by rajadilipkolli** [jobrunr/jobrunr#571]
**Is your feature request related to a problem? Please describe.**
There are few organizations which provides only option to create DML is using Flyway or Liquibase migrations for SQL Stores

**Describe the solution you'd like**
Flyway and Liquibase script per database so that It can be copied and executed in the project start up

**Comment by neldrak** [comment]
Flyway would be really appreciated.
Currently trying to setup Pro, but column "PAUSED" is missing and I can't find a definition in any sql script.

**Comment by neldrak** [comment]
After trying a while, I think there is no way to see the SQL to create the Pro Table structure as it is in a private repo, right?
We can't use the build in .sql scripts, as our HANA DB is not really supported (but it is pretty close to DB2).
So we manually converted the scripts so far and everything worked fine.
But without access to the DML scrips in PRO, it is really hard to reverse engeneer the update scripts :)
Thanks for any support.

Regards,
Daniel

**Comment by rdehuyss** [comment]
Hi @neldrak - sorry, I didn't see this comment earlier as it was a comment. Could you tell me from which company you are (depending on the license you are entitled to view the source code)?

**Comment by neldrak** [comment]
Hey! Sorry, used my private github account. I'm the guy from SAP  ;)
No we are not allowed to see the sourcecode, which I totally understand.
But I dont think it makes sense to hide the DDL SQL, as we would anyway see the DDL structure later in the DB.
Worst case I need to deploy JobRunR Pro to some instance with a DB2/Postgre DB and then check the DDL. But that would take me some time, so I thought I might ask here.
Thanks for your help!

**Comment by neldrak** [comment]
I could also offer you the working SQL baseline/migrations for HANA SQL if you want to start supporting it :D

**Comment by rdehuyss** [comment]
Haha - lol. 

Have you tried [Exporting the SQL scripts](https://www.jobrunr.io/en/documentation/installation/storage/#apply-the-sql-scripts-yourself)? 

JobRunr supports a command that will provide you with all the necessary SQL scripts to generate all the tables. Drop me a note if that doesn't work out!

**Comment by neldrak** [comment]
ahhhhhh... RTFM ;)
Thanks for the help and sorry for the issue highjack.

**Comment by rdehuyss** [comment]
Flyway and Liquibase support will be available in the. next release of JobRunr Pro.
