### ISSUE TITLE
[BUG] NullPointerException in MDCMapper:16 when MDC has a null value

### ISSUE THREAD

**Issue by jan-schumacher** [jobrunr/jobrunr#581]
**Are you running the latest version of JobRunr?**
Yes
5.1.7

**Describe the bug**
When MDC has a null value there is a NullPointerException, because the underlying ConcurrentHashMap does not allow null values.

**Environment**
I'm using JobRunr version: 5.1.7
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk 17.0.2 2022-01-18
Kotlin 1.7.10
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): PostgresSQL

**How to Reproduce**
```java
MDC.put("Something",null);
jobScheduler.schedule<MyJob>(Instant.now()) {
}
```

**Expected behavior**
Null values don't break the application

**Additional context**
We are using JobScheduler Bean autogenerated by org.jobrunr:jobrunr-spring-boot-starter:5.1.7

**Comment by jan-schumacher** [comment]
This might be an issue with Java 17?

**Comment by jan-schumacher** [comment]
@rdehuyss Can you tell me when this fix will be released? This bug makes allot of trouble right now.

**Comment by rdehuyss** [comment]
Hi @jan-schumacher - JobRunr 5.3.1 was released with the fix. It took me a bit longer because of personal reasons. 

Anyway, enjoy!

**Comment by rdehuyss** [comment]
Feel free to star the repo if you enjoy using JobRunr!
