### ISSUE TITLE
Unable to Autowired service classes

### ISSUE THREAD

**Issue by rasi-natbuild** [jobrunr/jobrunr#59]
**Describe the bug**

When I call my service call in try block it works fine, which means my service class is properly wired, but when I try to put it to BackgroundJob.enqueue or scheduleRecurrently it doesn't work.

**Environment**
I'm using version 1.1.0
I'm using SpringBoot 2.3.3.RELEASE
I'm running on JRE / JDK 14 
I'm using the following StorageProvider InMemoryStorageProvider

**To Reproduce**
```java
@Configuration
public class Runner {

	private static final Logger log = LoggerFactory.getLogger(Runner.class);

	@Autowired JobScheduler jobScheduler;
	@Autowired FtpAccountService ftpAccountService;

        @Bean
	public void scheduleRecurrently() {
		log.info("Configured");
		
		try {
			ftpAccountService.sweepFolders();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		BackgroundJob.enqueue(() -> ftpAccountService.sweepFolders());
	}

}
```

**Error**
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.onlykalu.tn.edi.service.FtpAccountService' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:352) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1127) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.jobrunr.server.runner.BackgroundJobWithIocRunner.supports(BackgroundJobWithIocRunner.java:21) ~[jobrunr-1.1.0.jar:na]
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$0(BackgroundJobServer.java:133) ~[jobrunr-1.1.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
```

**Expected behavior**
List down files

**Comment by rasi-natbuild** [comment]
Attaching sample project...
 
[TestingJobRunr.zip](https://github.com/jobrunr/jobrunr/files/5462020/TestingJobRunr.zip)

**Comment by rdehuyss** [comment]
Root cause found after 3 hours of debugging :smile: 

It is caused because of this dependency:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-devtools</artifactId>
    <scope>runtime</scope>
    <optional>true</optional>
</dependency>
```
If you comment this dependency, all works as expected.

**Why does it happen:** 
- by adding that dependency, you also enable the live reload server from Spring
- the live reload server results in Spring using a different classloader than JobRunr.
- because different classloaders are used, `com.natbuild.test.jobrunr.service.TestService` loaded by the Classloader of JobRunr is not known anymore by Spring.
- the reason for this is that `com.natbuild.test.jobrunr.service.TestService` loaded by Classloader A != `com.natbuild.test.jobrunr.service.TestService` loaded by Classloader B

**Comment by rdehuyss** [comment]
> Attaching sample project...
> 
> [TestingJobRunr.zip](https://github.com/jobrunr/jobrunr/files/5462020/TestingJobRunr.zip)

P.s.: thanks for providing the example project - I would not have been able to find the issue without it!

**Comment by rasi-natbuild** [comment]
Legend worked perfectly, thanks mate and this framework is a lifesaver for me.

**Comment by rasi-natbuild** [comment]
Hey mate, this may not happen earlier for you guys but when dev tools are in that makes auto restart the spring boot application when code changes and results in 

```
Error creating bean with name 'dashboardWebServer' defined in class path resource [org/jobrunr/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrDashboardWebServer]: Factory method 'dashboardWebServer' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use: bind
```
You can simply test this by a simple change in a code (need to have dev-tools in).

Any feedback highly appreciates.

Thanks

**Comment by rdehuyss** [comment]
Hi Rasi,

I could reproduce the problem and reopened #61 

Cheers,
R
