### ISSUE TITLE
[Enhancement] jobrunr-spring-boot-starter adds two retry-filters

### ISSUE THREAD

**Issue by Guschtel** [jobrunr/jobrunr#594]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
The code in the JobRunrAutoConfiguration sets Job Filters for the BackgroundServer:
```java
@Bean(destroyMethod = "stop")
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "org.jobrunr.background-job-server", name = "enabled", havingValue = "true")
    public BackgroundJobServer backgroundJobServer(StorageProvider storageProvider, JsonMapper jobRunrJsonMapper, JobActivator jobActivator, BackgroundJobServerConfiguration backgroundJobServerConfiguration, JobRunrProperties properties) {
        final BackgroundJobServer backgroundJobServer = new BackgroundJobServer(storageProvider, jobRunrJsonMapper, jobActivator, backgroundJobServerConfiguration);
        backgroundJobServer.setJobFilters(singletonList(new RetryFilter(properties.getJobs().getDefaultNumberOfRetries(), properties.getJobs().getRetryBackOffTimeSeed())));
        backgroundJobServer.start();
        return backgroundJobServer;
    }
```

Since setJobFilters actually calls `this.jobDefaultFilters.addAll(jobFilters);` it simply adds an additional set of filters (there is already a default set of filters configured).

**Environment**
I'm using JobRunr version: 5.3.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 11
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Oracle/H2 Storage Provider

**How to Reproduce**
Start the server with the spring boot autoconfiguration

**Expected behavior**
JobRunr should configure only one RetryFilter

**Comment by rdehuyss** [comment]
At runtime, only the last added filter will be used (in this case, the one from Spring).

See [AbstractJobFilters](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/filters/AbstractJobFilters.java#L33).

Are you having issues with something related to filters?

**Comment by Guschtel** [comment]
@rdehuyss not a real issue, but i don't see the point in making those iterations when it could be avoided.
That could be done by either making the lists not package protected, so that one could use .clear() and then add the actual ones, or by adding another method or a bool flag for completely replacing the existing filters.

Wouldn't that be an improvement?

**Comment by rdehuyss** [comment]
Yes, that would be an improvement. Feel free to open a PR.

**Comment by rdehuyss** [comment]
No PR coming in, closing issue.
