### ISSUE TITLE
[Feature] Add ability to cancel and update a job

### ISSUE THREAD

**Issue by johanhaleby** [jobrunr/jobrunr#60]
I cannot seem to find a way to delete/cancel/update a non-reoccurring job but this would be really beneficial, especially in combination with https://github.com/jobrunr/jobrunr/issues/47 (the ability for the client to specify an id).

 Here's one use case: 

Imagine I have a multiplayer game where players try to guess a word. I want the game to automatically end after 10 hours of inactivity. This means that as soon as a player has made a guess, I like to schedule the code that ends the game after 10 hours. If a player guesses the right word before 10 hours, the game is ended and then I'd like to _cancel_ the scheduled job. If, on the other hand, a player guesses the wrong word, I'd like to _update_ the existing job and schedule it to end 10 hours from the last interaction with the game.

Does this make sense?

**Comment by rdehuyss** [comment]
Hi @johanhaleby ,

you can already cancel a scheduled job by deleting it (it will move to the Deleted state).

See `jobScheduler.delete(UUID id)`.

Is it an option to _delete the existing job and recreate a new job_  instead of _updating the existing job_ ?

And yes, the feature request definitely makes sense.

**Comment by johanhaleby** [comment]
@rdehuyss Oh cool, that's great! :)

But what about updating? Can you simply schedule a job with the same id? Will it override the previous one?

**Comment by rdehuyss** [comment]
No, updating is not possible (yet) as you cannot provide the id for a scheduled job.

**Comment by nlescure-pictet** [comment]
Hi,

Deleting a job only stops the execution on the jobrunr side right ?
If the job is running a remote async job (polling the remote execution status every n seconds for example), it would be nice to be able to use a kind of callback which would give the opportunity to the developer to run some code to cancel the remote execution as well.

Example: JobScheduler.enqueue(() -> doSomething(), () -> cancelExec());

Cheers.

**Comment by rdehuyss** [comment]
@nlescure-pictet , normally if you delete the job, the thread will be interrupted.

If you catch InterruptedException inside your job, you can then cleanup within the catch block.
Does this make sense?

**Comment by rdehuyss** [comment]
So, I have give this some thought: with the release of v2.0.0, idem-potency for Jobs has become easier as you specify your own job uuid. But, this also means that there is no way to update a job directly.

So, to update a job, please **delete** it first (if it off-course has not been processed) and **then create a new job**.

**Comment by johanhaleby** [comment]
@rdehuyss Cool thanks! Will it possible to create a new job with the same UUID as a deleted job?

**Comment by rdehuyss** [comment]
@johanhaleby yes, if you use `deletePermanently`.

**Comment by johanhaleby** [comment]
Cool, thanks!

One potential drawback with delete and then re-create is that this will not
happen in an atomic fashion. So it could still be something that, perhaps,
could be considered in the future. But I understand if you have other
priorities :)

**Comment by ryuichi7** [comment]
@rdehuyss, first off, thanks for the great lib 😊.

I can't find `deletePermanently` anywhere in the source code (I'm using the OSS version `6.1.4`). Is it only available in the pro version?

**Comment by ryuichi7** [comment]
for anyone interested, I achieved this by injecting the storage provider that can be accessed by the current background job server.

something along the lines of (with Guice)
```java
@Provides
@Singleton
static StorageProvider storageProvider() {
     // make sure your job scheduler is already initialized when this is accessed
    return JobRunr.getBackgroundJobServer().getStorageProvider()
}

public class MyBackGroundJobService {
    private final Provider<StorageProvider> storageProvider;

    @Inject
    public class MyBackGroundJobService(Provider<StorageProvider> storageProvider) {
        this.storageProvider = storageProvider;
    }

    public void deletePermanently(UUID id) {
        storageProvider.get().deletePermanently
    }
}
```
