### ISSUE TITLE
[BUG] Server JobRunr exception

### ISSUE THREAD

**Issue by Qiuqiu0505** [jobrunr/jobrunr#602]
**Are you running the latest version of JobRunr?**
 No
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.
Yes, Ichange to 5.3.0 and the issue still exists
**Describe the bug**
I add many  recurring tasks and not received the task on time. When I restart the jobRunr service, I  will update tasks by onliy taskId.

**Environment**
I'm using JobRunr version: 5.2.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292):  JDK 1.8.0_151
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): mysql 8.0.20

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
BackgroundJob.enqueue(() -> service.helpMe());
```

The codes are:

`    public void addTask(UserJob userJob) {

        Long jobId = userJob.getId();
        String jobIdentifierId = getJobIdentifierId(JobType.USER_JOB.getName(), jobId);
        String jobCronExpression = getExpression(userJob.getCronExpression());
        try {
            CronExpression.create(jobCronExpression);
        } catch (InvalidCronExpressionException e) {
            log.error("cron expression is illegal! cronExpression: {}, error:{}", userJob.getCronExpression(), e.getMessage());
            throw new RuntimeException(e);
        }

        jobRequestScheduler.scheduleRecurrently(jobIdentifierId, jobCronExpression, new SampleJobRequest(JobType.USER_JOB.getCode(), jobId));
    }`

the configuration :
org:
  jobrunr:
    background_job_server:
      enabled: true
      worker-count: 20
    dashboard:
      enabled: true
      port: 9099

**Expected behavior**
I can receive the task on time.

**Additional context**
The following about some logs：
2022-11-06 07:59:55.714 INFO  [backgroundjob-zookeeper-pool-2-thread-2] org.jobrunr.server.JobZooKeeper - Recurring job 'com.hisense.hitv.vipjob.service.JobHandlerService.run(com.hisense.hitv.vipjob.model.Sampl
eJobRequest@70659be0)' resulted in 27 scheduled jobs. This means a long GC happened and JobRunr is catching up.
2022-11-06 08:01:45.684 INFO  [backgroundjob-zookeeper-pool-2-thread-2] org.jobrunr.server.JobZooKeeper - Recurring job 'com.hisense.hitv.vipjob.service.JobHandlerService.run(com.hisense.hitv.vipjob.model.Sampl
eJobRequest@70659be0)' resulted in 22 scheduled jobs. This means a long GC happened and JobRunr is catching up.
2022-11-06 08:03:34.032 INFO  [backgroundjob-zookeeper-pool-2-thread-2] org.jobrunr.server.JobZooKeeper - Recurring job 'com.hisense.hitv.vipjob.service.JobHandlerService.run(com.hisense.hitv.vipjob.model.Sampl
eJobRequest@70659be0)' resulted in 22 scheduled jobs. This means a long GC happened and JobRunr is catching up.

If there is wrong, please tell me.
Thanks in advance

**Comment by rdehuyss** [comment]
How many recurring tasks do you have?

**Comment by Qiuqiu0505** [comment]
> How many recurring tasks do you have?
When verifying locally，the number of tasks is about 224.  
When the amount is 90. 000, the problem still exists.

If need more. please tell me.

**Comment by rdehuyss** [comment]
JobRunr OSS (open source) is only able to handle about 100 recurring jobs (depends on your DB performance). See the pricing page See https://www.jobrunr.io/en/pricing/).

The reason for that is that I originally designed JobRunr for my own needs where for me 10 recurring jobs was already a lot. Now people start to run 1000+ recurring jobs with it. As it was originally not designed for that, I decided to add this feature to the Pro version.

**Comment by Qiuqiu0505** [comment]
@rdehuyss 
I understand，due to more recurring jobs，will the all jobs  fail ？If using the current version,  Is there a good solution？ for example, improving my database performance.

Now, we have launched this feature and all job failed.  Is there any good remedy?

Thanks  in advance

**Comment by rdehuyss** [comment]
You could do 2 things:
- try to give DB some more performance
- increase pollIntervalInSeconds

Or, get a Pro version and all will be solved 😄

**Comment by jhchee** [comment]
Running one job with 10 seconds cron interval is complaining about  
```This means a long GC happened and JobRunr is catching up.```

**Comment by rdehuyss** [comment]
@jhchee which JobRunr version are you on?

**Comment by rdehuyss** [comment]
And what's your pollIntervalInSeconds?

**Comment by jhchee** [comment]
@rdehuyss Im using in memory backend, Spring boot 3 and pollIntervalInSeconds as default.

**Comment by jhchee** [comment]
JobRunr version: [5.3.3](https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-starter/5.3.3)

**Comment by rdehuyss** [comment]
Then your CRON (10s), is lower than the pollIntervalInSeconds (default 15s) resulting in the error message above.

I do agree that the error message could be made clear

See also the docs: https://www.jobrunr.io/en/documentation/background-methods/recurring-jobs/

**Comment by jhchee** [comment]
@rdehuyss Ah I see, sorry for the misunderstanding earlier.
