### ISSUE TITLE
[Feature] Can JobRunr support the Spring Live Reload server?

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#61]
Related to issue #59 ...

When the following Spring dependency is added, JobRunr does not work anymore.

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-devtools</artifactId>
    <scope>runtime</scope>
    <optional>true</optional>
</dependency>
```

The root cause is that the Live Reload server makes Spring use a different classloader than JobRunr. Because of that, although Spring internally knows a certain Job class, it cannot be found and results in `NoSuchBeanDefinitionException`.
The reason for this is that _**com.example.TestService loaded by Classloader A != com.example.TestService loaded by Classloader B**_

**Comment by rdehuyss** [comment]
Resolved with commit 6acc

**Comment by rasi-natbuild** [comment]
any luck with this mate?

**Comment by rdehuyss** [comment]
Not yet to be honest - having some trouble with private life (kids en co).

I'll try to plan it in somewhere before the end of the month.

Kind regards,
Ronald

**Comment by rasi-natbuild** [comment]
All good mate thanks
