### ISSUE TITLE
[BUG] configuration for spring boot with yaml file

### ISSUE THREAD

**Issue by trangdaiphu** [jobrunr/jobrunr#614]
**Are you running the latest version of JobRunr?**
I'm using 5.3.1

**Describe the bug**
I define configuration for spring boot in yaml file, but jobrunr has no affect. Although I config port dashboard in yaml config file, but after I start my project, I can't access dashboard. 

**Environment**
I'm using JobRunr version: 5.3.1
I'm running on openjdk version "1.8.0_345"
I'm using the following StorageProvider Mongodb

**How to Reproduce**
my configuration jobconfig
```java
  @Bean
  public JobScheduler initJobRunr(final MongoClient mongoClient,
      final JobActivator jobActivator) {
    return JobRunr.configure()
        .useJobActivator(jobActivator)
        .useStorageProvider(new MongoDBStorageProvider(mongoClient))
        .withJobFilter(new RetryFilter(3))
        .useBackgroundJobServer()
        .initialize()
        .getJobScheduler();
  }
```
my configuration yaml file
```yml
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enable: true
      port: 8082
```

**Expected behavior**
yaml configuration file affects for spring boot.

**Additional context**
In present, I'm using Jobrunr.configure().useDashboard(8082) instead of yml config.

**Comment by rdehuyss** [comment]
You should depend on the correct maven artifact, `jobrunr-spring-boot-starter`. Also, you don't need to make the JobConfig - all of this will be done via the spring boot starter.

Please star JobRunr if you enjoy using it!

**Comment by trangdaiphu** [comment]
tks. I followed and ran successfully.
