### ISSUE TITLE
[Feature] Dashboard security should be configurable  

### ISSUE THREAD

**Issue by podile** [jobrunr/jobrunr#615]
**Is your feature request related to a problem? Please describe.**
Since the library currently allowing basic auth security mechanism only to protect jobs dashboard, I am not able to implement my own security mechanism like OAuth to protect dashboard and API.  

**Describe the solution you'd like**
Basic auth may not be option for  many modern services, there should be a way to customize authenticator to support other security mechanisms. Enhancements needed to dashboard module to enable developer to customize dashboard security.

**Describe alternatives you've considered**
NA

**Comment by rdehuyss** [comment]
Duplicate of #410. Will be part of JobRunr Pro v6.
