### ISSUE TITLE
[Feature] Allow poll interval to be less than 5 seconds for InMemoryStorageProvider

### ISSUE THREAD

**Issue by johanhaleby** [jobrunr/jobrunr#619]
When writing integration tests it would be really useful if it would be possible to configure the poll interval to be less than 5 seconds so that the tests don't need to wait so long, especially when using the `InMemoryStorageProvider`. However, the standard `BackgroundJobServerConfiguration` won't allow this because `andPollIntervalInSeconds` throws an exception if `pollIntervalInSeconds` is less than 5. Preferably, the method should take a `java.time.Duration` instead of an integer so that we can configure it with e.g. 200 ms for testing purposes.

**Comment by rdehuyss** [comment]
@gklijs : what do you mean almost? Is this also in unit tests or in actual usage?

If it's for unit testing, you can have a look at the [BackgroundJobByJobLambdaTest](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/scheduling/BackgroundJobByJobLambdaTest.java).

**Comment by gklijs** [comment]
Thanks, its working with:
```
        StorageProvider storageProvider = new InMemoryStorageProvider();
        JobScheduler scheduler = new JobScheduler(storageProvider);
        JobRunrDeadlineManager manager = JobRunrDeadlineManager
                .builder()
                .jobScheduler(scheduler)
                .scopeAwareProvider(new ConfigurationScopeAwareProvider(configuration))
                .transactionManager(NoTransactionManager.INSTANCE)
                .spanFactory(configuration.spanFactory())
                .build();
        JobRunr.configure()
               .useJobActivator(new SimpleActivator(manager))
               .useStorageProvider(storageProvider)
               .useBackgroundJobServer(usingStandardBackgroundJobServerConfiguration().andPollIntervalInSeconds(5))
               .initialize();
        backgroundJobServer = JobRunr.getBackgroundJobServer();
```
Not sure why, but the tests run fast, I don't have to wait 5 seconds for each event. I need the custom activator since it will call a method in the manager.

**Comment by rdehuyss** [comment]
Solved in branch v7.
