### ISSUE TITLE
[Feature] Check if job is already in the queue

### ISSUE THREAD

**Issue by Skillkiller** [jobrunr/jobrunr#630]
**Is your feature request related to a problem? Please describe.**
Hello,
this primarily a question and secondarily a feature request. Is it currently possible in the Free version to check if a job with parameter X is already in the queue? I am facing the problem that I cannot make sure if such a job is already in the queue.

**Describe the solution you'd like**
``BackgroundJob.findJob([parameter]...)``
I am not sure if this is possible without a job name.

**Describe alternatives you've considered**

**Additional context**

**Comment by rdehuyss** [comment]
This is already possible in the pro version.
