### ISSUE TITLE
[BUG] Jobs getting enqueued but not running

### ISSUE THREAD

**Issue by SharkFourSix** [jobrunr/jobrunr#636]
### Contact Details

no-need@example.com

### JobRunr Version

5.7.1

### JDK Version

17

### Your SQL / NoSQL database

MySQL 8

### What happened?

Jobs get enqueued but do not get run, ever

- In Memory storage
- Spring boot

### How to reproduce?

```java
public class MyService {
    void sweepForTempFilesOlderThan(TimeUnit tu){
    }
} 

void doX(){
    class SweeperJob {
        void doWork(){
            myService.sweepForTempFilesOlderThan(TimeUnit.Hours(2))
        }
    }
    var job = new SweeperJob();
    // jobscheduler.enqueue(job::doWork);  <-- only schedules, doesn't run
    // BakgroundJob.enqueue(job::doWork); <-- only schedules, doesn't run
}
```

Checking dashboard shows that the jobs are there but queued. Even up to 10 minutes without running.

What's the issue?

**Comment by rdehuyss** [comment]
Not an official JobRunr version (latest is 5.3.1) and not following the bug template (the email address is missing).

If you want support on open-source, please have the courtesy to provide your email address or company you are working for. Feel free to reopen once the correct details are provided.

Thanks!
