### ISSUE TITLE
[Feature] - Change job schedule at runtime

### ISSUE THREAD

**Issue by StefanoPaganoni** [jobrunr/jobrunr#639]
**Is your feature request related to a problem? Please describe.**
In past versions of jobrunr (free version), ex. 4.x.x, it was possible to change a job schedule by modifying it's corresponding row in jobrunr_recurring_jobs table and by changing the scheduleExpression field. In 5.x.x version it is no more possible.

**Describe the solution you'd like**
We'd like to have this feature back and change the job schedule at runtime by changing entries in jobrunr_recurring_jobs table or, if it is not possible, in the dashboard.

**Describe alternatives you've considered**
An alternative we have considered is to launch manually the trigger for one single job from the dashboard, but it is not as effective as changing the row value and change the scheduleExpression field.

**Comment by rdehuyss** [comment]
Changing stuff in the database was never meant to be done, never should be done and I will never endorse this way of working. This may break a lot of stuff. 

I may add this as a feature to the Pro version where this can be edited from the dasbboard.

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro (will be part of next release).
