### ISSUE TITLE
[Feature] Manageable base paths for dashboard app

### ISSUE THREAD

**Issue by ivan-osipov** [jobrunr/jobrunr#640]
**Is your feature request related to a problem? Please describe.**
When we deploy a few services with jobrunr dashboard to k8s cluster (the particular technology doesn't matter) we need to forward urls to dashboards of different services via Ingress (just a wrapper for nginx). 
Two dashboards are available at:
jobs.my-app.my-company.io/my-service-1
jobs.my-app.my-company.io/my-service-2

We realised that because react app does not define base path it works like:
1. we open jobs.my-app.my-company.io/my-service-1
2. JobRunrDashboardWebServer redirects to /dashboard
3. We get jobs.my-app.my-company.io/dashboard url instead of jobs.my-app.my-company.io/my-service-1/dashboard
4. js/css files are trying to be loaded from jobs.my-app.my-company.io/dashboard even if we initially opened jobs.my-app.my-company.io/my-service-1/dashboard

It seems that there are two problems
1. Not configurable redirect on / (workaround to override start() of JobRunrDashboardWebServer)
2. Static files are trying to be load without base path (/my-service/dashboard) awareness

**Describe the solution you'd like**
1. Support configuration for base path for UI (replace Router with BrowserRouter and use "basename")
2. Support configurable "/" -> "/my-service-1/dashboard" redirect (org/jobrunr/dashboard/JobRunrDashboardWebServer.java:69)

**Describe alternatives you've considered**
Use domains as a separator between two services (counter intuitive & harder to support), for example:
1. jobs.service-1.my-app.io/dashboard
2. jobs.service-2.my-app.io/dashboard

**Comment by rdehuyss** [comment]
Hi @ivan-osipov , this is part of JobRunr Pro. See https://www.jobrunr.io/en/documentation/pro/jobrunr-pro-dashboard/#easier-support-to-proxy.

Feel free to reach out if you would like a Pro subscription.

**Comment by ivan-osipov** [comment]
@rdehuyss what if somebody implement this part of functionality in free version. Will you approve this PR?

**Comment by rdehuyss** [comment]
Hmmm, difficult - it's the first time I receive this question...

Probably not as I think I already gave a lot to the open source community and I also try to make a living from it.

Second, I've done this for the pro version and it was not a trivial task to be honest. It may be cheaper to just buy the pro version, especially with all the extra features that come with the Pro version.

Fyi - Jobrunr 6  and JobRunr 6 Pro is around the corner. With Jobrunr 6 Pro you could host it within the spring container, so without the extra server.
