### ISSUE TITLE
[BUG] Get Server Status method is passing Instant.now() to the last heartbeat parameter

### ISSUE THREAD

**Issue by RicardoMGNascimento** [jobrunr/jobrunr#663]
### JobRunr Version

5.3.3

### JDK Version

17

### Your SQL / NoSQL database

Postgres

### What happened?

Hi,
When trying to implement a method that restarts the background server job when the background server job stops for some reason, we found out that the getServerStatus() method is passing Instant.now() to the last heartbeat parameter instead of actually using the lastHeartbeat. 

If the background job server stops, then the getServerStatus of the background server is returning an incorrect result.

```
public BackgroundJobServerStatus getServerStatus() {
        return new BackgroundJobServerStatus(this.backgroundJobServerId, this.workDistributionStrategy.getWorkerCount(), this.configuration.pollIntervalInSeconds, this.configuration.deleteSucceededJobsAfter, this.configuration.permanentlyDeleteDeletedJobsAfter, this.firstHeartbeat, Instant.now(), this.isRunning, this.jobServerStats.getSystemTotalMemory(), this.jobServerStats.getSystemFreeMemory(), this.jobServerStats.getSystemCpuLoad(), this.jobServerStats.getProcessMaxMemory(), this.jobServerStats.getProcessFreeMemory(), this.jobServerStats.getProcessAllocatedMemory(), this.jobServerStats.getProcessCpuLoad());
    }
```

I don't think this was intended or at least I don't think this should be the expected behaviour.

Thanks!

### How to reproduce?

In order to reproduce this, we disconnected our database from the application and then recconected it.

After reconecting we called the following method:

`backgroundJobServer.getServerStatus().getLastHeartbeat()`

This isn't returning the lastheartbeat as it's on the database but the Instant.now().

**Comment by rdehuyss** [comment]
This is intended and the feature you're trying to implement is part of JobRunr Pro.
