### ISSUE TITLE
[Feature] PermanentlyDeletedFilter

### ISSUE THREAD

**Issue by steamrolla** [jobrunr/jobrunr#666]
It would be nice to be able to tap into JobRunr when a job is permanently deleted to perform things like cleaning up other data in the database.

Would love to see a PermanentlyDeletedFilter that is invoked when a job has been permanently deleted.

**Comment by rdehuyss** [comment]
Hi @steamrolla , is there a reason why the `ApplyStateFilter` is not working for you when the newState is `DELETED`?

**Comment by steamrolla** [comment]
I think the `ApplyStateFilter` will work for us when the newState is `DELETED`, however, it would still be nice to have a `PermanentlyDeletedFilter`. 😄

**Comment by rdehuyss** [comment]
The reason that it is not there is that it results in a huge performance impact (fetching all jobs to be deleted again from the DB).  As the `ApplyStateFilter` will work for you when the newState is `DELETED`, I currently don't see the added value.

Will close this for now but do not hesitate to reopen in case there is an actual business need.
