### ISSUE TITLE
when using enqueue for background job -> ILlegalAccessException -> class org.jobrunr.server.runner.AbstractBackgroudJobRunner can not access a member of class with modifiers "private"

### ISSUE THREAD

**Issue by ankit296** [jobrunr/jobrunr#667]
### JobRunr Version

5.3.3

### JDK Version

JDK11

### Your SQL / NoSQL database

NoSql

### What happened?

when using enqueue for background job -> ILlegalAccessException -> class org.jobrunr.server.runner.AbstractBackgroudJobRunner can not access a member of the class with modifiers "private"

=> There is many private class available inside the method that I calling

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

### Relevant log output

```shell
when using enqueue for background job -> ILlegalAccessException -> class org.jobrunr.server.runner.AbstractBackgroudJobRunner can not access a member of class with modifiers "private"
```

**Comment by rdehuyss** [comment]
Closing this without answer as not following community guidelines:

> As this is an open-source project where we try to make a living from,
we kindly ask you to have a complete Github Personal Profile (Name and Company details or LinkedIn Profile).

I'm really sorry but I don't see why I should provide free support if you're not willing to provide me the above details.

**Comment by rdehuyss** [comment]
@ankz296 : the method your are scheduling is private. It should be public.

The exception is quite clear, I think 😄

**Comment by ankz296** [comment]
Yes I got the solution .

Thanks for reply .
