### ISSUE TITLE
Not getting no of succeeded, failed, processing jobs in dashboard

### ISSUE THREAD

**Issue by shivamkapoor9999** [jobrunr/jobrunr#670]
### JobRunr Version

6.0.0

### JDK Version

8

### Your SQL / NoSQL database

MySQL

### What happened?

Not getting no of succeeded, failed, processing jobs in dashboard
Screenshot:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/26411641/215471356-4db870a4-fa94-4261-80fd-5008107bdabf.png">

In earlier version 5.3.2 These nos where present in dashboard real-time

### How to reproduce?

Open dashboard with jobrunr v6

**Comment by rdehuyss** [comment]
Also, if you want community support, please complete your github profile.

**Comment by rdehuyss** [comment]
@shivamkapoor9999 - can you setup a repo that reproduces this issue?

**Comment by shivamkapoor9999** [comment]
@rdehuyss surely I'll complete my profile.

Update on the issue:
While analysing logs I found below error every second, I think this is causing the issue seems on UI.

Error notifying JobStorageChangeListeners
org.jobrunr.storage.StorageException: java.sql.SQLException: View 'loantransaction_olxcl.jobrunr_jobs_stats' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

**Comment by shivamkapoor9999** [comment]
It was not coming in 5.3.2 version so may be recent changes in migration script may caused it.

**Comment by rdehuyss** [comment]
Hi @shivamkapoor9999 - indeed, JobRunr should have access to the view `jobrunr_jobs_stats `.

Strange that you have this error as nothing major changed since [git tag v5.3.2](https://github.com/jobrunr/jobrunr/blob/v5.3.2/core/src/main/resources/org/jobrunr/storage/sql/mysql/migrations/v014__improve_job_stats.sql).

**Comment by rdehuyss** [comment]
Hi @shivamkapoor9999 - is the issue solved? Do you know why JobRunr had access before and now not anymore?

**Comment by shivamkapoor9999** [comment]
@rdehuyss We degraded jobrunr version to again v5.3.2.. and now with same permission settings things are working fine.. seems some problem with latest version v6.0.0

**Comment by rdehuyss** [comment]
Hi @shivamkapoor9999 - hhhm, really strange but as I cannot reproduce and if you cannot give me a reproducible github project, I'm afraid I cannot help.

Which MySql version are you on?

**Comment by shivamkapoor9999** [comment]
Hi @rdehuyss, we are using mysql version - 8.0.23
Some insignts:
- On latest version we got permission issue while accessing jobrunr_jobs_stats view even after granting all permissions to our user
- On v5.3.2 this view is accessible

**Comment by rdehuyss** [comment]
Hi @shivamkapoor9999 ,

I did try the whole upgrade again and all works perfectly. This is JobRunr running on MySQL first with v5.3.2. and then with v6.0.0. One migration was applied:

```
Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v015__alter_table_backgroundjobserver_add_name.sql}
```

Without a reproducible scenario, I'm afraid I cannot do more for you. Feel free to reach out for a support contract or a Pro version if you don't get this solved. Then I can further help you and on top of that, you're supporting open-source development.

### Version 5.3.2
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/567842/216552516-d8089ebf-2810-44e4-b3fb-89846c2ac852.png">

### Version 6.0.0
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/567842/216552643-f56d5a03-20d4-4792-9bd1-6285b231a1ae.png">

**Comment by sohanh** [comment]
Hi @rdehuyss I have also experienced similar error on upgrading to Mysql 8.0.23 on version 6.0.0

**Comment by rdehuyss** [comment]
Hi @sohanh - can you provide me with a repo that reproduces the issue?
