### ISSUE TITLE
Total job time is long

### ISSUE THREAD

**Issue by vasanthkumar97** [jobrunr/jobrunr#672]
Hello,

We are using jobrunnr 5.3.1 and mysql as our db. 

Our jobs are short jobs and we want near real time processing. 
What we are observing is difference between createdAt and updatedAt for Successful jobs is 10 seconds, when there are no more jobs in PROCESSING state, whereas process duration noted in the jobasjson column is 1 second.

I want to understand is the 9 seconds delta normal behavior. We are using the default batch size and enough workers in the worker pool. 
Poll duration is also the default.

**Comment by rdehuyss** [comment]
Yes - near real time processing is part of Pro offering. Please see the part about **instant job processing** in the [docs](https://www.jobrunr.io/en/documentation/pro/).

**Comment by vasanthkumar97** [comment]
I have reduced polling interval to 5s , What is the best we could do on the free version, We are a small startup and cannot afford the pro license
