### ISSUE TITLE
after update to 6.0.0  there is no  maven spring starter repository.[BUG]

### ISSUE THREAD

**Issue by Hardcore-fs** [jobrunr/jobrunr#674]
### JobRunr Version

5.3.3

### JDK Version

11

### Your SQL / NoSQL database

irelevent

### What happened?

there are continual messages about upgrading from 5.3.3 to 6.0.0

however the maven repository for  "spring boot starter" stops at 5.3.3
https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-starter

so it's not a simple case of just updating hte references in the maven build.

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

**Comment by jloisel** [comment]
As stated in the doc:
https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-3-starter
https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-2-starter

**Comment by rdehuyss** [comment]
Thanks, @jloisel !

**Comment by rdehuyss** [comment]
Docs have been updated to reflect changes.
