### ISSUE TITLE
Apply a fix delay between retry requests 

### ISSUE THREAD

**Issue by ahdadou** [jobrunr/jobrunr#678]
Hello
we are using Jobrunr 5.1.7
The issue we encountered is: we cannot specify a fixed time between attempts. 
for exemple : 20 retries with a fixed delay of 3min .

**Comment by rdehuyss** [comment]
Hey @ahdadou  - this is an option available with JobRunr Pro (although perhaps not enough documented). I'll make sure to improve to the documentation asap.

See the part `Custom Retry Policy` on the [JobRunr Pro website](https://www.jobrunr.io/en/documentation/pro/).

> **Custom Retry Policy**: Do you have some special needs regarding retrying failed Jobs? Then use the CustomRetryPolicy where you can specify the time to wait between each retry or just implement your own RetryPolicy if you want to have full control.
