### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HarithaGunda** [jobrunr/jobrunr#679]
### JobRunr Version

5.3.3

### JDK Version

Java 17 SDK

### Your SQL / NoSQL database

MySQlServer 

### What happened?

I am using the following code to create jobrunr tables prepended with the given table prefix. but ican see it ending up in creating duplicate tables. I mean it created set of tables starting wth jobrunr_ and other set of tables with the given table prefix. I am using spring boot application and version is 3.0.1.
Is it the problem with the usage of the api?	useStorageProvider(SqlStorageProviderFactory.using(applicationContext.getBean(DataSource.class),
						tablePrefix, StorageProviderUtils.DatabaseOptions.CREATE))
Note: tablePrefix is populated witht the value from the props :
org.jobrunr.database.skip-create=false
org.jobrunr.database.table-prefix=_ABC_DOMAIN_.

Any advice would be appreciated .

Thanks in Advance

### How to reproduce?

JobRunr.configure()
				.useJobActivator(applicationContext::getBean)
				useStorageProvider(SqlStorageProviderFactory.using(applicationContext.getBean(DataSource.class),
						tablePrefix, StorageProviderUtils.DatabaseOptions.CREATE)))
				.withJobFilter(new RetryFilter(retryCount))
				.useBackgroundJobServerIf(isBackgroundJobServerEnabled,
					usingStandardBackgroundJobServerConfiguration().andWorkerCount(workerThreadsCount),true)
				.useDashboardIf(isDashboardEnabled)
				.initialize();

**Comment by rdehuyss** [comment]
Closing this without answer as not following community guidelines:

As this is an open-source project where we try to make a living from,
we kindly ask you to have a complete Github Personal Profile (Name and Company details or LinkedIn Profile).

I'm really sorry but I don't see why I should provide free support if you're not willing to provide me the above details. Please comment on this issue again as soon as your Github profile is complete. I will then reopen the issue.

On top of that, I don't understand your problem nor is your code properly formatted.

**Comment by HarithaGunda** [comment]
Could you please recheck as i have updated the Git profile.
