### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HarithaGunda** [jobrunr/jobrunr#680]
### JobRunr Version

5.3.3

### JDK Version

Java 17 SDK

### Your SQL / NoSQL database

MySQlServer 

### What happened?

 I am using the following code to create jobrunr tables prepended with the given table prefix. but i can see it ending up in creating duplicate tables. I mean it created set of tables starting wth jobrunr_ and other set of tables with the given table prefix(ABC_DOMAIN_jobrunr_).
 I am using spring boot application and version is 3.0.1.

Is it the problem with the usage of the api ?
It seems some issue inthe way i am creating StorageProvider.

useStorageProvider(SqlStorageProviderFactory.using(applicationContext.getBean(DataSource.class),
tablePrefix, StorageProviderUtils.DatabaseOptions.CREATE))

Note: tablePrefix is populated with the value from the property file  :
org.jobrunr.database.skip-create=false
org.jobrunr.database.table-prefix=ABC_DOMAIN.

Any advice would be appreciated .

Thanks in Advance

### How to reproduce?

JobRunrConfiguration.JobRunrConfigurationResult jobRunrConfigurationResult = JobRunr.configure().useJobActivator(applicationContext::getBean).useStorageProvider(storageProvider)
.withJobFilter(new RetryFilter(retryCount)).useBackgroundJobServerIf(isBackgroundJobServerEnabled,usingStandardBackgroundJobServerConfiguration().andWorkerCount(workerThreadsCount), true).useDashboardIf(isDashboardEnabled).initialize();

**Comment by HarithaGunda** [comment]
how to stop the spring boot starter from creating the tables since i want to do from the code explicitly. The reason being I am not mentioning the jobrunr properties in the application property file instead pulling from the Zookeeper node.

Any suggesstion if I want the JobRunr to take the keys from the Zookeeper while configuring the Job?

**Comment by rdehuyss** [comment]
It's all in the docs. Search for skip-create.

**Comment by rdehuyss** [comment]
Feel free to star the repo if you're enjoying JobRunr!

**Comment by rdehuyss** [comment]
And please do not create duplicate issues, this is open-source software. Also, the discussions would have been a better place to ask this.

**Comment by HarithaGunda** [comment]
Sorry for my unawareness. I tried reopening the issue but unfortunately i could not and ended up in raising a new one . Can I know the link for the discussions site?

And I did set the SKIP_CREATE option to the DatabaseOptions but didnot worked . It created the duplicate tables.
Changed the code to the below:
JobRunrConfiguration.JobRunrConfigurationResult jobRunrConfigurationResult=JobRunr.configure()
.useJobActivator(applicationContext::getBean).useStorageProvider(SqlStorageProviderFactory.using(applicationContext.getBean(DataSource.class),"jopadmin_", StorageProviderUtils.DatabaseOptions.SKIP_CREATE)).withJobFilter(new RetryFilter(retryCount)).useBackgroundJobServerIf(isBackgroundJobServerEnabled,usingStandardBackgroundJobServerConfiguration().andWorkerCount(workerThreadsCount),true).useDashboardIf(isDashboardEnabled)
				.initialize();

**Comment by rdehuyss** [comment]
Then please create a repo that reproduces the issue (which saves me time).

This is all used by a lot of people (and well tested) so I'm quite sure there is no problem.

**Comment by rdehuyss** [comment]
You should also just just one of two methods to initialize JobRunr - combing the two is a bad idea.

You can pass environment variables to replace spring boot properties but all of this is outside the book l snipe of JobRunr.

**Comment by rdehuyss** [comment]
Discussions are right here in GitHub.

**Comment by HarithaGunda** [comment]
Thanks rdehuyss . I have removed the jobrunr spring starter dependecny from the pom and that solved my problem.
