### ISSUE TITLE
[Feature] Allow configure different credentials for JobRunr database migrations

### ISSUE THREAD

**Issue by ilopmar** [jobrunr/jobrunr#687]
**Is your feature request related to a problem? Please describe.**
For production environment we use different users to connect to the database, one for the application itself (with read/write permissions on the database) and another one for the database migrations (we use Flyway) that has permissions to modify the schema.
With Flyway and Spring Boot it's pretty simple to configure a different user for the migrations just overriding `SPRING_FLYWAY_USER` and `SPRING_FLYWAY_PASSWORD` environment variables with the appropriate values. For the application we use `SPRING_DATASOURCE_USERNAME` and `SPRING_DATASOURCE_PASSWORD`.

During the upgrade to JobRunr 6 our application failed to start because the application db user don't have permissions to modify the schema (`jobrurn_xxxx` tables) and JobRunr needs to run its own migrations.

It would be great if it is possible to configure a different database user for JobRunr own db migrations than the one for "normal" execution. Something similar like what Flyway supports.

**Describe the solution you'd like**
I would like to be able to define some configuration in my `application.yml` like:

```yaml
org:
  jobrunr:
    database:
      migrations:
        url: xxxxx # probably not necessary
        user: xxxx
        password: xxxx
```

And then JobRunr uses this new configuration for running its own database migrations but, at the same time, JobRunr uses the default Spring Boot `dataSource` during the execution.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rdehuyss** [comment]
We're adding support for Flyway and Liquibase in JobRunr Pro. I think this would solve your issue?

**Comment by ilopmar** [comment]
Umm... but that should be transparent for users. I mean we shouldn't care about how JobRunr executes its own database migrations, with Flyway, Liquibase or the way they are run at this moment, right?

**Comment by rdehuyss** [comment]
I see what you mean. I'll add this as a Pro feature though 😉 .

**Comment by ilopmar** [comment]
Ok, thanks for your help :)

**Comment by rdehuyss** [comment]
Solved in JobRunr Pro v6.

**Comment by adamalexandru4** [comment]
Honestly, I really think that flyway or liquibase should be available for OSS version. You will increase adoption because developers could try & error integration in their products before buying PRO.
