### ISSUE TITLE
[BUG] Dashboard redirect not working on other browsers than Chrome

### ISSUE THREAD

**Issue by JoonasC** [jobrunr/jobrunr#69]
**Describe the bug**
The redirect from `/` to `/dashboard` when accessing the web dashboard doesn't work on other browsers than Chrome.
The browser gets stuck and doesn't redirect.

**Environment**
I'm using version 1.2.1
I'm running on JRE / JDK 11 
I'm using the following StorageProvider Redis

**To Reproduce**
Start JobRunr with the dashboard enabled and try to access it from any other browser than Chrome.

**Expected behavior**
The dashboard should appear.

**Additional context**

**Comment by rdehuyss** [comment]
Solved in v1.2.2
