### ISSUE TITLE
[Feature] Quarkus extension support for AWS DocumentDB

### ISSUE THREAD

**Issue by fanaSA** [jobrunr/jobrunr#690]
**Is your feature request related to a problem? Please describe.**
JobRunr core has added support for AWS DocumentDB, as shown in issue #62, however, the Quarkus JobRunr extension does not auto configuration for AWS DocumentDB as a storage provider.

**Describe the solution you'd like**
Enable support for AWS DocumentDB in Quarkus Extension as follows:
* Introduce a new database type, as per `quarkus.jobrunr.database.type` configuration property, e.g. `documentdb`
* Introduce an AWS DocumentDB Producer, `JobRunrAwsDocumentDBStorageProviderProducer` that will produce an instance of `org.jobrunr.storage.nosql.documentdb.AmazonDocumentDBStorageProvider`

**Describe alternatives you've considered**
Use JobRunr in stand-alone configuration mode

**Additional context**
N/A

**Comment by rdehuyss** [comment]
@fanaSA  : please star the github repo if you're happy with JobRunr!

**Comment by fanaSA** [comment]
@rdehuyss thank you for the fix 👍🏻

**Comment by fanaSA** [comment]
@rdehuyss just a quick question: do you have an indication on when this fix will be made available?

**Comment by rdehuyss** [comment]
Probably somewhere next week.

**Comment by fanaSA** [comment]
@rdehuyss Awesome, I'll be on the lookout 🚀
