### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SomeshK4** [jobrunr/jobrunr#695]
### JobRunr Version

5.1.4

### JDK Version

Open JDK 11.0

### Your SQL / NoSQL database

MS SQL 

### What happened?

We are running 4 different recurring services on same machine and we are using jobrunr-spring-boot-starter. All of these services are using different tables using schema property. The problem is sometimes the services are not getting executed even if the server is up and running and we have to manually go to the JobRunr Dashboard to trigger the services again. Seems like JobRunr Background server stop executing the recurring services after some time and goes to idle state. 

Note:- All of the 4 services are self contained services independent of each other.

### How to reproduce?

Create two spring boot services with recurring job and use different schemas.

### Relevant log output

```shell
No log output
```

**Comment by rdehuyss** [comment]
Closing due to not following community guidelines.
