### ISSUE TITLE
Is RedisStorageProvider still in beta?

### ISSUE THREAD

**Issue by MegaGio94** [jobrunr/jobrunr#699]
As the title: Is RedisStorageProvider still in beta?
From the site of [JobRunr](https://www.jobrunr.io/en/documentation/installation/storage/) seems like it is still in beta.
I'm asking this purely to know if even under the recent 6.0.0 release this applies.
If so, what challenges implies using RedisStorageProvider?

**Comment by rdehuyss** [comment]
I'm afraid it is - we're considering to move from Redis to RedisStack (as that allows us to use JSON Objects instead pure key value).

Please also use the discussion forum for questions instead of opening issues.
