### ISSUE TITLE
[BUG] Can't figure out why the lambda is not processed correctly .. 

### ISSUE THREAD

**Issue by plosson** [jobrunr/jobrunr#7]
**Describe the bug**
The enqueue code is being done in a spring rest controller such as this: 

@RestController
public class ReportStorageController {
    @GetMapping("/test")
    public String test() {
        BackgroundJob.<ReportService>enqueue(r -> r.test());
        return "ok";
    }
}

ReportService is an interface defined in the spring context and has one @Component (DefaultReportService.class) registered

The exception is 

java.lang.NoSuchMethodException: com.adswizz.ds.swiss.ui.report.storage.ReportStorageController.lambda$test$87095d82$1()

So it seems that when resolving the lambda, it strangely thinks the test call should be made on the controller and not the r instance 

Any idea ?

**Comment by rdehuyss** [comment]
This is indeed a confirmed bug - I was able to reproduce it.

Will be fixed in v0.9.5.
