### ISSUE TITLE
[Feature] Get the retry attempts count

### ISSUE THREAD

**Issue by ahdadou** [jobrunr/jobrunr#700]
We use  **BackgroundJob.enqueu()** for managing certain events several times , we want to get the retry attemps count or at last detecte the latest attempt to make a special logical like "DEAD-QUEUE" in RabbitMQ
Thanks

**Comment by rdehuyss** [comment]
See [JobServerFilter](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/filters/JobServerFilter.java) - this will be part of JobRunr 6.1.
