### ISSUE TITLE
[Question] Configure different schema for jobrunr jobs

### ISSUE THREAD

**Issue by swyftify** [jobrunr/jobrunr#712]
Currently when we deploy canaries to test, they use different schemas to the production schema. In our cases canaries run alongside production, get access to production data, but cannot write back to production. I found no way to specify the schema for the jobrunr tables, and by default they are created in public schema. Is there a way to specify which schema jobrunr tables should be created in?

**Comment by rdehuyss** [comment]
Please use discussions for questions.
