### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by Madhuri1518** [jobrunr/jobrunr#715]
### Runtime information
- __Timestamp__: 2023-03-07T22:35:52.145429Z
- __Location__: BackgroundJobServer 035d3a03-66df-4081-9082-93974ee21d0e
- __JobRunr Version__: null
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 11.0.16
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 035d3a03-66df-4081-9082-93974ee21d0e
(workerPoolSize: 48, pollIntervalInSeconds: 5, firstHeartbeat: 2023-03-07T22:35:45Z, lastHeartbeat: 2023-03-07T22:35:50Z)

#### Concurrent modified jobs:
Job id: 2df5cf97-8f85-44be-acfe-05aa21eb2566
	Local version: 21; Storage version: 22
	Local state: SCHEDULED (at 2023-03-07T22:35:48.078171Z) ← FAILED (at 2023-03-07T22:35:48.028878Z) ← PROCESSING (updated at 2023-03-07T22:23:42.749373Z on BackgroundJobServer 7f739498-13dc-430c-8c54-dfe4ad77d1f8 and started at 2023-03-07T22:18:42.614741Z) ← ENQUEUED (at 2023-03-07T22:12:03Z)
	Storage state: SCHEDULED (at 2023-03-07T22:35:47.455432Z) ← FAILED (at 2023-03-07T22:35:47.455181Z) ← PROCESSING (updated at 2023-03-07T22:23:42.749373Z on BackgroundJobServer 7f739498-13dc-430c-8c54-dfe4ad77d1f8 and started at 2023-03-07T22:18:42.614741Z) ← ENQUEUED (at 2023-03-07T22:12:03Z)
Job id: 1e3ea5e8-5b39-4cc7-bb6f-d343e797ee7f
	Local version: 15; Storage version: 16
	Local state: SCHEDULED (at 2023-03-07T22:35:48.087280Z) ← FAILED (at 2023-03-07T22:35:48.030039Z) ← PROCESSING (updated at 2023-03-07T22:35:18.790221Z on BackgroundJobServer 2d94c9d3-310c-49d8-97b2-85c6f9ba645b and started at 2023-03-07T22:19:26.704515Z) ← ENQUEUED (at 2023-03-07T22:12:03Z)
	Storage state: SCHEDULED (at 2023-03-07T22:35:49.090262Z) ← FAILED (at 2023-03-07T22:35:49.089989Z) ← PROCESSING (updated at 2023-03-07T22:35:18.790221Z on BackgroundJobServer 2d94c9d3-310c-49d8-97b2-85c6f9ba645b and started at 2023-03-07T22:19:26.704515Z) ← ENQUEUED (at 2023-03-07T22:12:03Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForOrphanedJobs(JobZooKeeper.java:126)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:98)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

Jobs are going down frequently. On restarting java service, the jobs are getting created again

**Comment by rdehuyss** [comment]
I'm afraid I cannot help you as you did something to the JobRunr library as it is not reporting the version, which it normally does.

**Comment by Madhuri1518** [comment]
Please let us know if we miss something regarding the version. Job runr version is 5.3.1

We are running many jobs at once and the CPU utilization is 100%. We want to make sure that the jobrunr jobs are up even though the CPU utilization is 100%. Due to this error, the jobs are going down

**Comment by rdehuyss** [comment]
I would love to help you but I cannot help everybody for free. If you want, there is a Pro subscription that comes with support.

JobRunr runs millions of jobs per hour with some customers without any problem.

**Comment by rdehuyss** [comment]
And the solution is not that hard I think...
