### ISSUE TITLE
[Feature] make database colum "log" configureable in spring-autoconfigure

### ISSUE THREAD

**Issue by jdickel** [jobrunr/jobrunr#73]
Currently we're using (or starting to use) the jobrunr for our recurring jobs and imports to third-party systems.
We were using the simple @Scheduled from spring-boot so far but after discovering jobrunr it felt a great opportunity to give our projectmanager the chance to overwatch and control or manually start those jobs. 
We're using mariadb as DB.

**Is your feature request related to a problem? Please describe.**
Our Log is mostly way longer than the size of the "jobAsJson" text column in mariadb, so it exceeded the size of the log (jobAsJson) column in the database which caused the job to fail because it couln't persist the changes to the db.
So i had to create those tables by hand and i'm unable to adjust the log column inside the properties file.

**Describe the solution you'd like**
A property inside the application.properties would be cool to select the size of the log column.
So the user can decide between SMALL, MEDIUM and LONG text as the log column. 
This way the user can still use the autoconfigure from spring without the need of adjusting the database manully.
Especially in a container context it's not a fun thing to manipulate the DB by hand.

**Describe alternatives you've considered**
* Another possibility is to (easily) override the sql creation scripts. So you can just place your custom SQL to create the jobrunr tables.
* Instead of writing the logs into the db you could also store the log in a .log file physically on the filesystem so you're also able to access the logs via FTP or similar.

Off-Topic
Thanks for maintaining and creating that project. Appreciate it!
We might look forward to buy a pro version if it fit's for all our other usecases.

**Comment by rdehuyss** [comment]
Hi, 

Thanks for your suggestion. Just a small question, 12 days ago I changed the medium text - is that not enough for you?

Because performance wise, more size is not so good as the jobAsJson is the actual job which is deserialized and used in memory when running jobs.

**Comment by jdickel** [comment]
For me that's totallty fine (for now).

But still i'd also like to see some kind of externalized logging tbh. What do you think about that?

I would see many benefits like the direct access per ssh/ftp without the need of deserilization as well as "unlimited" amount of logs.

**Comment by rdehuyss** [comment]
With externalized logging do you mean Job Progress?

As your Jobs are just service method calls, you could easily use any existing logging framework, including slf4j, that logs to whatever location you want. 

I probably don't understand your question, to be honest :-)

**Comment by jdickel** [comment]
Yes and no. First of all, yes i mean the [job progress/logging](https://www.jobrunr.io/en/documentation/background-methods/logging-progress/#logging).
I do **not** want to have a separate logging to have the logs inside a file **additionally**.

But **instead** of using the database column "jobAsJson" as the log persistance you could write the jobProgress (which is the log, right?) into a file and just store the filepath/filename in the database. So you're having a more or less unlimited amount of logs without being limited to MEDIUMTEXT while not getting any performance issues.

What i mean is to externalize the log out of the database into a file.
Of course i could add another logger but i'll still have the limit of the column size/performance. Just wanted to point out, that an external file has some other pros in contrast to storing the log/jobProgress inside the database.
To also mention the drawback: I feel like this is only useful if you're relying on a large amount of logs instead of just a few lines.

I hope you get my point :) 
Even if this goes beyond my initial request. The initial request has been solved by you 12 days ago!

**Comment by rdehuyss** [comment]
Well, there is a lot more going on behind the scenes:
- one of them is seeing whether jobs are still alive - a server could stop/crash while processing a job
- the jobAsJson also contains the latest status of a job - which is needed to see whether the status transition is valid
- ...

the jobAsJson is in fact the heart of JobRunr - the other columns only are there for fast retrieval/search.

Does this make it clear? 

I'll also close the issue as you mentioned that the initial request was already solved.
