### ISSUE TITLE
[BUG] Incorrect functioning of method StorageProvider.recurringJobExists

### ISSUE THREAD

**Issue by AfonsoFGarcia** [jobrunr/jobrunr#732]
### JobRunr Version

6.1.2

### JDK Version

Temurin 17.0.5

### Your SQL / NoSQL database

PostgreSQL 15.2

### What happened?

1) When running under PostgreSQL (and MySQL as well), the method `StorageProvider.recurringJobExists` fails when no states are passed as parameters. I expect that, as the method allows for no states to be passed, that it does not produce exceptions.
2) When running under H2, the method `StorageProvider.recurringJobExists` always returns false when no states are passed as parameters. I expect that, as the method allows for no states to be passed, that it allows to check for a recurring job independently of the status of its runs.

### How to reproduce?

Please check the provided repository and its README:

https://github.com/AfonsoFGarcia/jobrunr-issue-demo

**Comment by rdehuyss** [comment]
Thanks for reporting!
