### ISSUE TITLE
Logging support for REST calls within a job

### ISSUE THREAD

**Issue by sudhi-git** [jobrunr/jobrunr#738]
Hi,

**Question:** I have an Spring boot application that exposes a REST API which performs a long running operation. I would not like to consume JobRunr in the application that exposes the REST endpoint. 
I would prefer having another Spring boot application where I can consume JobRunr and start jobs to call the REST endpoint. What would be the mechanism to log the info messages originating from the application that exposes the REST endpoint? Is this set up even supported?

Best regards,
Sudhi

**Comment by rdehuyss** [comment]
Not following community guidelines.
