### ISSUE TITLE
[BUG] Windows only - All my workers are stuck querying the ProcessCpuLoad

### ISSUE THREAD

**Issue by benallard** [jobrunr/jobrunr#740]
### JobRunr Version

6.1.3

### JDK Version

AdoptJDK 8

### Your SQL / NoSQL database

H2

### What happened?

All Jobs are stuck in the ENQUEUED state, and not moving from there.

When attaching a debugger I see that out of my 5 workers, 3 are busy in `org.jobrunr.server.JobZooKeeper#notifyThreadIdle`, and 2 in org.jobrunr.jobs.Job#startProcessingOn. All five of them are in the org.jobrunr.server.BackgroundJobServer#getServerStatus method, and all of them querying the "ProcessCpuLoad" value.

### How to reproduce?

queue some jobs, wait for them to finish.

**Comment by benallard** [comment]
Tried with another JDK (temurin 1.8.0_362), and the same problem is occurring.

**Comment by benallard** [comment]
Just tried with Temurin 11 as well, and it's still the same.

The dashboard is running, and reporting some server load regularly, so there might still be some way to get that call running.

**Comment by benallard** [comment]
Moving back to 5.3.3 (including reverse-DB-migration) seems to be working for now. So I might be able to pinpoint the first failing release if necessary.

**Comment by rdehuyss** [comment]
That's really strange as nothing in that part of the code changed with release 6. Also, JobRunr 6 is used already quite a lot of companies so I would expect somebody else to also have this issue...

**Comment by rdehuyss** [comment]
@benallard can you setup a repo that reproduces this?

**Comment by benallard** [comment]
Well, I have mine, but i can't give you that. The first ~30 jobs are working fine, and then it starts hanging. There must be some kind of timeout as well, as sometimes a worker is able to unfreeze itself, and start working on one or two jobs. Maybe special to my case is that the jobs are enqueuing other jobs themselves. I can reproduce it within my test-suite.

**Comment by rdehuyss** [comment]
Enqueueing jobs within jobs is not a problem and tested via integration tests. Again, JobRunr 6 is used by 20% of the JobRunr installations so I think it must be on your side.

If you can provide me a repo that reproduces it, I'll look into it immediately but otherwise I'm afraid I cannot help you...

**Comment by rdehuyss** [comment]
Hi @benallard - I wanted to ask whether you made any progress on a repo that reproduces the issue?

**Comment by rdehuyss** [comment]
Hi @benallard - I'll close the issue for now. If you can provide me with a repo that reproduces it, feel free to re-open.

**Comment by rdehuyss** [comment]
Hi @benallard - were you able to reproduce this?

**Comment by benallard** [comment]
If your question is related to the 6.1.4 release, then yes, the problem is still there.

**Comment by rdehuyss** [comment]
No, I meant more of a reproducible repo.

**Comment by rdehuyss** [comment]
Hi @benallard - which OS are you on? Mac, Linux, Windows?

**Comment by benallard** [comment]
Oh, excellent question! Sorry i didn't came to this myself. Indeed, it could be that it only hapenned during development, as I am on my Windows 10 computer. We had the version shortly in production (Linux something), before I revert back, and it seems that it didn't hapenned there.

**Comment by rdehuyss** [comment]
Now fixed in master branch. Will be part of v6.2 release.

**Comment by rdehuyss** [comment]
Hi @benallard - please try JobRunr v6.2.0. It has a fix for the problem.

**Comment by benallard** [comment]
Congrats on the fix. I can confirm the issue is gone.

**Comment by rdehuyss** [comment]
Now also confirmed on a linux OS (CentOS).
