### ISSUE TITLE
[BUG] The succeeded scheduled task are getting executed again on spring App restart.  

### ISSUE THREAD

**Issue by Ankit2491** [jobrunr/jobrunr#750]
### JobRunr Version

5.3.3

### JDK Version

JDK 17

### Your SQL / NoSQL database

Mysql

### What happened?

Scenario 1: 
`LocalDate localDate = LocalDate.of(2022, 04, 21);
		LocalTime localTime = LocalTime.of(14, 30);
		ZoneId zoneId = ZoneId.of("GMT+05:30");

		ZonedDateTime timeStamp = ZonedDateTime.of( localDate, localTime, zoneId );
		
		scheduler.schedule(id,timeStamp,
				() -> schedulerServrice.executeCustomDateSampleJob());`

The API executeCustomDateSampleJob() just does sysout.

In the above, sample code am providing a date which is a year back. But, still the jobrunr executes it on spring app restart. In production environment say a Job was scheduled for some date1/time1 and it got executed by jobrunr. Then, the application restarts due to some reason then that same job which was scheduled and executed at date1/time1 shouldn't get executed again.

Scenario 2 : Also, in the very first run if you provide a schedule of older dates from now then also it executes.
Not sure if this is designed behavior ? Can this be tweaked by some way so that the older dates task shouldn't get executed.

### How to reproduce?

LocalDate localDate = LocalDate.of(2022, 04, 21);
		LocalTime localTime = LocalTime.of(14, 30);
		ZoneId zoneId = ZoneId.of("GMT+05:30");

		ZonedDateTime timeStamp = ZonedDateTime.of( localDate, localTime, zoneId );
		
		scheduler.schedule(id,timeStamp,
				() -> schedulerServrice.executeCustomDateSampleJob());

**Comment by rdehuyss** [comment]
Closing due to not following community guidelines.

**Comment by Ankit2491** [comment]
I am new to this. Can you help me what was missing in the filed bug to close it without any justification?

**Comment by rdehuyss** [comment]
There is a long page before creating an issue that explains these guidelines...

**Comment by rdehuyss** [comment]
Hi @Ankit2491 - if you would update your github profile, I'm willing to help. But, like I said in the guidelines, I prefer to know whom I'm helping.

I hope your issue is solved.
