### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by sidati20072** [jobrunr/jobrunr#753]
### Runtime information
- __Timestamp__: 2023-04-25T20:51:42.265355Z
- __Location__: BackgroundJobServer 55daa327-a648-4df7-865f-36209faa618f
- __JobRunr Version__: 5.1.7
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 11.0.14.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 0306d206-51d7-49e1-a953-dc658e6b007e
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-04-25T16:14:54.298396Z, lastHeartbeat: 2023-04-25T20:51:29.543356Z)
- BackgroundJobServer id: 55daa327-a648-4df7-865f-36209faa618f
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-04-25T20:45:06.990948Z, lastHeartbeat: 2023-04-25T20:51:28.431261Z)

#### Concurrent modified jobs:
Job id: f8f4514a-4ac6-4278-8c49-dae1dd5be94b
	Local version: 3; Storage version: 5
	Local state: PROCESSING (updated at 2023-04-25T20:48:52.646432Z on BackgroundJobServer 55daa327-a648-4df7-865f-36209faa618f and started at 2023-04-25T20:47:52.261264Z) ← ENQUEUED (at 2023-04-25T20:47:49.422675Z) ← SCHEDULED (at 2023-04-25T20:47:47.432975Z)
	Storage state: ENQUEUED (at 2023-04-25T20:50:48.022078Z) ← SCHEDULED (at 2023-04-25T20:50:06.209051Z) ← FAILED (at 2023-04-25T20:49:51.682230Z) ← PROCESSING (updated at 2023-04-25T20:47:52.261264Z on BackgroundJobServer 55daa327-a648-4df7-865f-36209faa618f and started at 2023-04-25T20:47:52.261264Z) ← ENQUEUED (at 2023-04-25T20:47:49.422675Z) ← SCHEDULED (at 2023-04-25T20:47:47.432975Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

Fatal
JobRunr encountered an exception that should not happen. To resolve this issue, can you please create a [Github issue](https://github.com/jobrunr/jobrunr/issues/new?title=Severe%20JobRunr%20Exception&body=%3C%21--%20Please%20paste%20the%20issue%20content%20generated%20JobRunr%20below.%20--%3E&labels=bug)? To make life easy, you can click here to copy all necessary information to your clipboard and paste it in the Github issue.
You can still cancel the creation of the issue in Github if you think it contains sensitive information..

**Comment by rdehuyss** [comment]
Not using latest JobRunr version.
