### ISSUE TITLE
[BUG] Generated a lot of ENQUEUED jobs

### ISSUE THREAD

**Issue by udoless** [jobrunr/jobrunr#760]
### JobRunr Version

6.1.4

### JDK Version

17

### Your SQL / NoSQL database

mysql5.7

### What happened?

I have a recurring job called **dispatchNewMessageJob**, it's internally a pulsar consumer, so it takes a long time to run. The cron is `*/10 * * * * *`,  the reason why I set such a small interval is that I hope that when my job fails, it can be quickly restarted, and my `background-job-server.poll-interval-in-seconds` is 15.

After starting application a few seconds,  table `jobrunnr_jobs` generated a lot of ENQUEUED jobs.

You can see the trace logs below.

I checked the jobrunnr code and posted that there may be a problem here. The following two `if` may need to be replaced?

ProcessRecurringJobsTask.java, line 50~60

**Original**
```java
if(jobsToSchedule.isEmpty()) {
    LOGGER.trace("Recurring job '{}' resulted in 0 scheduled job.", recurringJob.getJobName());
} else if(jobsToSchedule.size() > 1) {
    LOGGER.info("Recurring job '{}' resulted in {} scheduled jobs. This means a long GC happened and JobRunr is catching up.", recurringJob.getJobName(), jobsToSchedule.size());
    allJobsToSchedule.addAll(jobsToSchedule);
} else if(isAlreadyScheduledEnqueuedOrProcessing(recurringJob)) {
    LOGGER.debug("Recurring job '{}' is already scheduled, enqueued or processing. Run will be skipped as job is taking longer than given CronExpression or Interval.", recurringJob.getJobName());
} else if(jobsToSchedule.size() == 1) {
    LOGGER.debug("Recurring job '{}' resulted in 1 scheduled job.", recurringJob.getJobName());
    allJobsToSchedule.addAll(jobsToSchedule);
}
```

**Should it look like this?**
```java
if(jobsToSchedule.isEmpty()) {
    LOGGER.trace("Recurring job '{}' resulted in 0 scheduled job.", recurringJob.getJobName());
} else if(isAlreadyScheduledEnqueuedOrProcessing(recurringJob)) {
    LOGGER.debug("Recurring job '{}' is already scheduled, enqueued or processing. Run will be skipped as job is taking longer than given CronExpression or Interval.", recurringJob.getJobName());
} else if(jobsToSchedule.size() > 1) {
    LOGGER.info("Recurring job '{}' resulted in {} scheduled jobs. This means a long GC happened and JobRunr is catching up.", recurringJob.getJobName(), jobsToSchedule.size());
    allJobsToSchedule.addAll(jobsToSchedule);
} else if(jobsToSchedule.size() == 1) {
    LOGGER.debug("Recurring job '{}' resulted in 1 scheduled job.", recurringJob.getJobName());
    allJobsToSchedule.addAll(jobsToSchedule);
}
```

Because my job is every 10 seconds, and this task is every 15 seconds, so every `jobsToSchedule.size() > 1` is satisfied, thus entering an infinite loop. And if you change the order of `if`, you can skip running. I'm not sure if this modification will have any other effects, I hope to get some guidance, thank you!

### How to reproduce?

.

### Relevant log output

```shell
https://gist.github.com/udoless/5aac9b42fd558e1599d4daffa15420cb
```

**Comment by rdehuyss** [comment]
Can you please complete your GitHub profile as requested by the community guidelines?

**Comment by udoless** [comment]
> Can you please complete your GitHub profile as requested by the community guidelines?

Of course, I have done.

**Comment by rdehuyss** [comment]
Thx!

Well, what happens in fact is that you say to JobRunr: run this job every 10 seconds (= 6 times per minute) but only check whether there are new jobs every 15 seconds (= 4 times per minute). So, only possible thing to do is to schedule these recurring jobs twice on some runs. 

Regarding your comment:
> Should it look like this?

No, as it is important that no runs are skipped (even when a long GC happens, ... ).

The docs have been updated to reflect this. See the [Recurring Job docs](https://www.jobrunr.io/en/documentation/background-methods/recurring-jobs/#important-remarks).
