### ISSUE TITLE
[BUG]Trying to create two recurring jobs across different projects which are pointing to the same backend database ending in up in an issue

### ISSUE THREAD

**Issue by haritha-gunda** [jobrunr/jobrunr#778]
### Discussed in https://github.com/jobrunr/jobrunr/discussions/776

<div type='discussions-op-text'>

<sup>Originally posted by **haritha-gunda** May 30, 2023</sup>
Trying to create two recurring jobs(Job1 and Job2) with same table prefix across different projects(Project A and Project B) which are pointing to the same backend database ending in up in an issue where in either Job1 will end up in creating a record in the JOBRUNR_BACKGROUNSERVERS . so the problem here is when the job 1 has made the entry in the background server only that job1 can end up in smoothly scheduling the recurrent job. Job2 will try be placed in Enqueue mode and later entering into the Failed state.

I am using the Fluent API to create the recurring job in the both the projects.

Code to reproduce:

Code snippet for Job1 :

  @Bean
  public JobRunrConfiguration.JobRunrConfigurationResult initJobRunr(
      final ApplicationContext applicationContext) {
    return JobRunr.configure()
        .useJobActivator(applicationContext::getBean)
        .useStorageProvider(
            SqlStorageProviderFactory.using(
                applicationContext.getBean(DataSource.class), "ABC_"))
        .withJobFilter(new RetryFilter(2))
        .useBackgroundJobServer()
        .initialize();
  }
  @Bean
  public JobScheduler initJobScheduler(
      final JobRunrConfiguration.JobRunrConfigurationResult jobRunrConfigurationResult) {
    return jobRunrConfigurationResult.getJobScheduler();
  }

 applicationContext
                .getBean(JobScheduler.class)
                .scheduleRecurrently(
                        "Job1",
                        "*/5 * * * *",
                        service -> test())

Code snippet for Job2 : 
@Bean
  public JobRunrConfiguration.JobRunrConfigurationResult initJobRunr(
      final ApplicationContext applicationContext) {
    return JobRunr.configure()
        .useJobActivator(applicationContext::getBean)
        .useStorageProvider(
            SqlStorageProviderFactory.using(
                applicationContext.getBean(DataSource.class), tablePrefix))
      .withJobFilter(new RetryFilter(retryCount))
        .useBackgroundJobServer()
        .initialize();
  }

  @Bean
  public org.jobrunr.scheduling.JobScheduler initJobScheduler(
      final JobRunrConfiguration.JobRunrConfigurationResult jobRunrConfigurationResult) {
    return jobRunrConfigurationResult.getJobScheduler();
  }

 @PostConstruct
  public void cacheWriterJob() {
    try {
      applicationContext
          .getBean(JobScheduler.class)
          .scheduleRecurrently(
              "Job2",
              cronPattern,
              service ->test2());
    } catch (final Exception exc) {
      log.error("Error Occurred", exc);
    } 
  }

Note: I am using Jobrunr 5.3.3 version and using the maven dependency :	
<dependency>
			<groupId>org.jobrunr</groupId>
			<artifactId>jobrunr</artifactId>
			<version>${jobrunr.version}</version>
		</dependency>

Please let me know the issue for not creating a record in background server table. Ideally i should see 2 recorda in the table where in each entry associated to each job.
</div>

**Comment by rdehuyss** [comment]
Not following community guidelines and cross posting from discussion

**Comment by rdehuyss** [comment]
See https://github.com/jobrunr/jobrunr/discussions/769#user-content-i-wont-answer-every-question.

Feel free to reach out for a Pro license that comes with support.

**Comment by haritha-gunda** [comment]
> Not following community guidelines and cross posting from discussion

Sorry i created a discussion on this issue and later looked into the guidelines to create a bug.

**Comment by rdehuyss** [comment]
> > See [#769 (comment)](https://github.com/jobrunr/jobrunr/discussions/769#user-content-i-wont-answer-every-question).
> > Feel free to reach out for a Pro license that comes with support.
> 
> Could you please confirm??
> 
> I am happy to lookout for considering pro version but wanted a confirmation that it cannot be supported as part of the free version .

Can I know what is the reason that you're trying to manage multiple JobRunr clusters with one DB?

**Comment by haritha-gunda** [comment]
here my job1 functionality is to do certain task of checking whether some services are down or not and the job2 will perform another functionality of changing the user template changes . The details about the services and the user template changes ,both are saved in the same database and we have only one db source used in the project. 
My understanding was if i want to create a new recurring job instance using Job Schduler , i should first create the instance of JobRunrConfiguration.JobRunrConfigurationResult. since the above mentioned two jobs are getting schduled in different projects , so ended up in creating the JobRunrConfiguration.JobRunrConfigurationResult.instances seperately.

**Comment by rdehuyss** [comment]
No, you should configure JobRunr only once.
