### ISSUE TITLE
Liveness probe with kubernates deployement

### ISSUE THREAD

**Issue by vasanthkumar97** [jobrunr/jobrunr#783]
Hi there ,

We are deploying jobrunnr kubernates , Is there a liveliness and readiness probe support out of the box from jobrunnr that kubernates can understand to see the health of pods. 

Today whenever job runnr goes down, due to exceptions, compile errors in code. background job servers table is empty and thats the only indication we have. 
We have tried setup jobrunnr in spring boot and used actuator endpoint. But between actuator and jobrunnr internal monitoring pods are unstable and they keep going down

**Comment by rdehuyss** [comment]
Not following community guidelines.
