### ISSUE TITLE
[BUG] Requeue and delete from dashboard broken

### ISSUE THREAD

**Issue by geirsagberg** [jobrunr/jobrunr#795]
### JobRunr Version

6.2.2

### JDK Version

OpenJDK 20.0.1

### Your SQL / NoSQL database

Oracle 19c

### What happened?

When clicking either "Requeue" or "Delete" from dashboard, there is an error, and nothing happens.

This seems to be because of this commit: https://github.com/jobrunr/jobrunr/commit/2fb59f1187611949d86d2be2be35780ef685676a

because the `requeue` and `delete` methods still refer to `prop.match.params.id`, not `jobId`. This causes the calls to use `undefined` as jobId.

### How to reproduce?

Go to dashboard, find a failed job, and click Requeue or Delete

**Comment by geirsagberg** [comment]
Workaround: Rolled back to 6.2.1

**Comment by rdehuyss** [comment]
Released with v6.2.3!

Thanks for your PR and please star the repo if you're enjoying JobRunr!
