### ISSUE TITLE
Cannot view dashboard

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#8]
The link `http://localhost:8000/dashboard/overview` does not work. The content appears but quickly disappears:

![image](https://user-images.githubusercontent.com/1297759/83261591-431f2d00-a1c4-11ea-9525-9beaf1bb9f1f.png)

`http://localhost:8000/dashboard/jobs` and the rest of the tabs works fine however.

Once I enqueue some jobs, it starts to work

**Comment by rdehuyss** [comment]
I don't really understand how this error happens - the only reason I can think of is that there is no BackgroundJobServer available - so not a single BackgroundJobServer was configured... 

This way, I could reproduce it. Was this perhaps the case?

**Comment by cemremengu** [comment]
I will try to reproduce it and let you know
