### ISSUE TITLE
[Feature] Support for JPA StorageProvider

### ISSUE THREAD

**Issue by s-jepsen** [jobrunr/jobrunr#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A JPA implementation of StorageProvider, so i can use the solution in my spring-data-jpa projects.

**Describe alternatives you've considered**

**Additional context**
Will make the product fit better in with software using JPA for other purposes.

**Comment by rdehuyss** [comment]
I don't understand this feature request - the only thing that is needed is a `DataSource`, which you will need anyway when you are using spring-data-jpa.

So, I don't see the advantage of adding the JpaStorageProvider. Why would you like/need it?

**Comment by rdehuyss** [comment]
Closing for now - please re-open if you still think it is relevant.

As said, JobRunr already supports projects using spring-data-jpa - it only needs a DataSource.
