### ISSUE TITLE
I need to disable JobRunr in a spring boot application, per JVM

### ISSUE THREAD

**Issue by SharkFourSix** [jobrunr/jobrunr#802]
I have a maven multi-module project, with the following dependency graph:

![image](https://github.com/jobrunr/jobrunr/assets/18681730/3578044b-f63f-47a2-a3b1-3158af93abed)

**CORE-COMPONENT** contains a configuration that initialized a JobScheduler, which I make heavy use of in **COMPONET-1**.

The components 1 and 2 are launched in separate JVM instances, with the core component being a shared library module. 

## Issue description

Because the two child components share a core component, the job scheduler in component-2 ends up reloading jobs from the database that have been persisted in component-1, causing issues and logs to show up in component-2.

## Current behavior

**COMPONENT-2** does other domain business logic and I'd like to disable JobRunr from being activated in this component.

I have tried using spring's ```@ConditionalOnBean``` to disable my configuration that initializes my JobScheduler instance. While it works (does not load previously persisted jobs), there seems to be some other default JobScheduler that gets spun up.

## Expected behavior

- I would like JobRunr to completely be disabled in COMPONENT-2 without any of its instances being booted up.

**Comment by ghahramani** [comment]
How come this does not follow the community guidelines? There should be a way to disable Jobrunr conditionally as all other Spring Boot libraries/components or am I missing something?

**Comment by rdehuyss** [comment]
The community guidelines can be [found here](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D) .

On top of that, this is not an issue but a question for which the answer can be found in the documentation.
