### ISSUE TITLE
[Feature] enhance jobrunr metrics with job name

### ISSUE THREAD

**Issue by karmingc** [jobrunr/jobrunr#805]
**Is your feature request related to a problem? Please describe.**
Currently using Spring Boot and leveraging metrics to create dashboard and monitors.
However, I noticed in the `jobrunr.jobs.*` metrics that they do not have any tag related to the job name to easily identify which job is failing immediately.

We could technically determine through the dashboard, but it is not deterministic through the metrics by themselves.

**Describe the solution you'd like**

Add the job name to the `jobrunr.jobs.*` metrics

**Describe alternatives you've considered**

No idea comes to mind, open to suggestions however.

**Additional context**
n/a

**Comment by rdehuyss** [comment]
Hi @karmingc , as an open-source developer is hard where to draw a line on which feature to add in which version of the product. JobRunr Pro has this feature and even more. See https://www.jobrunr.io/en/documentation/pro/observability/.

I still need to feed 3 kids and plant trees🌳🌴🌲.

**Comment by karmingc** [comment]
Hi @rdehuyss, my team is in the process of acquiring the pro license so we haven't had the chance to validate if it has everything we need.

That said, I would have been happy to contribute as well -- for this type of feature, should we have simply made a PR, or issue + PR?

Thanks

**Comment by rdehuyss** [comment]
Can I know which team / company you're working for? Feel free to reach out to me via the email address mentioned on the website.
