### ISSUE TITLE
[BUG] When auto recovery, it must clear the recurringJobRuns in ProcessRecurringJobsTask.

### ISSUE THREAD

**Issue by xiangjan** [jobrunr/jobrunr#808]
### JobRunr Version

6.0.0

### JDK Version

11

### Your SQL / NoSQL database

MySQL

### What happened?

A bug happened!
We use Mysql as datasoure and use 2 backgound job server.
Hi, I'm a user of jobrunr, last night our jobrunr server had amount of job were  enqueued. 
I research about that, I found the server have history like below.
server 1's DB connection was disconnected in 17th this month, so the master changed to server 2.  and it auto recovery soon, the server 1 is slave now.
And the server 2 DB connection was disconnected in last weekend. so the server 1 change to master and automatically remove server 2. the problem was happen in here. the server 1's recurringJobRuns in ProcessRecurringJobsTask has the information of recurring job were 17th this month, so it calculate the jobs from 17th to this weekend. so amount of jobs are enqueued.
I wish clear the map of value recurringJobRuns  when the server will change to slave. 

### How to reproduce?

I wish clear the map of value recurringJobRuns  when the server will change to slave. 

or shutdown the auto recovery server. (when failover is happen, the time of restart service may have along time. in that time it change to master, this issue can be happen..

**Comment by rdehuyss** [comment]
Not following community guidelines.
