### ISSUE TITLE
[BUG] jackson.JobParameterDeserializer kotlin deserialization broken

### ISSUE THREAD

**Issue by fkowal** [jobrunr/jobrunr#818]
### JobRunr Version

6.3.0

### JDK Version

OpenJDK Runtime Environment (build 17+35-2724)

### Your SQL / NoSQL database

Postgres 15.2

### What happened?

`JobParameterDeserializer` does not work with Kotlin data classes
it never could since it uses an private version of `ObjectMapper()` without `KotlinModule`

basic fix attached in https://github.com/jobrunr/jobrunr/pull/817/files
that enable configuring the internal fallback `objectMapper`

### How to reproduce?

using any custom jackson module ie `arrow.integrations.jackson.module.ArrowModule`
and even some basic `KotlinModule` features such as `SingletonSupport`
require a configured ObjectMapper instance

so a private empty `ObjectMapper` is a no go

so the `JobParameterDeserializer` objectmapper needs to be configurable

**Comment by rdehuyss** [comment]
Marking as stale as no response anymore on PR #817.

**Comment by rdehuyss** [comment]
I can for a fact say that the KotlinModule is used automatically if added to the classpath for parameter deserialization. This makes this bug report invalid.
