### ISSUE TITLE
Question: Is it possible to pass as argument a protobuf generated object? 

### ISSUE THREAD

**Issue by thahgr** [jobrunr/jobrunr#823]
With Jobrunr 6.3.0 and spring boot 2x I am trying create jobs where the argument is a java object generated by protobufs

I get the following error 

```
 org.jobrunr.scheduling.exceptions.JobMethodNotFoundException: service.printLog(MyObject)
	caused by: one of the JobParameters is not deserializable anymore
```

`MyObject` is generated from a protobuf, it has a private no argument-constructor as written here   https://www.jobrunr.io/en/documentation/background-methods/passing-arguments/

These objects created for gRPC services can be deserialized but need custom deserializers. Something similar happens with kafka listeners that listen to proto objects

**Comment by rdehuyss** [comment]
Not following community guidelines.
