### ISSUE TITLE
@Job annotation retry and jobfilters do not work after upgrading to spring 3

### ISSUE THREAD

**Issue by seniordanel** [jobrunr/jobrunr#825]
### JobRunr Version

6.1.2

### JDK Version

17

### Your SQL / NoSQL database

mongodb

### What happened?

I am using the @Job annotation for jobs and i have the retry and the jobfilters attribute (both server and client filters) in the annotation. After upgrading to spring 3.1.2 the retry and jobfilters in the annotation do not work.

### How to reproduce?

use the @job annotation from jobrunr on the job.

**Comment by rdehuyss** [comment]
For the open-source version, I do not provide support unless you run the latest and greatest JobRunr version (v6.3.0)

Please upgrade and if the issue persists, create a github repo that reproduces the issue.

**Comment by rdehuyss** [comment]
Also, please complete your github profile as requested in the community guidelines.
