### ISSUE TITLE
[BUG] jobScheduler fails when using a wrapper class with Kotlin function as parameter

### ISSUE THREAD

**Issue by tms0** [jobrunr/jobrunr#827]
### JobRunr Version

6.3.0

### JDK Version

Kotlin 1.9.0

### Your SQL / NoSQL database

In memory

### What happened?

Hi,

I want to hide the jobScheduler implementation, so I don't call it directly but instead use a wrapper and pass a Kotlin function as parameter:

```
class JobSchedulerWrapper(
    private val jobScheduler: JobScheduler
) {

    fun enqueue(job: () -> Unit) {
        jobScheduler.enqueue(job)
    }
}

val jobSchedulerWrapper = JobSchedulerWrapper(jobScheduler)
jobSchedulerWrapper.enqueue { println("test KO") }
```

Then it fails with the following exception :
`org.jobrunr.JobRunrException: Could not find a BackgroundJobRunner: either no JobActivator is registered, your Background Job Class is not registered within the IoC container or your Job does not have a default no-arg constructor.`

**NB**: If I change the signature of the wrapper method to pass the function as a `JobLambda`, then it works (but I don't want to leak this class in my wrapper signature).

```
fun enqueue(jobLambda: JobLambda) {
    jobScheduler.enqueue(jobLambda)
}

val jobSchedulerWrapper = JobSchedulerWrapper(jobScheduler)
jobSchedulerWrapper.enqueue { println("test OK") }
```

### How to reproduce?

Here's a very simple project to reproduce the issue : https://github.com/tms0/jobrunr-wrapper-kotlin-function/

**Comment by rdehuyss** [comment]
I'm afraid the only way to do so is using the `JobLambda` as it is used at runtime to determine how to analyse the job.

If the type is not known (e.g. a `Unit`), JobRunr can not do it's thing.

**Comment by tms0** [comment]
Hi @rdehuyss,

Thanks for your quick answer. Do you have a solution to hide the actual implementation ? I tried a lot of things but it always fails.

**Comment by rdehuyss** [comment]
No, I'm afraid not. Since it is a runnable Java 8 functional interface, I wonder if it's worth the time and effort - it will not leak out to any of your other classes.
