### ISSUE TITLE
Getting the following error :- java.sql.SQLException: View 'jobrunr_jobs_stats' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

### ISSUE THREAD

**Issue by as-sher** [jobrunr/jobrunr#828]
### JobRunr Version

6.1.3

### JDK Version

1.8

### Your SQL / NoSQL database

mysql 8.0

### What happened?

whenever I open the UI for jobrunr I get this error :-Getting the following error :- java.sql.SQLException: View 'jobrunr_jobs_stats' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

some methods used in the view are missing in the rds :- rollup_group_item, rollup_sum_switcher

### How to reproduce?

whenever I open the UI for jobrunr I get this error :-Getting the following error :- java.sql.SQLException: View 'jobrunr_jobs_stats' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

### Relevant log output

```shell
java.sql.SQLException: View 'jobrunr_jobs_stats' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

**Comment by rdehuyss** [comment]
For the open-source version, I do not provide support unless you run the latest and greatest JobRunr version (v6.3.0)

And, in your case, the exception is quite clear and is outside of the scope of JobRunr. I'm afraid I cannot help you as my time to work on the OSS version is limited. A JobRunr Pro subscription comes with support where I can help you.
