### ISSUE TITLE
[BUG] Unable to build a quarkus native application (com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.sql.TIMESTAMP)

### ISSUE THREAD

**Issue by tms0** [jobrunr/jobrunr#831]
### JobRunr Version

6.3.0

### JDK Version

OpenJDK 17

### Your SQL / NoSQL database

N.A.

### What happened?

Unable to build a Quarkus native application, it fails with the following error : 

```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.sql.TIMESTAMP. This error is reported at image build time because class org.jobrunr.utils.reflection.autobox.InstantForOracleTypeAutoboxer is registered for linking at image build time by command line
```

Expected : The native image build is working.

### How to reproduce?

See this Github project : https://github.com/tms0/jobrunr-quarkus-native
For Building a native app (with Docker running) : `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true`

**Comment by tms0** [comment]
Also, see this page explaining the issue and how it can be resolved : https://quarkus.io/version/main/guides/native-reference#i-get-a-analysiserrorparsingerror-when-building-a-native-executable-due-to-an-unresolvedelementexception-what-can-i-do

**Comment by tms0** [comment]
Ok, I understand.

I found a way to fix it using GraalVM substitution mechanism. I will open a PR soon.

IMHO, the proper solution is to split the library in modules to embed only what is really need, but it would be a really big change.

**Comment by tms0** [comment]
This is way more work than I expected (the exception reported was the first of a long list of issues), but there is some really good progress. I need to register all classes that will be used for reflection and there is no automatic way to find them.

**Comment by rdehuyss** [comment]
@tms0 - all the needed classes can be found in the [Spring Boot 3 implementation](https://github.com/jobrunr/jobrunr/blob/master/framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/aot/JobRunrBeanFactoryInitializationAotProcessor.java). I indeed also spent a lot of time to find out all the necessary classes so I feel your pain...

**Comment by rdehuyss** [comment]
Hi @tms0! Do you perhaps havea branch work your WIP? That way, I can perhaps help?

**Comment by tms0** [comment]
Hi @rdehuyss ,

I created the PR, this is still draft, but it works for the main features (enqueuing job. recurring job, dashboard, etc).

There is one remaining issue with lambda serialization:

When using a lambda for enqueuing a job, the lambda is serialized and the class declaring the lambda is read using `getResourceAsStream`. In order to work in GraalVM, there is two things to do:
- Register the capturing class using `lambdaCapturingTypes` : https://www.graalvm.org/latest/reference-manual/native-image/metadata/
- Register the capturing class as a resource : https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/

I didn't find a way to detect the lambda capturing class automatically in a build step, so the workaround is to manually add the annotation on the application side :  `@RegisterForReflection(lambdaCapturingTypes = "org.example.MyService")`.
Then, a build step will find this annotation and register this class to the be added to the native executable resources.

I guess there is the same issue with Spring 3 Native ?

**Comment by rdehuyss** [comment]
@tms0 : I wasn't fully awake yesterday and didn't mention you in the release, sorry for that. This has been fixed: see https://github.com/jobrunr/jobrunr/releases.

**Comment by tms0** [comment]
No problem, thank you for the quick release and the mention :-)
