### ISSUE TITLE
[Feature] How to use job metadata?

### ISSUE THREAD

**Issue by ctron-te** [jobrunr/jobrunr#84]
I saw that the `Job` class has a `metadata` field which seems to be empty by default.

How can one set metadata for a job?

**Comment by rdehuyss** [comment]
Hi @ctron-te ,

that's easy (but perhaps not well documented): you inject the `JobContext` (see logging and progress).

Then you can access the metadata using `jobContext.getMetadata().put("test", "test");`.

An example where this is used can be found in the tests: https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/scheduling/BackgroundJobTest.java#L126.

Cheers!
