### ISSUE TITLE
[Feature] RedisStorageProvider in BETA

### ISSUE THREAD

**Issue by arielazzi** [jobrunr/jobrunr#853]
**Is your feature request related to a problem? Please describe.**
We would like to use Jobrunr with Redis using `RedisStorageProvider`. However, as it still is in BETA, so it is advised not to use it.

**Describe the solution you'd like**
Either a prod ready version of RedisStorageProvider or some kind of official statement about the future of RedisStorageProvider.

**Describe alternatives you've considered**
We could use another database to store Job related information, but in our specific case that would be too much of a hassle considering that we are already using Redis for something unrelated to Jobrunr.

**Additional context**
None.

**Comment by patkujawa-wf** [comment]
https://github.com/jobrunr/jobrunr/discussions/735 has helpful context

**Comment by rdehuyss** [comment]
See discussion #735. Thanks, @patkujawa-wf ! ♥️
