### ISSUE TITLE
Is there an option to configure job storage time?

### ISSUE THREAD

**Issue by quantaprasanth** [jobrunr/jobrunr#863]
I'm seeing the default storage for a job is 1 day. 

![image](https://github.com/jobrunr/jobrunr/assets/143435607/540e097d-ecef-41d4-9e0e-8213a1f67b68)

Is it possible to add a method to the JobBuilder to set permanent retention of a job?

**Comment by rdehuyss** [comment]
Not following community guidelines, second remark. Third time will result in a permanent ban for this repo.

Instead of spamming open-source developers, please read the docs where this is mentioned and use the appropriate medium to ask questions (discussion instead issues). Last and final warning.

**Comment by rdehuyss** [comment]
See also the text when you create a [bug report](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D). It's not something we put in for fun.
