### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by sc-moonlight** [jobrunr/jobrunr#868]
We turned on the embedded dashboard in JobRunr pro, and I see some "exception(s) that should not happen".  Logging as requested.

### Runtime information
- __Timestamp__: 2023-11-12T03:50:37.815746250Z
- __Location__: BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee
- __JobRunr Version__: 6.2.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.7
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: c2e27acb-a375-4cc9-ad48-213991c6f0ee
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-01T10:06:10.701529Z, lastHeartbeat: 2023-11-12T03:50:33.373019Z)
- BackgroundJobServer id: df8e5112-82ac-4165-a912-4bf409c857d1
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-01T10:06:10.778820Z, lastHeartbeat: 2023-11-12T03:50:37.045929Z)
- BackgroundJobServer id: 942f8fa4-8a14-40d2-a7aa-b83b284ebc93
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-01T10:06:11.125631Z, lastHeartbeat: 2023-11-12T03:50:34.127190Z)
- BackgroundJobServer id: 32fd2804-b5f3-49c0-838f-f673dd796b7b
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-01T10:06:11.135434Z, lastHeartbeat: 2023-11-12T03:50:34.562143Z)
- BackgroundJobServer id: b0e7be64-d458-4d6b-aa3f-90ba6e4f05e4
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-01T10:06:20.341622Z, lastHeartbeat: 2023-11-12T03:50:37.377729Z)
- BackgroundJobServer id: 135985e1-2909-4a46-a21a-cb262871acd6
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-07T17:41:33.043763Z, lastHeartbeat: 2023-11-12T03:50:33.751647Z)
- BackgroundJobServer id: 5ce412a1-f78d-4cac-879f-2e458cf7d020
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-07T17:41:37.173992Z, lastHeartbeat: 2023-11-12T03:50:35.266500Z)
- BackgroundJobServer id: b4d4e94b-ba98-43ea-9f1e-4248b3a31f1b
(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2023-11-07T17:41:38.425362Z, lastHeartbeat: 2023-11-12T03:50:35.929561Z)

#### Concurrent modified jobs:
Job id: f2227a3d-1b7d-42f9-83c7-d4d7f35142bb
Occurred at: 2023-11-12T03:50:37.815710756Z
	Local version: 15; Storage version: 16
	Local state: ENQUEUED (at 2023-11-12T03:50:37.147958331Z) ← SCHEDULED (at 2023-11-12T03:46:33.732582284Z) ← FAILED (at 2023-11-12T03:46:33.732501853Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714989350Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714989350Z) ← ENQUEUED (at 2023-11-12T03:46:33.700459609Z) ← SCHEDULED (at 2023-11-12T03:45:12.637523388Z) ← FAILED (at 2023-11-12T03:45:12.637399911Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621441091Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621441091Z)
	Storage state: ENQUEUED (at 2023-11-12T03:50:36.800764529Z) ← SCHEDULED (at 2023-11-12T03:46:33.732582284Z) ← FAILED (at 2023-11-12T03:46:33.732501853Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714989350Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714989350Z) ← ENQUEUED (at 2023-11-12T03:46:33.700459609Z) ← SCHEDULED (at 2023-11-12T03:45:12.637523388Z) ← FAILED (at 2023-11-12T03:45:12.637399911Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621441091Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621441091Z)
Job id: 61fa7b5a-717b-4a60-94b1-4b5e99a502e6
Occurred at: 2023-11-12T03:50:37.815710756Z
	Local version: 15; Storage version: 16
	Local state: ENQUEUED (at 2023-11-12T03:50:37.147959183Z) ← SCHEDULED (at 2023-11-12T03:46:33.732709797Z) ← FAILED (at 2023-11-12T03:46:33.732637390Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714939092Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714939092Z) ← ENQUEUED (at 2023-11-12T03:46:33.700456596Z) ← SCHEDULED (at 2023-11-12T03:45:12.637523400Z) ← FAILED (at 2023-11-12T03:45:12.637464107Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621371950Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621371950Z)
	Storage state: ENQUEUED (at 2023-11-12T03:50:36.800765784Z) ← SCHEDULED (at 2023-11-12T03:46:33.732709797Z) ← FAILED (at 2023-11-12T03:46:33.732637390Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714939092Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714939092Z) ← ENQUEUED (at 2023-11-12T03:46:33.700456596Z) ← SCHEDULED (at 2023-11-12T03:45:12.637523400Z) ← FAILED (at 2023-11-12T03:45:12.637464107Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621371950Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621371950Z)
Job id: 91bed2d1-60e1-45fd-84ab-6220730ef223
Occurred at: 2023-11-12T03:50:37.815710756Z
	Local version: 15; Storage version: 16
	Local state: ENQUEUED (at 2023-11-12T03:50:37.147959412Z) ← SCHEDULED (at 2023-11-12T03:46:33.732709795Z) ← FAILED (at 2023-11-12T03:46:33.732637383Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714960735Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714960735Z) ← ENQUEUED (at 2023-11-12T03:46:33.700460128Z) ← SCHEDULED (at 2023-11-12T03:45:12.637833127Z) ← FAILED (at 2023-11-12T03:45:12.637758042Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621424635Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621424635Z)
	Storage state: ENQUEUED (at 2023-11-12T03:50:36.800766601Z) ← SCHEDULED (at 2023-11-12T03:46:33.732709795Z) ← FAILED (at 2023-11-12T03:46:33.732637383Z) ← PROCESSING (updated at 2023-11-12T03:46:33.714960735Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:46:33.714960735Z) ← ENQUEUED (at 2023-11-12T03:46:33.700460128Z) ← SCHEDULED (at 2023-11-12T03:45:12.637833127Z) ← FAILED (at 2023-11-12T03:45:12.637758042Z) ← PROCESSING (updated at 2023-11-12T03:45:12.621424635Z on BackgroundJobServer c2e27acb-a375-4cc9-ad48-213991c6f0ee and started at 2023-11-12T03:45:12.621424635Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:83)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.processJobListAndPublishJobEnqueuedMessage(ProcessScheduledJobsTask.java:107)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.processJobList(ProcessScheduledJobsTask.java:78)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:55)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:79)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:79)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
Hi @sc-moonlight , as a Pro customer you have access to JobRunr Pro where you can log issues related to JobRunr Pro.

Before doing so, can you please upgrade to the latest version (6.3.3) as I think this has already been resolved? And could you update your github profile with your actual name 😊? This helps me diagnosing issues. Feel free to also send an email.

Closing for now. If this happens again on the latest JobRunr version, feel free to reopen in the JobRunr Pro repo.
