### ISSUE TITLE
[Feature] Redis group segregation

### ISSUE THREAD

**Issue by ctron-te** [jobrunr/jobrunr#87]
**Is your feature request related to a problem? Please describe.**
We would like to use Redis as a backing store and use a single instance to run multiple "groups" of Jobrunr servers. Something like this:

![image](https://user-images.githubusercontent.com/58181729/104922183-43a64700-5992-11eb-8543-8354657b0745.png)

**Describe the solution you'd like**
We thought the easier would be to allow a prefix to be configured in `LettuceRedisStorageProvider` and `JedisRedisStorageProvider`. This prefix would be added at the beginning of every keys.

Are they any alternative ways to achieve this result? If the solution using a prefix is the way to go I'm happy to make a PR for it.

**Comment by rdehuyss** [comment]
Hi @ctron-te, I'd like to gather some additional context about this issue.

Why wouldn't you setup multiple redis instances - e g one for each functional domain? Segregation within one redis cluster can indeed be done with a prefix, but from an architectural point, I think it would make more sense to split the redis cluster, no?

Just trying to understand what you want to achieve...

**Comment by ctron-te** [comment]
Hi @rdehuyss, yes that's definitively an alternative. However, it might too much overhead from an ops perspective to create a new Redis instance for each context (even using solutions like ElasticCache).

We have a microservices architecture with over 20 services. Let's say we wanted all of them to have their own Jobrurn context, it would be quite painful to manage 20 clusters, 20 connection strings etc....

I think the two approaches are valid and it would be good to offer both to suit different needs.

**Comment by rdehuyss** [comment]
Hi @ctron-te , a PR for this would definitely be an option...

**Comment by ctron-te** [comment]
alright thanks, will do when I have a moment 👍
