### ISSUE TITLE
[Feature] Use Debezium for starting jobs faster

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#88]
**Is your feature request related to a problem? Please describe.**
Now, it can take up to 15 seconds before a job is started. I want it to start instantly.

**Describe the solution you'd like**
Using Debezium, we could do change tracking of the jobs table. This would allow the job to be started immediately.

**Describe alternatives you've considered**
I don't know of any alternatives...

**Comment by rdehuyss** [comment]
Resolved in JobRunr Pro branch feature/v5.0.0.

**Comment by marcantoine-bibeau** [comment]
Hi @rdehuyss, does that mean that we could enqueue a job that would be instantly executed? We have cases (in test and some production use cases) where we would like to enqueue a job but not wait the polling period (5 sec minimum). We are currently looking to buy the Pro version but that is something we really mean :)

**Comment by rdehuyss** [comment]
Yes. I've also noticed the docs are a bit outdated as since JobRunr Pro 6.2 you have realtime scheduling per 100ms instead of per second. I'll try to update it tomorrow.

**Comment by marcantoine-bibeau** [comment]
When you say realtime scheduling does that mean I can enqueue a job and not wait a worst case minimum of 5 seconds (min polling period) for that job to be executed ?

**Comment by rdehuyss** [comment]
Yes.

P.s.: I also reached out to you via LinkedIn (I think it was you at least 😄 ). It sometimes helps for a quick chat.
