### ISSUE TITLE
[Feature] Proper way of handling batch job with thousands of child jobs

### ISSUE THREAD

**Issue by filipafw** [jobrunr/jobrunr#897]
**Is your feature request related to a problem? Please describe.**
I have a batch job, which can lead to thousands od child jobs in the future. I am trying to find the best way to handle this case, meaning that I want to all jobs to be enquened properly, or none.  

Using batches (https://www.jobrunr.io/en/documentation/pro/batches/) seems to be the proper mechanism to use. However there is one problem, which prevents me to use that solution - if I would have thousands of jobs, event with one simple UUID as a parameter, parent's job name would be HUGE and will break JobRunr Dashboard web app while trying to check job details

Alternative way is to use `JobRequestScheduler.create` method, which creates batches of jobs with 5000 elements. That's good solution, however if there will be more than 5000 jobs, and persisting 2nd batch will fail, 1st one will already be executed. So this solution works just for <= 5000 jobs.

**Describe the solution you'd like**
Batch way - possibility to set name for a batch job, so dashboard would not break

JobRequestScheduler.create way - possibility to set size of batch (currently its fixed to 5000) or persist all jobs at once.

**Additional context**

How I tested that case using Kotlin, Spring and JobRunr Pro 6.3.5

```kotlin
import org.jobrunr.jobs.lambdas.JobRequest
import org.jobrunr.jobs.lambdas.JobRequestHandler
import org.jobrunr.scheduling.BackgroundJob
import org.jobrunr.scheduling.JobBuilder
import org.jobrunr.scheduling.JobRequestScheduler
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import java.util.*
import java.util.concurrent.atomic.AtomicInteger

@RestController
@RequestMapping("/api/jobrunr-test")
class JobRunrTestEndpoint(private val jobRequestScheduler: JobRequestScheduler) {

    @GetMapping("/test1")
    @Transactional
    fun test1() {
        // create list of 10000 jobs
        val jobs = (1..15000).map {
            TestJob.create()
        }
        val counter = AtomicInteger(0)
        jobRequestScheduler.create(jobs.stream().map {
            val cntVal = counter.incrementAndGet()
            if (cntVal > 12000) {
                error("error")
            }
            println("not error: $cntVal")
            it
        })
    }

    @GetMapping("/test2")
    fun test2() {
        val list = (1..15000).map { UUID.randomUUID() }
        BackgroundJob.startBatch {
            batch(list)
        }
    }

    fun batch(uuids: List<UUID>) {
        uuids.mapIndexed { index, it ->
            BackgroundJob.enqueue { println("Success: $it") }
            if (index > 12000) {
                error("error")
            }
        }
    }
}

class TestJob(val uuid: UUID) : JobRequest {
    override fun getJobRequestHandler() = TestJobHandler::class.java

    companion object {
        fun create(uuid: UUID = UUID.randomUUID()): JobBuilder =
            JobBuilder.aJob()
                .withLabels("test")
                .withJobRequest(TestJob(uuid))
    }
}

@Service
class TestJobHandler : JobRequestHandler<TestJob> {
    override fun run(job: TestJob) {
        println("Success: ${job.uuid}")
    }
}
```

**Comment by rdehuyss** [comment]
Fi @filipafw , I do not know who you are or which company (and thus which JobRunr Pro license) this is related to. Can you please update your profile or reach out via email? 

On top of that, I don't understand what this is about. Batch jobs are designed to have 1000's of child jobs and this does not impact the dashboard so issue this does not make sense to me. I'll close the issue for now and please email me if you need further help.
