### ISSUE TITLE
[BUG] Recurring job creates unexpected multiple jobs

### ISSUE THREAD

**Issue by garfberg** [jobrunr/jobrunr#899]
### JobRunr Version

6.3.3

### JDK Version

Java(TM) SE Runtime Environment (build 12.0.1+12)

### Your SQL / NoSQL database

Elasticsearch 7.8.1

### What happened?

Hi,

When a recurring job is being processed inside ProcessRecurringJobsTask.java, it computes a list a job (using the hashmap "recurringJobRuns"to get last run timestamp) representing potential missed runs. It looks like it is not synchronized with database state.

PS: It is not related to pollInvervalSeconds = 5 seconds vs recurring job duration = 1 minute

The following sequence shows the problem :
1) Create a recurring job using jobScheduler.scheduleRecurrently() with a job id.

2) After a certain time, delete the job using jobScheduler.delete() with job id.

At his point the recurring job is successfully deleted from the database but the hashmap "recurringJobRuns" is not updated (keeping the last run timestamp value)

3) Create a new recurring job with the same previous job id.
When method processRecurringJobs() calls getJobsToSchedule(recurringJob, from, upUntil), this method uses old timestamps from recurringJobRuns hashmap, thus using a wrong value because the first recurring job was deleted before and the key should have been deleted from the hashmap.

As I understand the current source code, using a new job Id each time I create a recurring job may create a slow but slow memory leak as the recurringJobRuns hashmap will keep increasing in size.

I made the following fix in ProcessRecurringJobsTask.java: (may create a RR if you want)
```java
    private List<RecurringJob> getRecurringJobs() {
        if (storageProvider.recurringJobsUpdated(recurringJobs.getLastModifiedHash())) {
            this.recurringJobs = storageProvider.getRecurringJobs();
        }
        // SUGGESTED FIX START   
        // synchronize recurringJobRuns with database result
        Map<String, String> oldJobIssToDelete = new HashMap<>();
        for (String jobId : recurringJobRuns.keySet()) {
            oldJobIssToDelete.put(jobId, null);
        }
        for (RecurringJob rj : this.recurringJobs) {
            oldJobIssToDelete.remove(rj.getId());
        }
        for (String oldJobId : oldJobIssToDelete.keySet()) {
            // clean up
            recurringJobRuns.remove(oldJobId);
        }
        // SUGGESTED FIX END

        return this.recurringJobs;
    }
```

### How to reproduce?

1) Create a recurring job using jobScheduler.scheduleRecurrently() with a job id.

```java
String testId = "testcase-id";
jobScheduler.scheduleRecurrently(testId, Duration.ofMinutes(1L), () -> {
	System.out.println("test1 " + Instant.now().toString());
});
```
Wait 5 minutes

2) After a certain time, delete the job using jobScheduler.delete() with job id.

```java
jobScheduler.delete(testId);
```
Wait 10 minutes

3) Create a new recurring job with the same previous job id.

```java
String testId = "testcase-id";
jobScheduler.scheduleRecurrently(testId, Duration.ofMinutes(1L), () -> {
	System.out.println("test2 " + Instant.now().toString());
});
```

### Relevant log output

```shell
The stdout output looks like:
test1 T0+1min
test1 T0+2min
test1 T0+3min
test1 T0+4min
test1 T0+5min
test2 T0+15min   
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+15min <= should not happen
test2 T0+16min
test2 T0+17min 
...
```

**Comment by rdehuyss** [comment]
Thanks for your bug report but this is in fact intended behaviour for JobRunr OSS. A feature of JobRunr Pro is that you pause and resume recurring jobs (which is exact what you're building here).

The above works out-of-the-box in JobRunr Pro and as I have some kids to feed, I will not allow a PR for this. I hope you understand my situation.

**Comment by garfberg** [comment]
Undestood. Have a nice day.
