### ISSUE TITLE
[BUG] fix integration to quarkus v 3.6.4  after container.instance deprecated 

### ISSUE THREAD

**Issue by ShiboTanany** [jobrunr/jobrunr#907]
### JobRunr Version

6.3.3

### JDK Version

OpenJDK 17

### Your SQL / NoSQL database

H2

### What happened?

Exception thrown after adding  @Recurring 
No such method which is     JobScheduler scheduler = container.instance(JobScheduler.class); 
in JobRunrRecurringJobRecorder 

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

**Comment by rdehuyss** [comment]
As Quarkus is not following semver releases, we are unable to fix this in JobRunr v6. This is already fixed in JobRunr v7.

**Comment by ShiboTanany** [comment]
thanks for replying, when we are expecting to release v7?
I would like to share my passion to join as a contributor if possible

**Comment by rdehuyss** [comment]
See also the [Quarkus Zulip Chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20integrations.20break.20due.20to.20no.20semver.20releases) where I've voiced my concern related to this.

JobRunr v7 will be released somewhere in Q1 (when it's finished 😄 ).
