### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maborg** [jobrunr/jobrunr#92]
**Describe the bug**
When losing db connection Job on RDS AWS Aurora seem to try to restart and continue to loop in error

**Environment**
I'm using version 1.0.0
I'm running on JRE / JDK 11
I'm using the following StorageProvider Mysql on AWS RDS

**To Reproduce**
It's happening on our complex project and I'm not able to reproduce it on mysql

**Expected behavior**
I expect jobrunr to exit and let the container to restart, now is blocking everything

**Additional context**
LOG FILE
[logs-insights-results.zip](https://github.com/jobrunr/jobrunr/files/5909453/logs-insights-results.zip)
this is the log... as you can see it's blocked and not exiting.

**Comment by rdehuyss** [comment]
As this is a project that I maintain in my free time, I can only give support on the latest version of JobRunr.

Can you please upgrade your JobRunr version before creating an issue?
