### ISSUE TITLE
[BUG] When losing db connection Job on RDS AWS Aurora seem to try to restart and continue to loop in error

### ISSUE THREAD

**Issue by maborg** [jobrunr/jobrunr#93]
Describe the bug
When losing db connection Job on RDS AWS Aurora seem to try to restart and continue to loop in error (the connection error happens when Aurora increment the capacity instance from 1 to 2 as result for the start of jobs using the db)

Environment
I'm using version 1.2.5
I'm running on JRE / JDK 11
I'm using the following StorageProvider Mysql on AWS RDS

To Reproduce
It's happening on our complex project and I'm not able to reproduce it on mysql

Expected behavior
I expect jobrunr to exit and let the container to restart, now is blocking everything

Additional context
LOG FILE
[logs-insights-results (1).zip](https://github.com/jobrunr/jobrunr/files/5911005/logs-insights-results.1.zip)
this is the log... as you can see it's blocked and not exiting.

**Comment by rdehuyss** [comment]
I've been thinking about this and I'm still not convinced that JobRunr should exit the VM (let's say you also handle web requests in the container where JobRunr is running). 

Personally, I would not want any library to exit my vm.

I do however have a workaround for you: You could create a health endpoint that is monitored by Docker/k8s. To do so, you would need to:
- Inject the `BackgroundJobServer` in a Spring Rest Controller
- Create a Simple Pojo that represents the health where you:
  - return the status of the `BackgroundJobServer`. You can query it with `BackgroundJobServer.isRunning()`.
  - return the status of your AWS Aurora instane (select 1 from DUAL;)
- Then, you can create a Docker health check to see whether the health of both is ok (see https://docs.docker.com/engine/reference/builder/#healthcheck)

Does this make sense?
