### ISSUE TITLE
Exception during initialization on openJDK 21

### ISSUE THREAD

**Issue by 0xiDen** [jobrunr/jobrunr#936]
### JobRunr Version

6.3.3

### JDK Version

openjdk-21-ea+23

### Your SQL / NoSQL database

Postgres 12

### What happened?

On initialization I get the following exception:
```

java.lang.NumberFormatException: For input string: \"21-ea\"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.lang.Integer.parseInt(Integer.java:661)
    at java.lang.Integer.parseInt(Integer.java:777)
    at org.jobrunr.server.DesktopUtils.getJavaVersion(DesktopUtils.java:55)
    at org.jobrunr.server.DesktopUtils.<clinit>(DesktopUtils.java:16)
    ... 40 common frames omitted
```

### How to reproduce?

run your app with an early access java or set java.version env variable to something that's not parsable by `Integer.parseInt(value)`.
For example take a look at this [Dockerfile](https://github.com/docker-library/openjdk/blob/892e5d672c4e8ffb94c65e1e52d5fbbeb9dba5a7/21/jdk/slim-bullseye/Dockerfile#L27) if you run this you'll get an error because the `getJavaVersion()` method in DesktopUtils assumes that java.version is always int that I think is a false assumption.

I think this should have a fallback behavior:
https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/DesktopUtils.java#L55

**Comment by rdehuyss** [comment]
Thanks for reporting. Any reason you're still using 21-ea and not a release version?

**Comment by 0xiDen** [comment]
My pleasure. 
No stumbled upon this while using openJDK docker images. apparently their still use ea binaries

**Comment by rdehuyss** [comment]
Solved in v7
