### ISSUE TITLE
[BUG] In start-stop-start scenario all the missed recurring jobs are scheduled and executed

### ISSUE THREAD

**Issue by phejl** [jobrunr/jobrunr#940]
### JobRunr Version

6.3.4

### JDK Version

OpenJDK Runtime Environment Temurin-21+35

### Your SQL / NoSQL database

MongoDB 4.0.4

### What happened?

Single node setup with recurring job (ie. interval of 15s).

1. BackgroundJobServer is started, jobs get regularly scheduled, all good.
2. BackgroundJobServer is stopped and stays like that for some time (let's say a minute).
3. BackgroundJobServer is started. Job is executed multiple times for all the missed schedules. With confusing log "Recurring job 'jobrunr.repro.TestJob.perform()' resulted in 5 scheduled jobs. This means a long GC happened and JobRunr is catching up.".

This is somewhat unexpected and confusing. The server keeps some metadata between the runs which makes the difference from initial start.

### How to reproduce?

https://github.com/phejl/jobrunr-start-stop-start
Local docker as prerequisite.
Run `./gradlew test`

### Relevant log output

```shell
    12:40:21.526 [backgroundjob-worker-pool-2-thread-5] INFO  jobrunr.repro.TestJob -- Performed 1
    12:40:36.537 [backgroundjob-worker-pool-2-thread-6] INFO  jobrunr.repro.TestJob -- Performed 2
    12:40:50.554 [Test worker] INFO  jobrunr.repro.ReproTest -- Stopping the server
    12:40:50.554 [Test worker] INFO  o.jobrunr.server.BackgroundJobServer -- BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
    12:40:50.560 [Test worker] INFO  o.jobrunr.server.BackgroundJobServer -- BackgroundJobServer and BackgroundJobPerformers stopped
    12:40:50.560 [Test worker] INFO  jobrunr.repro.ReproTest -- So far the job has been executed 2 times
    12:41:50.561 [Test worker] INFO  jobrunr.repro.ReproTest -- Starting the server
    12:41:50.568 [Test worker] INFO  o.j.s.t.ScheduledThreadPoolJobRunrExecutor -- ThreadManager of type 'ScheduledThreadPool' started
    12:41:50.572 [backgroundjob-zookeeper-pool-3-thread-1] INFO  o.jobrunr.server.BackgroundJobServer -- JobRunr BackgroundJobServer (a6ac6b20-42fc-4aa0-985c-3fd60e22f78e) using MongoDBStorageProvider and 64 BackgroundJobPerformers started successfully
    12:41:50.572 [backgroundjob-zookeeper-pool-3-thread-1] INFO  org.jobrunr.server.ServerZooKeeper -- Server a6ac6b20-42fc-4aa0-985c-3fd60e22f78e is master (this BackgroundJobServer)
    12:41:51.565 [backgroundjob-zookeeper-pool-3-thread-2] INFO  org.jobrunr.server.JobZooKeeper -- Recurring job 'jobrunr.repro.TestJob.perform()' resulted in 5 scheduled jobs. This means a long GC happened and JobRunr is catching up.
    12:41:51.585 [backgroundjob-worker-pool-4-thread-5] INFO  jobrunr.repro.TestJob -- Performed 3
    12:41:51.586 [backgroundjob-worker-pool-4-thread-7] INFO  jobrunr.repro.TestJob -- Performed 4
    12:41:51.586 [backgroundjob-worker-pool-4-thread-8] INFO  jobrunr.repro.TestJob -- Performed 5
    12:41:51.586 [backgroundjob-worker-pool-4-thread-6] INFO  jobrunr.repro.TestJob -- Performed 6
    12:41:51.589 [backgroundjob-worker-pool-4-thread-9] INFO  jobrunr.repro.TestJob -- Performed 7
    12:42:06.599 [backgroundjob-worker-pool-4-thread-11] INFO  jobrunr.repro.TestJob -- Performed 8
```

**Comment by phejl** [comment]
Thank you @rdehuyss. I fully understand your point of making money on OSS and I'm perfectly ok with that. Perhaps just to reassure myself sure we have mutual understanding of the issue: I'm not asking for the feature of executing missed jobs - actually the opposite is happening the missed jobs are executed in the OSS version in stop-start scenario right after start.

Thanks for your great work.

**Comment by rdehuyss** [comment]
Thanks for the compliment!

Yeah, I see it as the feature of pausing and resuming recurring jobs. On top of that, in the Pro dashboard, you can also stop and start background job servers. So all is covered there.

If you can convince your company to take a Pro version, you will have your request feature out of the box and my eternal gratitude 😊.
