### ISSUE TITLE
[BUG] Instruction 191 not found error

### ISSUE THREAD

**Issue by ManosKaravas** [jobrunr/jobrunr#946]
### JobRunr Version

6.3.4

### JDK Version

Java 17.0.5

### Your SQL / NoSQL database

PostgreSQL 14.5

### What happened?

A bug happened!
My goal is to set TenantContext to a specific tenant in a multitenant environment so that job is executed for this tenant and retrieve data needed from its schema (Each tenant owes a schema)

### How to reproduce?

```java
   jobScheduler().enqueue(uuid,
                        () -> {
                            try {
                                TenantContext.setCurrentTenant(tenant);
                                myService.taskToDo(uuid, dataInputDto, requesterId);
                            } catch (IOException ex) {
                                throw new RuntimeException(ex);
                            } finally {
                                TenantContext.clear();
                            }
                        });
```

### Relevant log output

```shell
22-02-2024 14:30:31.187 [http-nio-8081-exec-2] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver->logException() - Resolved [org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)]

No further messages printed on log.


Method called from Postman :
Status: 400 Bad request
Response: Instruction 191 not found
```

**Comment by rdehuyss** [comment]
Well, as you perhaps saw in the documentation, the Job is analyzed and not everything (including try catch) is supported in JobRunr. See also the [best practices](https://www.jobrunr.io/en/documentation/background-methods/best-practices/#make-the-job-lambda-as-small-as-possible).

That being said, I see 2 easy solutions:
- get a JobRunr Pro license which supports multi tenancy out of the box 😊
- pass the tenantId as a Job argument and set the Tenant as first thing inside your job.

You must remember that Jobs can pass JVM / server boundaries so things like ThreadLocal (what I assume you're doing with the TenantContext) are not available. Instead you should load them first thing inside your job.

Hope this makes sense, if not, I've reached out via LinkedIn.
