### ISSUE TITLE
[Feature] .schedule() with an argument input.

### ISSUE THREAD

**Issue by chakrit** [jobrunr/jobrunr#95]
**Is your feature request related to a problem? Please describe.**

Often we need to schedule one-off tasks to be done in the background, but in the future, for example expiring something after 5 minutes of inactivity or releasing shared resource (i.e. tickets) or, the reverse, polling for status from a remote server for a single entity.

**Describe the solution you'd like**

Just a way to pass argument to `.schedule` like one-off tasks. Since there's no way to specify time with `.enqueue` (which allow args but not time 🤔)

**Describe alternatives you've considered**

A recurrent scanning `.scheduleRecurrent` that scans for things to be done and do it in batches, but this doesn't really scale by the amount of the job. If there's a spike in demand, things would pile up and gets delayed and we can't just increase the number of worker process to keep up.

**Additional context**

n/a

**Comment by rdehuyss** [comment]
Hmm, this is a request I don't understand: `.schedule` accepts a lambda just like `.enqueue`.

You could just do:
```java
String someUrl = "";
BackgoundJob.schedule(() -> service.notifyWebhook(someUrl), Instant.now().plusMinutes(5));
```

Or are you talking about Kotlin?

**Comment by chakrit** [comment]
Nope, I'm just not sure how to use it correctly haha. I thought you'd suppose to use Stream() for supplying arguments.

@rdehuyss This works, thanks for clarifying.

**Comment by rdehuyss** [comment]
You can already have a look on www.jobrunr.io. All methods are explained there.
