### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by eforkin** [jobrunr/jobrunr#968]
### Runtime information
- __Timestamp__: 2024-02-08T06:08:19.480855593Z
- __Location__: BackgroundJobServer 6d13c802-0eff-4522-9c54-445fb7e7a54f
- __JobRunr Version__: 6.1.4
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 17.0.8
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: f1de9a5c-d592-4fae-abec-5ebac6b6273a
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T02:43:23.493414Z, lastHeartbeat: 2024-02-08T06:08:12.361468Z)
- BackgroundJobServer id: 27dd8b1a-6031-4393-9db8-2bdc2a7ffd1d
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T02:43:23.570035Z, lastHeartbeat: 2024-02-08T06:08:12.377109Z)
- BackgroundJobServer id: f443b476-6498-4e4c-a304-459b64052790
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T02:43:34.026953Z, lastHeartbeat: 2024-02-08T06:08:06.156508Z)
- BackgroundJobServer id: 0775d473-afaa-4cd8-b37e-2b2cffa88c62
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T02:43:41.013882Z, lastHeartbeat: 2024-02-08T06:08:14.338325Z)
- BackgroundJobServer id: 1dc5b97d-b638-473f-a8c0-ed5a5ec701ce
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T22:08:15.307417Z, lastHeartbeat: 2024-02-08T06:08:11.466077Z)
- BackgroundJobServer id: 5a60d9bd-d4f9-4469-a087-9d8515c54af0
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T22:08:16.957018Z, lastHeartbeat: 2024-02-08T06:08:16.144846Z)
- BackgroundJobServer id: 40ed5de6-3b9e-41b1-96ee-fd9b5a94f471
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T22:10:00.703074Z, lastHeartbeat: 2024-02-08T06:08:10.666920Z)
- BackgroundJobServer id: 6d13c802-0eff-4522-9c54-445fb7e7a54f
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-07T22:10:04.516205Z, lastHeartbeat: 2024-02-08T06:08:19.130763Z)

#### Concurrent modified jobs:
Job id: 7c3a0c4f-7414-4844-95ca-51b49f858224
	Local version: 3; Storage version: 4
	Local state: SUCCEEDED (at 2024-02-08T06:02:51.204248229Z) ← PROCESSING (updated at 2024-02-08T06:02:25.986181060Z on BackgroundJobServer 6d13c802-0eff-4522-9c54-445fb7e7a54f and started at 2024-02-08T06:02:10.987223820Z) ← ENQUEUED (at 2024-02-08T06:02:10.916829491Z) ← SCHEDULED (at 2024-02-08T05:56:22.859389956Z)
	Storage state: FAILED (at 2024-02-08T06:03:12.070066217Z) ← PROCESSING (updated at 2024-02-08T06:02:10.987223820Z on BackgroundJobServer 6d13c802-0eff-4522-9c54-445fb7e7a54f and started at 2024-02-08T06:02:10.987223820Z) ← ENQUEUED (at 2024-02-08T06:02:10.916829491Z) ← SCHEDULED (at 2024-02-08T05:56:22.859389956Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:76)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2024-02-18T11:59:53.111053543Z
- __Location__: BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9
- __JobRunr Version__: 6.1.4
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 17.0.8
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 738c8858-3700-400e-826b-dd8159d8945f
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:00:32.936263Z, lastHeartbeat: 2024-02-18T11:59:52.558817Z)
- BackgroundJobServer id: 110929e8-a670-4973-95cc-55aece69bd6b
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:00:43.488258Z, lastHeartbeat: 2024-02-18T11:59:44.390458Z)
- BackgroundJobServer id: 3de26702-78a8-441e-b337-c7e4fdd85ca9
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:02:11.246621Z, lastHeartbeat: 2024-02-18T11:59:45.783554Z)
- BackgroundJobServer id: 0c58db07-b190-40f1-9a72-944171daa723
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:02:45.309417Z, lastHeartbeat: 2024-02-18T11:59:44.665537Z)

#### Concurrent modified jobs:
Job id: c7577c0f-094a-4e6a-bbf0-c58b53444a6a
	Local version: 3; Storage version: 4
	Local state: SUCCEEDED (at 2024-02-18T11:58:00.267571410Z) ← PROCESSING (updated at 2024-02-18T11:57:14.749710562Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749617483Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471498Z) ← SCHEDULED (at 2024-02-18T11:39:07.617254637Z)
	Storage state: FAILED (at 2024-02-18T11:58:10.240882951Z) ← PROCESSING (updated at 2024-02-18T11:56:59.749617483Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749617483Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471498Z) ← SCHEDULED (at 2024-02-18T11:39:07.617254637Z)
Job id: ff7dc809-9933-4ef8-b5d7-419529407fa1
	Local version: 3; Storage version: 4
	Local state: SUCCEEDED (at 2024-02-18T11:58:00.269108188Z) ← PROCESSING (updated at 2024-02-18T11:57:14.749711812Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749694828Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471338Z) ← SCHEDULED (at 2024-02-18T11:39:00.601753209Z)
	Storage state: FAILED (at 2024-02-18T11:58:10.240912891Z) ← PROCESSING (updated at 2024-02-18T11:56:59.749694828Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749694828Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471338Z) ← SCHEDULED (at 2024-02-18T11:39:00.601753209Z)
Job id: f591e6d2-b7ba-4b7b-8c29-cdc502f7840f
	Local version: 4; Storage version: 5
	Local state: SUCCEEDED (at 2024-02-18T11:57:45.301862676Z) ← PROCESSING (updated at 2024-02-18T11:57:14.749713142Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:44.739754873Z) ← ENQUEUED (at 2024-02-18T11:56:39.151125101Z) ← SCHEDULED (at 2024-02-18T11:38:54.083282853Z)
	Storage state: FAILED (at 2024-02-18T11:58:10.240722908Z) ← PROCESSING (updated at 2024-02-18T11:56:59.739901305Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:44.739754873Z) ← ENQUEUED (at 2024-02-18T11:56:39.151125101Z) ← SCHEDULED (at 2024-02-18T11:38:54.083282853Z)
Job id: ce09386e-3cdd-4117-88c6-5ccd07b2db28
	Local version: 3; Storage version: 4
	Local state: SUCCEEDED (at 2024-02-18T11:58:00.270028241Z) ← PROCESSING (updated at 2024-02-18T11:57:14.749714042Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749694717Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471447Z) ← SCHEDULED (at 2024-02-18T11:39:05.613638240Z)
	Storage state: FAILED (at 2024-02-18T11:58:10.240900831Z) ← PROCESSING (updated at 2024-02-18T11:56:59.749694717Z on BackgroundJobServer 3de26702-78a8-441e-b337-c7e4fdd85ca9 and started at 2024-02-18T11:56:59.749694717Z) ← ENQUEUED (at 2024-02-18T11:56:54.352471447Z) ← SCHEDULED (at 2024-02-18T11:39:05.613638240Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:76)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2024-02-18T12:11:54.100716408Z
- __Location__: BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723
- __JobRunr Version__: 6.1.4
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 17.0.8
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 738c8858-3700-400e-826b-dd8159d8945f
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:00:32.936263Z, lastHeartbeat: 2024-02-18T12:11:52.878845Z)
- BackgroundJobServer id: 110929e8-a670-4973-95cc-55aece69bd6b
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:00:43.488258Z, lastHeartbeat: 2024-02-18T12:11:44.624126Z)
- BackgroundJobServer id: 3de26702-78a8-441e-b337-c7e4fdd85ca9
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:02:11.246621Z, lastHeartbeat: 2024-02-18T12:11:46.116329Z)
- BackgroundJobServer id: 0c58db07-b190-40f1-9a72-944171daa723
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-14T18:02:45.309417Z, lastHeartbeat: 2024-02-18T12:11:44.893601Z)

#### Concurrent modified jobs:
Job id: cc679744-8168-4201-b8d9-dce66c6440d1
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.748824441Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535334765Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460834373Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472468Z) ← SCHEDULED (at 2024-02-18T11:46:56.054000050Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857397209Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498258087Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460834373Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472468Z) ← SCHEDULED (at 2024-02-18T11:46:56.054000050Z)
Job id: 893b7f42-a640-4eeb-a105-72f3b803fad2
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.724918978Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535336265Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460255811Z) ← ENQUEUED (at 2024-02-18T12:04:35.098272526Z) ← SCHEDULED (at 2024-02-18T11:46:45.026326536Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857562372Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498259287Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460255811Z) ← ENQUEUED (at 2024-02-18T12:04:35.098272526Z) ← SCHEDULED (at 2024-02-18T11:46:45.026326536Z)
Job id: 89515db9-1173-48a9-b6ee-99ad572a5338
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.705105889Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535338235Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460676310Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472417Z) ← SCHEDULED (at 2024-02-18T11:46:53.551530814Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857581912Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498260407Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460676310Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472417Z) ← SCHEDULED (at 2024-02-18T11:46:53.551530814Z)
Job id: 18c3c1ca-a722-48ca-9ce8-edd2df1b4e87
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.726137763Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535339555Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.450617557Z) ← ENQUEUED (at 2024-02-18T12:04:35.098273016Z) ← SCHEDULED (at 2024-02-18T11:46:47.572204755Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857595492Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498261587Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.450617557Z) ← ENQUEUED (at 2024-02-18T12:04:35.098273016Z) ← SCHEDULED (at 2024-02-18T11:46:47.572204755Z)
Job id: d6a2911e-aa46-4de4-b59b-7bb7f4ef8c9a
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.762270741Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535341105Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460523896Z) ← ENQUEUED (at 2024-02-18T12:04:35.098273256Z) ← SCHEDULED (at 2024-02-18T11:46:50.040639457Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857607592Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498262707Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460523896Z) ← ENQUEUED (at 2024-02-18T12:04:35.098273256Z) ← SCHEDULED (at 2024-02-18T11:46:50.040639457Z)
Job id: 718ddae1-e26f-4782-af9a-d5864e50990c
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.724998330Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535343825Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460812462Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472537Z) ← SCHEDULED (at 2024-02-18T11:46:58.552018570Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857619073Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498263707Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460812462Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472537Z) ← SCHEDULED (at 2024-02-18T11:46:58.552018570Z)
Job id: 3a6b9cda-22aa-4892-b7b6-e0643e657038
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.698813612Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535346325Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460770952Z) ← ENQUEUED (at 2024-02-18T12:04:50.248471517Z) ← SCHEDULED (at 2024-02-18T11:46:51.540027770Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857631413Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498264807Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460770952Z) ← ENQUEUED (at 2024-02-18T12:04:50.248471517Z) ← SCHEDULED (at 2024-02-18T11:46:51.540027770Z)
Job id: 52c10af6-261e-47f1-a715-81af65d9710f
	Local version: 6; Storage version: 7
	Local state: SUCCEEDED (at 2024-02-18T12:07:21.722023030Z) ← PROCESSING (updated at 2024-02-18T12:07:21.535348035Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460894024Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472597Z) ← SCHEDULED (at 2024-02-18T11:47:01.056772244Z)
	Storage state: FAILED (at 2024-02-18T12:08:24.857642623Z) ← PROCESSING (updated at 2024-02-18T12:07:06.498265987Z on BackgroundJobServer 0c58db07-b190-40f1-9a72-944171daa723 and started at 2024-02-18T12:06:21.460894024Z) ← ENQUEUED (at 2024-02-18T12:04:50.248472597Z) ← SCHEDULED (at 2024-02-18T11:47:01.056772244Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:76)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
Not running latest JobRunr version
