### ISSUE TITLE
missing info on upgrade to 7.0 from upgrade page

### ISSUE THREAD

**Issue by we-sell-bags** [jobrunr/jobrunr#987]
Info missing on the Caveat screen.

if you replace

   <jobrunr.version>6.3.5</jobrunr.version>

with:
<jobrunr.version>7.0.0-RC.1</jobrunr.version>

you get a java error:

import org.springframework.boot.actuate.info.InfoContributor;
import org.springframework.boot.actuate.info.InfoEndpoint;

It seems 7.X has changed some dependencies for spring boot

**Comment by rdehuyss** [comment]
Hmmm, I'm not following... Can you provide the link to the exact page?

**Comment by we-sell-bags** [comment]
Hi,
ok...  found it,  jobrunr was providing a library reference in 6.x via the maven repository definition.
on 7.0 that reference went away, and caused an error in the compilation of the master project that included jobrunr maven library

I added the spring library back in to the master project... and it's all good...

so technically speaking its not purely jobrunr , but was maven causing  problems with conflicting libraries , which is why the original  reference was removed.
