### ISSUE TITLE
[BUG] Instruction 191 not found when throwing exception in lambda

### ISSUE THREAD

**Issue by michaelcowan** [jobrunr/jobrunr#996]
### JobRunr Version

7.0.0

### JDK Version

Oracle OpenJDK 21.0.1

### Your SQL / NoSQL database

MySQL 8.x

### What happened?

I scheduled a job using an inline function that contains code throwing an exception.
When `create` is called, `JobRunrException` is thrown with a cause of 'Instruction 191 not found'.

Executing the exact same code using a method reference works as expected:
1. Job is scheduled
2. Job runs
3. Job (may) throw exception
4. Retry mechanics step in

### How to reproduce?

The following code witll throw `JobRunrException` during the `create` call:
```java
scheduler.create(aJob()
        .withDetails(() -> {
            throw new RuntimeException("Mock exception");
        }));
```

This code does not throw `JobRunrException`:

```java
public void detail() {
    throw new RuntimeException("Mock exception");
}

// ...

scheduler.create(aJob()
        .withDetails(this::detail));
```

**Comment by auloin** [comment]
Hi @michaelcowan, I'm closing as this issue has already been addressed https://github.com/jobrunr/jobrunr/issues/266#issuecomment-975671009.

**Comment by rdehuyss** [comment]
Please also see the [best practices](https://www.jobrunr.io/en/documentation/background-methods/best-practices/#make-the-job-lambda-as-small-as-possible). You can also use a [JobRequest](https://www.jobrunr.io/en/documentation/background-methods/enqueueing-jobs/#enqueueing-a-job-using-a-jobrequest) if you want to make sure these kinds of errors can't happen.
